---
title: "Aggregate-Distributions"
author: "whh36"
date: "10/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

#Metadata Import

```{r}
#import density data for nnd, voronoi, and r3d

nnddensdata <- read.csv("./data-files/nnddensities.csv") %>%
  mutate(nndx = round(nndx, digits = 3)) %>%
  spread(., key = nndx, value = nnddens) %>%
  mutate(Labelfine = as.character(Labelfine))

vrndensdata <- read.csv("./data-files/voronoidens.csv") %>%
  mutate(x = round(x, digits = 3)) %>%
  select(-count) %>%
  spread(., key = x, value = density) %>%
  mutate(Labelfineshort = as.character(Labelfineshort))

r3densdata <- read.csv("./data-files/r3densities.csv") %>%
  mutate(x = round(x, digits = 3)) %>%
  spread(., key = x, value = density) %>%
  mutate(Labelfine = as.character(Labelfine))
```

```{r}
#import density data for skeleton branch counts, ave branch length, and max branch length

skelbranchdensdata <- read.csv("./data-files/skel.dens.branch.csv")

skelbranchdensdata <- skelbranchdensdata %>%
  mutate(Labelfineshort = i) %>%
  select(-i) %>%
  mutate(Labelfineshort = as.character(Labelfineshort)) %>%
  mutate(LabelLength = nchar(Labelfineshort)) %>%
  mutate(Labelfineshort = substr(Labelfineshort, 27, LabelLength-4)) %>%
  select(-LabelLength) %>%
  mutate(x = round(x, digits = 3)) %>%
  spread(., key = x, value = density) %>%
  mutate(Labelfineshort = as.character(Labelfineshort))

skelavebrdensdata <- read.csv("./data-files/skel.dens.avebranch.csv")

skelavebrdensdata <- skelavebrdensdata %>%
  mutate(Labelfineshort = i) %>%
  select(-i) %>%
  mutate(Labelfineshort = as.character(Labelfineshort)) %>%
  mutate(LabelLength = nchar(Labelfineshort)) %>%
  mutate(Labelfineshort = substr(Labelfineshort, 27, LabelLength-4)) %>%
  select(-LabelLength) %>%
  mutate(x = round(x, digits = 3)) %>%
  spread(., key = x, value = density) %>%
  mutate(Labelfineshort = as.character(Labelfineshort))


skelmaxbrdensdata <- read.csv("./data-files/skel.dens.maxbranch.csv")

skelmaxbrdensdata <- skelmaxbrdensdata %>%
  mutate(Labelfineshort = i) %>%
  select(-i) %>%
  mutate(Labelfineshort = as.character(Labelfineshort)) %>%
  mutate(LabelLength = nchar(Labelfineshort)) %>%
  mutate(Labelfineshort = substr(Labelfineshort, 27, LabelLength-4)) %>%
  select(-LabelLength) %>%
  mutate(x = round(x, digits = 3)) %>%
  spread(., key = x, value = density) %>%
  mutate(Labelfineshort = as.character(Labelfineshort))
```


```{r}
#create list of partition files to read

partitionList <- list.files("C:/Users/William/Desktop/distribution_feats_for_William")

```






```{r}
#primary for loop
#reads individual partition files
#uses each partition file to filter each density dataset
#aggregates each density dataset
#writes to individual partition file

#i <- partitionList[1]

for (i in partitionList){
  
  #reads individual partition files
  filename <- paste("C:/Users/William/Desktop/distribution_feats_for_William/",i,sep = "") 
  
  partitionID <- substr(i,11,nchar(i)) %>%
    substr(.,1,nchar(.)-14)
  
  tempfilter <- read.csv(filename) %>%
  mutate(Labelfine = as.character(Labelfine)) %>%
  mutate(Labelfineshort = substr(Labelfine,7,nchar(Labelfine)))
  
  newdata <- data.frame(rownumeric = 1:512)
  #nndfilename <- paste("C:/Users/William/Desktop/AggrDens/partition_",partitionID,"_nnd.csv", sep = "")

  newdata <- nnddensdata %>%
  #filters here
  left_join(tempfilter, ., by = "Labelfine") %>% #uses each partition file to filter each density dataset
  select(-1,-2,-3,-4,-5) %>%
  colSums() %>% #aggregates each density dataset
  as.data.frame() %>%
  rownames_to_column() %>%
  setNames(., c("nndx","nndxAggregateDensity")) %>%
    cbind(newdata, .)
  #write.csv(., file = nndfilename, row.names = F) #writes to individual partition file
  
  
  #vrnfilename <- paste("C:/Users/William/Desktop/AggrDens/partition_",partitionID,"_vrn.csv", sep = "")

  newdata <- vrndensdata %>%
  #filters here
  left_join(tempfilter, ., by = "Labelfineshort") %>%
  select(-1,-2,-3,-4,-5) %>%
  colSums() %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  setNames(., c("vrnx","vrnxAggregateDensity")) %>%
    cbind(newdata, .)
  #write.csv(., file = vrnfilename, row.names = F)
  
  
  #r3dfilename <- paste("C:/Users/William/Desktop/AggrDens/partition_",partitionID,"_r3d.csv", sep = "")

  newdata <- r3densdata %>%
  #filters here
  left_join(tempfilter, ., by = "Labelfine") %>%
  select(-1,-2,-3,-4,-5) %>%
  colSums() %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  setNames(., c("r3x","r3xAggregateDensity")) %>%
    cbind(newdata, .)
  #write.csv(., file = r3dfilename, row.names = F)
  
  
  #brfilename <- paste("C:/Users/William/Desktop/AggrDens/partition_",partitionID,"_br.csv", sep = "")

  newdata <- skelbranchdensdata %>%
  #filters here
  left_join(tempfilter, ., by = "Labelfineshort") %>%
  select(-1,-2,-3,-4,-5) %>%
  colSums() %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  setNames(., c("skel.br.x","brAggregateDensity")) %>%
    cbind(newdata, .)
  #write.csv(., file = brfilename, row.names = F)
  
  #avbrfilename <- paste("C:/Users/William/Desktop/AggrDens/partition_",partitionID,"_avbr.csv", sep = "")

  newdata <- skelavebrdensdata %>%
  #filters here
  left_join(tempfilter, ., by = "Labelfineshort") %>%
  select(-1,-2,-3,-4,-5) %>%
  colSums() %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  setNames(., c("skel.avbr.x","avbrAggregateDensity")) %>%
    cbind(newdata, .)
  #write.csv(., file = avbrfilename, row.names = F)

  #mxbrfilename <- paste("C:/Users/William/Desktop/AggrDens/partition_",partitionID,"_mxbr.csv", sep = "")

  newdata <- skelmaxbrdensdata %>%
  #filters here
  left_join(tempfilter, ., by = "Labelfineshort") %>%
  select(-1,-2,-3,-4,-5) %>%
  colSums() %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  setNames(., c("skel.mxbr.x","mxbrAggregateDensity")) %>%
    cbind(newdata, .)
  #write.csv(., file = mxbrfilename, row.names = F)
  
  newdata <- newdata %>%
    select(-1)
  
  newfilename = paste("C:/Users/William/Desktop/AggrDens/partition_",partitionID,".csv", sep = "")
  write.csv(newdata, file = newfilename, row.names = F)
  
  rm(filename)
  rm(partitionID)
  rm(tempfilter)
  
  rm(nndfilename)
  rm(vrnfilename)
  rm(r3dfilename)
  
  rm(brfilename)
  rm(avbrfilename)
  rm(mxbrfilename)
  
  rm(newdata)
  rm(newfilename)
}
rm(i)
```









