---
title: "gg-voronoi-map"
author: "whh36"
date: "8/17/2020"
output: html_document
---

```{r setup, include=FALSE}
#SETUP OF LIBRARIES
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE) #set echo to FALSE to hide code
```

```{r}
ggvmap <- list.files("./data-files/voronoi-txt-files-10k/", full.names = TRUE)[1] %>%
  read.table(header = FALSE) %>%
  rownames_to_column() %>%
  pivot_longer(., cols = starts_with("v"), names_to = "colx", values_to = "intensz") %>%
  mutate(colx = substr(colx, 2, 6)) %>%
  mutate(colx = as.numeric(colx)) %>%
  mutate(rowname = as.numeric(rowname)) %>%
  mutate(intensz = if_else(intensz != 0, intensz, as.integer(NA))) %>%
  mutate(intensz = intensz*0.052459) %>%
  mutate(colx = colx*8/305) %>%
  mutate(rowname = rowname*8/305) %>%

  ggplot() +
  geom_tile(aes(x = colx, y = rowname, fill = intensz)) +
  geom_rect(xmin = 0, xmax = 10, ymin = -1.5, ymax = -1) +
  update_geom_defaults("rect", list(fill = "#000000")) +
  coord_fixed() +
  xlab("") +
  ylab("") +
  scale_y_continuous(labels = NULL) +
  scale_x_continuous(breaks = c(0,10), labels = c("0", expression(10~'['*mu*m*']'))) +
  scale_fill_gradientn(colours = hue_pal()(8), na.value="black",
                       breaks = c(0,1,2,3,4),
                       labels = c("0","1","2","3","4")) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 12),
        legend.text = element_text(colour="black", size = 11),
        legend.title = element_text(colour="black", size = 12),
        axis.line.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line.x = element_blank(),
        axis.ticks.x = element_blank()) +
  labs(fill = expression(Voronoi~Distance~'['*mu*m*']'))

print(ggvmap)
ggsave(filename = "./plotexports/plotexportggvmap.png", plot = ggvmap, device = "png", width = 8, height = 6, units = "in")
rm(ggvmap)
```
