---
title: "LTO-Ni-ML"
author: "whh36"
date: "8/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(caret)
library(randomForest)
library(e1071)
library(ipred)
library(concaveman)
library(randomForestExplainer)
```

#data splitting

```{r}
#INCLUDE PCA


#bind1 is a modified version of the original machine learning dataset
#properly filtered to match PCA dataset
#
bind1 <- voronoidens %>%
  select(-x, -count, -density, -Labelfineshort) %>%
  select(-magx, -imagearea, -avennd) %>%
  select(-avecountarea,-avevcoarse, -countperarea) %>%
  #select(-Ni.Vol.Corrected) %>%
  select(-stressf, -aveR3) %>%
  #
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  #select(-Label, -Labelfine) %>%
  #
  unique()

#bind2 allows the PCA dataset to be filtered down to Magx = 10 (machine learning doesn't have Magx=5)
bind2 <- df_particles_fine %>%
  select(Labelfine, magx) %>%
  unique()

#bind 3 brings in skeleton data
bind3 <- skeleton.data %>%
  select(ave.branches, ave.ave.branches, ave.max.branches, Labelfine) %>%
  unique()

#add PCA results to bind1
temp <- left_join(prcomp.R3.Results, bind2, by = "Labelfine") %>%
  filter(magx == 10) %>%
  select(1:7) %>%
  left_join(., bind1, by = "Labelfine") %>%
  left_join(., bind3, by = "Labelfine") %>%
  select(-Label, -Labelfine) %>%
  mutate(condAve = log(condAve)) %>%
  filter(is.na(condAve) == FALSE)




rm(bind1)
rm(bind2)
rm(bind3)
```


```{r}
#originial machine learning dataset (see above for PCA added)
# temp <- voronoidens %>%
#   select(-x, -count, -Labelfineshort) %>%
#   select(-magx, -imagearea, -avennd) %>%
#   select(-avecountarea,-avevcoarse, -countperarea) %>%
#   #select(-Ni.Vol.Corrected) %>%
#   select(-stressf, -aveR3) %>%
#   select(-Label, -Labelfine) %>%
#   unique() %>%
#   mutate(condAve = log(condAve)) %>%
#   filter(is.na(condAve) == FALSE)

tempscaled <- as.data.frame(scale(temp))

#split into testing and training
split <- createDataPartition(temp$condAve, p = 0.7, times = 4)

trainset <- temp[as.vector(split[[1]]),]
testset <- temp[-as.vector(split[[1]]),]

#scale features
trainset <- as.data.frame(scale(trainset))
testset <- as.data.frame(scale(testset))

#move condAve to last column
trainset <- select(trainset,c(names(select(trainset, -condAve)), "condAve"))
testset <- select(testset,c(names(select(testset, -condAve)), "condAve"))


#summary(temp)
summary(trainset)
#summary(testset)
#rm(temp)
rm(split)

```


#models

```{r}

rfmodel <- trainset %>%
  select(-Dim.1,-Dim.2,-Dim.3,-Dim.4,-Dim.5,-Dim.6) %>%
  select(-Temp, -hrs) %>%
  select(-Ni.Vol.Corrected) %>%
  randomForest(x = ., y = trainset$condAve, ntree = 300)

#remove Ni.Vol.Corrected from RF model

conrferr <- plot(rfmodel, main = paste("Conductivity RF -", 
                        round(sqrt(last(rfmodel$mse)),2),
                        "RMSE"))

conrferrplot <- ggplot() +
  geom_line(size = 1, aes(x = 1:300, y = conrferr)) +
  labs(title = paste("Conductivity RF - ", 
                        round(sqrt(last(rfmodel$mse)),2),
                        " RMSE", sep = "")) +
  xlab("Trees") +
  ylab("Error") +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        plot.title = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))


print(conrferrplot)
ggsave(filename = "./MLexports/conrferrplot.png", plot = conrferrplot, 
         device = "png", width = 6,height = 4, units = "in")
rm(conrferr)
rm(conrferrplot)

#print(rfmodel)
```

```{r}
rfmodimp <- importance(rfmodel) %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(IncNodePurity) %>%
  filter(rowname != "condAve")

importance(rfmodel) %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(desc(IncNodePurity))
```

```{r}
rfmodimp.verb <- rfmodimp %>%
  mutate(variable = rowname) %>%
  select(-rowname) %>%
  mutate(variable = if_else(variable == "ave.ave.branches", "Average Branch Length", variable)) %>%
  mutate(variable = if_else(variable == "ave.max.branches", "Maximum Branch Length", variable)) %>%
  mutate(variable = if_else(variable == "ave.branches", "Average Number of Branches", variable)) %>%
  mutate(variable = if_else(variable == "aveAreafine", "Average Particle Area", variable)) %>%
  mutate(variable = if_else(variable == "avevoronoix", "Average Edge-to-Edge Spacing", variable)) %>%
  mutate(variable = if_else(variable == "fineavennd", "Average Center-to-Center Spacing", variable)) %>%
  mutate(variable = if_else(variable == "finecount", "Counts Per Area", variable)) %>%
  mutate(variable = if_else(variable == "hrs", "Dwell Time", variable)) %>%
  mutate(variable = if_else(variable == "Temp", "Sintering Temperature", variable)) %>%
  mutate(variable = if_else(variable == "Th.Density", "Bulk Density", variable)) %>%
  mutate(variable = if_else(variable == "totNifrace", "Nickel Area Fraction", variable)) %>%
  mutate(variable = if_else(variable == "voronoicount", "Edge-to-Edge Complexity", variable)) %>%
  mutate(variable = if_else(variable == "Dim.1", "Size-PC-1", variable)) %>%
  mutate(variable = if_else(variable == "Dim.2", "Size-PC-2", variable)) %>%
  mutate(variable = if_else(variable == "Dim.3", "Size-PC-3", variable)) %>%
  mutate(variable = if_else(variable == "Dim.4", "Size-PC-4", variable)) %>%
  mutate(variable = if_else(variable == "Dim.5", "Size-PC-5", variable)) %>%
  mutate(variable = if_else(variable == "Dim.6", "Size-PC-6", variable))

ggplot() +
  geom_point(data = rfmodimp.verb, aes(x = variable, y = -IncNodePurity*10))



# conrfnode <- dotchart(rfmodimp.verb$IncNodePurity, labels = rfmodimp.verb$variable, main = "Conductivity RF")
# 
# print(conrfnode)
# ggsave(filename = "./MLexports/conrfnode.png", plot = conrfnode, 
#          device = "png", width = 6,height = 4, units = "in")
# rm(conrfnode)
png("./MLexports/conrfnode.png")
print(dotchart(rfmodimp.verb$IncNodePurity, labels = rfmodimp.verb$variable, main = "Conductivity RF"))
dev.off()


#somehow combine node purity and depth information?
```


```{r}
rfresults <- predict(rfmodel, testset) %>%
  as.data.frame() %>%
  cbind(as.data.frame(testset$condAve))

colnames(rfresults)[1] <- "prediction"
colnames(rfresults)[2] <- "actual"



rflm <- lm(rfresults$prediction ~ rfresults$actual)

paste(round(summary(rflm)$r.squared,3), "R^2")

paste(round(summary(rflm)$adj.r.squared,3), "Adj. R^2")
```

```{r}
#plot of testing predicted vs measured
tempPAL <- scico(8, palette = "roma", direction = 1)
lim1 <- -1.5
lim2 <-  2.25

VALUETEMP <- paste(round(summary(rflm)$adj.r.squared,3)," ~ Adj. ~ R^2",sep = "")

conrfpredmeas <- cbind(rfresults, testset) %>%
  ggplot() +
  geom_point(aes(y = prediction, x = condAve, color = as.factor(Ni.Vol.Corrected))) +
  geom_abline(slope = 1, intercept = 0) +
  #guides(color = FALSE) +
  scale_color_manual(values = tempPAL, labels = c(0.05,0.10,0.20,0.24,0.28,0.35,0.40,0.50)) +
  theme_classic() +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  coord_fixed(ratio = 1, xlim = c(lim1,lim2), ylim = c(lim1,lim2)) +
  xlab("Scaled Conductivity") +
  ylab("Conductivity Predicted") +
  guides(colour = guide_legend(reverse = TRUE, title = "Ni Vol.", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10))) +
  geom_abline(slope = rflm$coefficients[2], 
              intercept = rflm$coefficients[1],
              color = "red",linetype = "dashed") +
  annotate("text", label = VALUETEMP, parse = T,
           x = 1, 
           y = -1)

print(conrfpredmeas)
ggsave(filename = "./MLexports/conrfpredmeas.png", plot = conrfpredmeas, 
         device = "png", width = 6,height = 4, units = "in")
rm(conrfpredmeas)

```

```{r}
#plot of training predicted vs measured
rfresults.training <- predict(rfmodel, trainset) %>%
  as.data.frame() %>%
  cbind(as.data.frame(trainset$condAve))

colnames(rfresults.training)[1] <- "prediction"
colnames(rfresults.training)[2] <- "actual"



rflm.training <- lm(rfresults.training$prediction ~ rfresults.training$actual)

paste(round(summary(rflm.training)$r.squared,3), "R^2")

paste(round(summary(rflm.training)$adj.r.squared,3), "Adj. R^2")

#
#
#

tempPAL <- scico(8, palette = "roma", direction = 1)
lim1 <- -1.5
lim2 <-  2.25

VALUETEMP <- paste(round(summary(rflm.training)$adj.r.squared,3)," ~ Adj. ~ R^2",sep = "")

conrfpredmeas.training <- cbind(rfresults.training, trainset) %>%
  ggplot() +
  geom_point(aes(y = prediction, x = condAve, color = as.factor(Ni.Vol.Corrected))) +
  geom_abline(slope = 1, intercept = 0) +
  #guides(color = FALSE) +
  scale_color_manual(values = tempPAL, labels = c(0.05,0.10,0.20,0.24,0.28,0.35,0.40,0.50)) +
  theme_classic() +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  coord_fixed(ratio = 1, xlim = c(lim1,lim2), ylim = c(lim1,lim2)) +
  xlab("Scaled Conductivity") +
  ylab("Conductivity Predicted") +
  guides(colour = guide_legend(reverse = TRUE, title = "Ni Vol.", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10))) +
  geom_abline(slope = rflm.training$coefficients[2], 
              intercept = rflm.training$coefficients[1],
              color = "red",linetype = "dashed") +
  annotate("text", label = VALUETEMP, parse = T,
           x = 1, 
           y = -1)

print(conrfpredmeas.training)
ggsave(filename = "./MLexports/conrfpredmeastrain.png", plot = conrfpredmeas.training, 
         device = "png", width = 6,height = 4, units = "in")
rm(conrfpredmeas.training)


```



```{r}
rfmodel.min.depth.df <- min_depth_distribution(rfmodel)

rfmodel.min.depth.df <- rfmodel.min.depth.df %>%
  filter(variable != "condAve") %>%
  mutate(variable = if_else(variable == "ave.ave.branches", "Average Branch Length", variable)) %>%
  mutate(variable = if_else(variable == "ave.max.branches", "Maximum Branch Length", variable)) %>%
  mutate(variable = if_else(variable == "ave.branches", "Average Number of Branches", variable)) %>%
  mutate(variable = if_else(variable == "aveAreafine", "Average Particle Area", variable)) %>%
  mutate(variable = if_else(variable == "avevoronoix", "Average Edge-to-Edge Spacing", variable)) %>%
  mutate(variable = if_else(variable == "fineavennd", "Average Center-to-Center Spacing", variable)) %>%
  mutate(variable = if_else(variable == "finecount", "Counts Per Area", variable)) %>%
  mutate(variable = if_else(variable == "hrs", "Dwell Time", variable)) %>%
  mutate(variable = if_else(variable == "Temp", "Sintering Temperature", variable)) %>%
  mutate(variable = if_else(variable == "Th.Density", "Bulk Density", variable)) %>%
  mutate(variable = if_else(variable == "totNifrace", "Nickel Area Fraction", variable)) %>%
  mutate(variable = if_else(variable == "voronoicount", "Edge-to-Edge Complexity", variable)) %>%
  mutate(variable = if_else(variable == "Dim.1", "Size-PC-1", variable)) %>%
  mutate(variable = if_else(variable == "Dim.2", "Size-PC-2", variable)) %>%
  mutate(variable = if_else(variable == "Dim.3", "Size-PC-3", variable)) %>%
  mutate(variable = if_else(variable == "Dim.4", "Size-PC-4", variable)) %>%
  mutate(variable = if_else(variable == "Dim.5", "Size-PC-5", variable)) %>%
  mutate(variable = if_else(variable == "Dim.6", "Size-PC-6", variable))

conrfmindepth <- plot_min_depth_distribution(rfmodel.min.depth.df, k = 30) +
  xlab("") +
  {if(cb == 1)scale_fill_scico_d(na.translate = FALSE, palette = "nuuk", direction = 1, begin = 0, end = 1)}

print(conrfmindepth)
ggsave(filename = "./MLexports/conrfmindepth.png", plot = conrfmindepth, 
         device = "png", width = 7.29,height = 4.5, units = "in")
rm(conrfmindepth)
```


<!--
```{r}
#Random forest using just PCA data to predict conductivity

trainset %>%
  select(hrs) %>%
  unique()

trainset.pcs <- trainset %>%
  filter(hrs < 1) %>%
  select(., Dim.1,Dim.2,Dim.3,Dim.4,Dim.5,Dim.6, condAve)

testset.pcs <- testset %>%
  filter(hrs < 1) %>%
  select(., Dim.1,Dim.2,Dim.3,Dim.4,Dim.5,Dim.6, condAve)


rf.pcs <- randomForest(x = trainset.pcs, y = trainset.pcs$condAve, ntree = 300)

#remove Ni.Vol.Corrected from RF model

plot(rf.pcs, main = paste("Conductivity Random Forest - PCA only -", 
                        round(last(rf.pcs$rsq)*100,2),
                        "% Var Explained"
                        )
     )
#print(rfmodel)

rfmodimp.pcs <- importance(rf.pcs) %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(IncNodePurity) %>%
  filter(rowname != "condAve")

dotchart(rfmodimp.pcs$IncNodePurity, labels = rfmodimp.pcs$rowname, main = "Conductivity RF")

importance(rf.pcs) %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(desc(IncNodePurity))

rfresults.pcs <- predict(rf.pcs, testset.pcs) %>%
  as.data.frame() %>%
  cbind(as.data.frame(testset.pcs$condAve))

colnames(rfresults.pcs)[1] <- "prediction"
colnames(rfresults.pcs)[2] <- "actual"

testset %>%
  filter(hrs < 1) %>%
cbind(rfresults.pcs, .) %>%
  ggplot() +
  geom_point(aes(y = prediction, x = condAve, color = as.factor(Ni.Vol.Corrected))) +
  geom_abline(slope = 1, intercept = 0) +
  guides(color = FALSE) +
  theme_classic() +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  coord_fixed() +
  xlab("Conductivity [S/cm]") +
  ylab("Conductivity Predicted [S/cm]")
  #annotate("text", label = round(last(rfmodel$rsq)*100,2), x = mean(rfresults$actual), y = mean(rfresults$prediction)*2)

rflm.pcs <- lm(rfresults.pcs$prediction ~ rfresults.pcs$actual)

paste(round(summary(rflm.pcs)$r.squared,3), "R^2")

paste(round(summary(rflm.pcs)$adj.r.squared,3), "Adj. R^2")
```

```{r}
#Random forest using just microstructure data to predict conductivity
#no size or processing info




trainset.u <- select(trainset, -Dim.1,-Dim.2,-Dim.3,-Dim.4,-Dim.5,-Dim.6, -aveAreafine,
       -totNifrace,
       -Ni.Vol.Corrected, -Temp, -hrs,
       -Th.Density)

testset.u <- select(testset, -Dim.1,-Dim.2,-Dim.3,-Dim.4,-Dim.5,-Dim.6, -aveAreafine,
       -totNifrace,
       -Ni.Vol.Corrected, -Temp, -hrs,
       -Th.Density)


rf.u <- randomForest(x = trainset.u, y = trainset.u$condAve, ntree = 300)

#remove Ni.Vol.Corrected from RF model

plot(rf.u, main = paste("Conductivity Random Forest - microstructure only -", 
                        round(last(rf.u$rsq)*100,2),
                        "% Var Explained"
                        )
     )
#print(rfmodel)

rfmodimp.u <- importance(rf.u) %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(IncNodePurity) %>%
  filter(rowname != "condAve")

dotchart(rfmodimp.u$IncNodePurity, labels = rfmodimp.u$rowname, main = "Conductivity RF")

importance(rf.u) %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(desc(IncNodePurity))

rfresults.u <- predict(rf.u, testset.u) %>%
  as.data.frame() %>%
  cbind(as.data.frame(testset.u$condAve))

colnames(rfresults.u)[1] <- "prediction"
colnames(rfresults.u)[2] <- "actual"


cbind(rfresults.u, testset) %>%
  ggplot() +
  geom_point(aes(y = prediction, x = condAve, color = as.factor(Ni.Vol.Corrected))) +
  geom_abline(slope = 1, intercept = 0) +
  guides(color = FALSE) +
  theme_classic() +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  coord_fixed() +
  xlab("Conductivity [S/cm]") +
  ylab("Conductivity Predicted [S/cm]")
  #annotate("text", label = round(last(rfmodel$rsq)*100,2), x = mean(rfresults$actual), y = mean(rfresults$prediction)*2)

rflm.u <- lm(rfresults.u$prediction ~ rfresults.u$actual)

paste(round(summary(rflm.u)$r.squared,3), "R^2")

paste(round(summary(rflm.u)$adj.r.squared,3), "Adj. R^2")

```



```{r}
#old SVM code

svmctrl <- trainControl(method = "repeatedcv",
             number = 10,
             repeats = 10)

consvm <- train(condAve ~ ., data = trainset, 
                method = "svmLinear",
                trControl = svmctrl)

svmresults <- predict(consvm, testset) %>%
  as.data.frame()

colnames(svmresults)[1] <- "prediction"

cbind(svmresults, testset) %>%
  ggplot() +
  geom_point(aes(y = prediction, x = condAve, color = as.factor(Ni.Vol.Corrected))) +
  geom_abline(slope = 1, intercept = 0) +
  guides(color = FALSE) +
  theme_classic() +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  #coord_fixed() +
  xlab("Conductivity [S/cm]") +
  ylab("Conductivity Predicted [S/cm]")
  #annotate("text", label = round(summary(svmlm)$r.squared,3), x = mean(testset$condAve), y = mean(svmresults$prediction)*2)

consvmimp <- varImp(consvm)[1] %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(Overall)


svmvarex <- consvm$results %>%
  select(Rsquared) %>%
  slice(which.max(Rsquared)) %>%
  as.numeric() %>%
  round(3)


dotchart(consvmimp$Overall, labels = consvmimp$rowname, 
         main = paste("Conductivity (SVM-Linear rpt-CV)",
                      svmvarex*100,
                      "% Var Explained")
         )

varImp(consvm)[1] %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(desc(Overall))

svmlm <- lm(svmresults$prediction ~ testset$condAve)

paste(round(summary(svmlm)$r.squared,3)*100, "R^2")

paste(round(summary(svmlm)$adj.r.squared,3)*100, "Adj. R^2")

print(consvm)
```
-->

<!--

```{r}
svmctrl <- trainControl(method = "LOOCV", #repeatedcv vs Leave one out cross validation
             #number = 10,
             #repeats = 10,
             #p = 0.7,
             #sampling = "up",
             )
             

consvm <- train(condAve ~ ., data = select(trainset, -Ni.Vol.Corrected), 
                method = "svmPoly", #svmLinear is worse
                trControl = svmctrl)

consvmresults <- predict(consvm, testset) %>%
  as.data.frame()

colnames(consvmresults)[1] <- "prediction"





consvmimp <- varImp(consvm)[1] %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(Overall)

consvmvarex <- consvm$results %>%
  select(RMSE) %>%
  slice(which.min(RMSE)) %>%
  as.numeric() %>%
  round(2)



consvmimp.verb <- consvmimp %>%
  mutate(variable = rowname) %>%
  select(-rowname) %>%
  mutate(variable = if_else(variable == "ave.ave.branches", "Average Branch Length", variable)) %>%
  mutate(variable = if_else(variable == "ave.max.branches", "Maximum Branch Length", variable)) %>%
  mutate(variable = if_else(variable == "ave.branches", "Average Number of Branches", variable)) %>%
  mutate(variable = if_else(variable == "aveAreafine", "Average Particle Area", variable)) %>%
  mutate(variable = if_else(variable == "avevoronoix", "Average Voronoi Spacing", variable)) %>%
  mutate(variable = if_else(variable == "fineavennd", "Average NND", variable)) %>%
  mutate(variable = if_else(variable == "finecount", "Counts Per Area", variable)) %>%
  mutate(variable = if_else(variable == "hrs", "Dwell Time", variable)) %>%
  mutate(variable = if_else(variable == "Temp", "Sintering Temperature", variable)) %>%
  mutate(variable = if_else(variable == "Th.Density", "Bulk Density", variable)) %>%
  mutate(variable = if_else(variable == "totNifrace", "Nickel Area Fraction", variable)) %>%
  mutate(variable = if_else(variable == "voronoicount", "Voronoi Map Coverage", variable)) %>%
  mutate(variable = if_else(variable == "Dim.1", "Size-PC-1", variable)) %>%
  mutate(variable = if_else(variable == "Dim.2", "Size-PC-2", variable)) %>%
  mutate(variable = if_else(variable == "Dim.3", "Size-PC-3", variable)) %>%
  mutate(variable = if_else(variable == "Dim.4", "Size-PC-4", variable)) %>%
  mutate(variable = if_else(variable == "Dim.5", "Size-PC-5", variable)) %>%
  mutate(variable = if_else(variable == "Dim.6", "Size-PC-6", variable))


# consvmvar <- dotchart(consvmimp.verb$Overall, labels = consvmimp.verb$variable, main = paste("Conductivity (SVM-Poly.)",
#                       consvmvarex*100,
#                       "% Var Explained"))
# print(consvmvar)
# ggsave(filename = "./MLexports/consvmvar.png", plot = consvmvar, 
#          device = "png", width = 6,height = 4, units = "in")
# rm(consvmvar)
png("./MLexports/consvmvar.png")
print(dotchart(consvmimp.verb$Overall, xlab = "Importance", labels = consvmimp.verb$variable, main = paste("Conductivity SVM -",
                                                                                      consvmvarex,
                                                                                      "RMSE")))
dev.off()



varImp(consvm)[1] %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(desc(Overall))


consvmlm <- lm(consvmresults$prediction ~ testset$condAve)

paste(round(summary(consvmlm)$r.squared,3)*100, "R^2")

paste(round(summary(consvmlm)$adj.r.squared,3)*100, "Adj. R^2")

print(consvm)
#to try: ensemble SVM / cross validate across different test/train splits
#

consvmpredmeas <- cbind(consvmresults, testset) %>%
  ggplot() +
  geom_point(aes(y = prediction, x = condAve, color = as.factor(Ni.Vol.Corrected))) +
  geom_abline(slope = 1, intercept = 0) +
  guides(color = FALSE) +
  theme_classic() +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  coord_fixed() +
  xlab("Scaled Conductivity") +
  ylab("Conductivity Predicted") +
  geom_abline(slope = consvmlm$coefficients[2], 
              intercept = consvmlm$coefficients[1],
              color = "red",linetype = "dashed") +
  annotate("text", label = paste(round(summary(consvmlm)$adj.r.squared,3), "Adj. R^2"), 
           x = 1, 
           y = -1)


print(consvmpredmeas)
ggsave(filename = "./MLexports/consvmpredmeas.png", plot = consvmpredmeas, 
         device = "png", width = 6,height = 4, units = "in")
rm(consvmpredmeas)
```

-->

<!--
```{r}
#not scaled
condbag <- bagging(condAve ~., data = temp, nbagg = 25)


bagpred <- predict(condbag, temp) %>%
  as.data.frame()

colnames(bagpred)[1] <- "prediction"

cbind(bagpred, temp) %>%
  ggplot() +
  geom_point(aes(y = prediction, x = condAve, color = as.factor(Ni.Vol.Corrected))) +
  geom_abline(slope = 1, intercept = 0) +
  coord_fixed() +
  guides(color = FALSE)
```
-->


<!--
```{r}
#use scaled dataframe?

tbctrl <- trainControl(method = "repeatedcv",
             number = 10,
             #classProbs = TRUE,
             #sampling = "down",
             #summaryFunction = defaultSummary,
             repeats = 10)


bagCtrl <- bagControl(fit = ctreeBag$fit,
                      predict = ctreeBag$pred,
                      aggregate = ctreeBag$aggregate)


treebagresults2 <- bag(condAve~., data = trainset, bagControl = bagCtrl)

treebagpred2 <- predict(treebagresults2, testset) %>%
  as.data.frame()

colnames(treebagpred2)[1] <- "prediction"

cbind(treebagpred2, temp) %>%
  ggplot() +
  geom_point(aes(y = prediction, x = condAve, color = as.factor(Ni.Vol.Corrected))) +
  geom_abline(slope = 1, intercept = 0) +
  coord_fixed() +
  guides(color = FALSE)

treebagimp2 <- varImp(treebagresults2)[1] %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(Overall)

dotchart(treebagimp2$Overall, labels = treebagimp2$rowname, main = "treebag")

varImp(treebagresults2)[1] %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(desc(Overall))
```
-->

<!--
```{r}
tbctrl <- trainControl(method = "repeatedcv",
             number = 10,
             #classProbs = TRUE,
             #sampling = "down",
             #summaryFunction = defaultSummary,
             repeats = 10)

treebagresults <- train(condAve~., data = temp, method = "treebag", trControl = tbctrl)

treebagpred <- predict(treebagresults, temp) %>%
  as.data.frame()

colnames(treebagpred)[1] <- "prediction"

cbind(treebagpred, temp) %>%
  ggplot() +
  geom_point(aes(y = prediction, x = condAve, color = as.factor(Ni.Vol.Corrected))) +
  geom_abline(slope = 1, intercept = 0) +
  coord_fixed() +
  guides(color = FALSE)

treebagimp <- varImp(treebagresults)[1] %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(Overall)

dotchart(treebagimp$Overall, labels = treebagimp$rowname, main = "treebag")

varImp(treebagresults)[1] %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(desc(Overall))

```
-->


<!--
```{r}
#svmBag using Caret
#nnetBag too

svmbagctrl <- trainControl(method = "cv",
             number = 10,
             selectionFunction = oneSE)
             #classProbs = TRUE,
             #sampling = "down",
             #summaryFunction = defaultSummary,
             #repeats = 10)



#str(svmBag)
#svmBag$fit

bagctrl <- bagControl(fit = svmBag$fit,
                      predict = svmBag$pred,
                      aggregate = svmBag$aggregate)


#set.seed(300)
svmsack <- train(condAve ~ ., data = tempscaled, "bag",
                 trControl = svmbagctrl, bagControl = bagctrl)

svmsack


```
-->




#stress modeling

```{r}
bind1 <- voronoidens %>%
  select(-x, -count, -density, -Labelfineshort) %>%
  select(-magx, -imagearea, -avennd) %>%
  select(-avecountarea,-avevcoarse, -countperarea) %>%
  #select(-Ni.Vol.Corrected) %>%
  select(-condAve, -aveR3) %>%
  #
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  #select(-Label, -Labelfine) %>%
  #
  unique()

#bind2 allows the PCA dataset to be filtered down to Magx = 10 (machine learning doesn't have Magx=5)
bind2 <- df_particles_fine %>%
  select(Labelfine, magx) %>%
  unique()

#bind 3 brings in skeleton data
bind3 <- skeleton.data %>%
  select(ave.branches, ave.ave.branches, ave.max.branches, Labelfine) %>%
  unique()

#add PCA results to bind1
temp2 <- left_join(prcomp.R3.Results, bind2, by = "Labelfine") %>%
  filter(magx == 10) %>%
  select(1:7) %>%
  left_join(., bind1, by = "Labelfine") %>%
  left_join(., bind3, by = "Labelfine") %>%
  select(-Label, -Labelfine) %>%
  mutate(stressf2 = stressf) %>%
  select(-stressf) %>%
  filter(is.na(stressf2) == FALSE)

rm(bind1)
rm(bind2)

# temp2 <- voronoidens %>%
#   select(-x, -count, -Labelfineshort) %>%
#   select(-magx, -imagearea, -avennd) %>%
#   select(-avecountarea,-avevcoarse, -countperarea) %>%
#   #select(-Ni.Vol.Corrected) %>%
#   select(-condAve, -aveR3) %>%
#   select(-Label, -Labelfine) %>%
#   unique() %>%
#   mutate(stressf2 = stressf) %>%
#   select(-stressf) %>%
#   filter(is.na(stressf2) == FALSE)

tempscaled2 <- as.data.frame(scale(temp2))

#split into testing and training
split <- createDataPartition(temp2$stressf, p = 0.7, times = 4)

trainset2 <- temp2[as.vector(split[[1]]),]
testset2 <- temp2[-as.vector(split[[1]]),]

#scale features
trainset2 <- as.data.frame(scale(trainset2))
testset2 <- as.data.frame(scale(testset2))
```


```{r}
rfmodels <- trainset2 %>%
  select(-Dim.1,-Dim.2,-Dim.3,-Dim.4,-Dim.5,-Dim.6,) %>%
  select(-Temp, -hrs, -Ni.Vol.Corrected) %>%
  randomForest(x = ., y = trainset2$stressf, ntree = 300)

#remove Ni.Vol.Corrected from RF model

stressrferr <- plot(rfmodels, main = paste("Stress RF -", 
                        round(sqrt(last(rfmodels$mse)),2),
                        " RMSE"))

stressrferrplot <- ggplot() +
  geom_line(size = 1, aes(x = 1:300, y = stressrferr)) +
  labs(title = paste("Stress RF - ", 
                        round(sqrt(last(rfmodels$mse)),2),
                        " RMSE", sep = "")) +
  xlab("Trees") +
  ylab("Error") +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        plot.title = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(stressrferrplot)
ggsave(filename = "./MLexports/stressrferrplot.png", plot = stressrferrplot, 
         device = "png", width = 6,height = 4, units = "in")
rm(stressrferr)
rm(stressrferrplot)
#print(rfmodels)
```

```{r}
rfmodimps <- importance(rfmodels) %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(IncNodePurity) %>%
  filter(rowname != "stressf2")

importance(rfmodels) %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(desc(IncNodePurity))
```

```{r}
rfresultss <- predict(rfmodels, testset2) %>%
  as.data.frame() %>%
  cbind(as.data.frame(testset2$stressf))

colnames(rfresultss)[1] <- "prediction"
colnames(rfresultss)[2] <- "actual"

#rflms <- lm(rfresultss$prediction ~ rfresultss$actual)
#round(summary(rflms)$r.squared,3)



stress.rf.lm <- lm(rfresultss$prediction ~ rfresultss$actual)

paste(round(summary(stress.rf.lm)$r.squared,3)*100, "R^2")

paste(round(summary(stress.rf.lm)$adj.r.squared,3)*100, "Adj. R^2")


stressrfpredmeas <- cbind(rfresultss, testset2) %>%
  ggplot() +
  geom_point(aes(y = prediction, x = stressf2, color = as.factor(Ni.Vol.Corrected))) +
  geom_abline(slope = 1, intercept = 0) +
  guides(color = FALSE) +
  theme_classic() +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  coord_fixed() +
  xlab(expression(Scaled~sigma[fr])) +
  ylab(expression(sigma[fr]~'-'~predicted)) +
  geom_abline(slope = stress.rf.lm$coefficients[2], 
              intercept = stress.rf.lm$coefficients[1],
              color = "red",linetype = "dashed") +
  annotate("text", label = paste(round(summary(stress.rf.lm)$adj.r.squared,3), "Adj. R^2"), 
           x = 1, 
           y = -1)

print(stressrfpredmeas)
ggsave(filename = "./MLexports/stressrfpredmeas.png", plot = stressrfpredmeas, 
         device = "png", width = 6,height = 4, units = "in")
rm(stressrfpredmeas)
```

```{r}
rfmodimps.verb <- rfmodimps %>%
  mutate(variable = rowname) %>%
  select(-rowname) %>%
  mutate(variable = if_else(variable == "ave.ave.branches", "Average Branch Length", variable)) %>%
  mutate(variable = if_else(variable == "ave.max.branches", "Maximum Branch Length", variable)) %>%
  mutate(variable = if_else(variable == "ave.branches", "Average Number of Branches", variable)) %>%
  mutate(variable = if_else(variable == "aveAreafine", "Average Particle Area", variable)) %>%
  mutate(variable = if_else(variable == "avevoronoix", "Average Edge-to-Edge Spacing", variable)) %>%
  mutate(variable = if_else(variable == "fineavennd", "Average Center-to-Center Spacing", variable)) %>%
  mutate(variable = if_else(variable == "finecount", "Counts Per Area", variable)) %>%
  mutate(variable = if_else(variable == "hrs", "Dwell Time", variable)) %>%
  mutate(variable = if_else(variable == "Temp", "Sintering Temperature", variable)) %>%
  mutate(variable = if_else(variable == "Th.Density", "Bulk Density", variable)) %>%
  mutate(variable = if_else(variable == "totNifrace", "Nickel Area Fraction", variable)) %>%
  mutate(variable = if_else(variable == "voronoicount", "Edge-to-Edge Complexity", variable)) %>%
  mutate(variable = if_else(variable == "Dim.1", "Size-PC-1", variable)) %>%
  mutate(variable = if_else(variable == "Dim.2", "Size-PC-2", variable)) %>%
  mutate(variable = if_else(variable == "Dim.3", "Size-PC-3", variable)) %>%
  mutate(variable = if_else(variable == "Dim.4", "Size-PC-4", variable)) %>%
  mutate(variable = if_else(variable == "Dim.5", "Size-PC-5", variable)) %>%
  mutate(variable = if_else(variable == "Dim.6", "Size-PC-6", variable))

ggplot() +
  geom_point(data = rfmodimps.verb, aes(x = variable, y = -IncNodePurity*10))

# stressrfnode <- dotchart(rfmodimps.verb$IncNodePurity, labels = rfmodimps.verb$variable, main = "Stress RF")
# 
# print(stressrfnode)
# ggsave(filename = "./MLexports/stressrfnode.png", plot = stressrfnode, 
#          device = "png", width = 6,height = 4, units = "in")
# rm(stressrfnode)
png("./MLexports/stressrfnode.png")
print(dotchart(rfmodimps.verb$IncNodePurity, labels = rfmodimps.verb$variable, main = "Stress RF"))
dev.off()

#somehow combine node purity and depth information?
```


```{r}
rfmodels.min.depth.df <- min_depth_distribution(rfmodels)
```

```{r}
rfmodels.min.depth.df <- rfmodels.min.depth.df %>%
  filter(variable != "stressf2") %>%
  mutate(variable = if_else(variable == "ave.ave.branches", "Average Branch Length", variable)) %>%
  mutate(variable = if_else(variable == "ave.max.branches", "Maximum Branch Length", variable)) %>%
  mutate(variable = if_else(variable == "ave.branches", "Average Number of Branches", variable)) %>%
  mutate(variable = if_else(variable == "aveAreafine", "Average Particle Area", variable)) %>%
  mutate(variable = if_else(variable == "avevoronoix", "Average Edge-to-Edge Spacing", variable)) %>%
  mutate(variable = if_else(variable == "fineavennd", "Average Center-to-Center Spacing", variable)) %>%
  mutate(variable = if_else(variable == "finecount", "Counts Per Area", variable)) %>%
  mutate(variable = if_else(variable == "hrs", "Dwell Time", variable)) %>%
  mutate(variable = if_else(variable == "Temp", "Sintering Temperature", variable)) %>%
  mutate(variable = if_else(variable == "Th.Density", "Bulk Density", variable)) %>%
  mutate(variable = if_else(variable == "totNifrace", "Nickel Area Fraction", variable)) %>%
  mutate(variable = if_else(variable == "voronoicount", "Edge-to-Edge Complexity", variable)) %>%
  mutate(variable = if_else(variable == "Dim.1", "Size-PC-1", variable)) %>%
  mutate(variable = if_else(variable == "Dim.2", "Size-PC-2", variable)) %>%
  mutate(variable = if_else(variable == "Dim.3", "Size-PC-3", variable)) %>%
  mutate(variable = if_else(variable == "Dim.4", "Size-PC-4", variable)) %>%
  mutate(variable = if_else(variable == "Dim.5", "Size-PC-5", variable)) %>%
  mutate(variable = if_else(variable == "Dim.6", "Size-PC-6", variable))
  
stressrfmindepth <- plot_min_depth_distribution(rfmodels.min.depth.df, k = 30) +
  xlab("") +
  {if(cb == 1)scale_fill_scico_d(na.translate = FALSE, palette = "nuuk", direction = 1, begin = 0, end = 1)} #+
  #geom_col(data = rfmodimps.verb, aes(x = variable, y = IncNodePurity))


print(stressrfmindepth)
ggsave(filename = "./MLexports/stressrfmindepth.png", plot = stressrfmindepth, 
         device = "png", width = 7.29,height = 4.5, units = "in")
rm(stressrfmindepth)

# measure_importance(rfmodels) %>%
#   plot_importance_ggpairs()
```


<!--
```{r}
#Random forest using just PCA data to predict stress

trainset.pcs.stressf2 <- select(trainset2, 1:6, stressf2)

testset.pcs.stressf2 <- select(testset2, 1:6, stressf2)


rf.pcs.stressf2 <- randomForest(x = trainset.pcs.stressf2, y = trainset.pcs.stressf2$stressf2, ntree = 300)

#remove Ni.Vol.Corrected from RF model

plot(rf.pcs.stressf2, main = paste("Stress Random Forest - PCA only -", 
                        round(last(rf.pcs.stressf2$rsq)*100,2),
                        "% Var Explained"
                        )
     )
#print(rfmodel)

rfmodimp.pcs.stressf2 <- importance(rf.pcs.stressf2) %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(IncNodePurity) %>%
  filter(rowname != "stressf2")

dotchart(rfmodimp.pcs.stressf2$IncNodePurity, labels = rfmodimp.pcs.stressf2$rowname, main = "Conductivity RF")

importance(rf.pcs.stressf2) %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(desc(IncNodePurity))

rfresults.pcs.stressf2 <- predict(rf.pcs.stressf2, testset.pcs.stressf2) %>%
  as.data.frame() %>%
  cbind(as.data.frame(testset.pcs.stressf2$stressf2))

colnames(rfresults.pcs.stressf2)[1] <- "prediction"
colnames(rfresults.pcs.stressf2)[2] <- "actual"


cbind(rfresults.pcs.stressf2, testset2) %>%
  ggplot() +
  geom_point(aes(y = prediction, x = stressf2, color = as.factor(Ni.Vol.Corrected))) +
  geom_abline(slope = 1, intercept = 0) +
  guides(color = FALSE) +
  theme_classic() +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  coord_fixed() +
  xlab(expression(sigma[fr]~'['*MPa*']')) +
  ylab(expression(sigma[fr]~'-'~predicted~'['*MPa*']'))

rflm.pcs.stressf2 <- lm(rfresults.pcs.stressf2$prediction ~ rfresults.pcs.stressf2$actual)

paste(round(summary(rflm.pcs.stressf2)$r.squared,3), "R^2")

paste(round(summary(rflm.pcs.stressf2)$adj.r.squared,3), "Adj. R^2")
```



```{r}
#Random forest using just microstructure data to predict stress
#no size or processing info




trainset.us <- select(trainset2, -Dim.1,-Dim.2,-Dim.3,-Dim.4,-Dim.5,-Dim.6, -aveAreafine,
       -totNifrace,
       -Ni.Vol.Corrected, -Temp, -hrs,
       -Th.Density)

testset.us <- select(testset2, -Dim.1,-Dim.2,-Dim.3,-Dim.4,-Dim.5,-Dim.6, -aveAreafine,
       -totNifrace,
       -Ni.Vol.Corrected, -Temp, -hrs,
       -Th.Density)


rf.us <- randomForest(x = trainset.us, y = trainset.us$stressf2, ntree = 300)

#remove Ni.Vol.Corrected from RF model

plot(rf.us, main = paste("Stress Random Forest - microstructure only -", 
                        round(last(rf.us$rsq)*100,2),
                        "% Var Explained"
                        )
     )
#print(rfmodel)

rfmodimp.us <- importance(rf.us) %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(IncNodePurity) %>%
  filter(rowname != "stressf2")

dotchart(rfmodimp.us$IncNodePurity, labels = rfmodimp.us$rowname, main = "Stress RF")

importance(rf.us) %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(desc(IncNodePurity))

rfresults.us <- predict(rf.us, testset.us) %>%
  as.data.frame() %>%
  cbind(as.data.frame(testset.us$stressf2))

colnames(rfresults.us)[1] <- "prediction"
colnames(rfresults.us)[2] <- "actual"


cbind(rfresults.us, testset2) %>%
  ggplot() +
  geom_point(aes(y = prediction, x = stressf2, color = as.factor(Ni.Vol.Corrected))) +
  geom_abline(slope = 1, intercept = 0) +
  guides(color = FALSE) +
  theme_classic() +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  coord_fixed() +
  xlab(expression(sigma[fr]~'['*MPa*']')) +
  ylab(expression(sigma[fr]~'-'~predicted~'['*MPa*']'))
  #annotate("text", label = round(last(rfmodel$rsq)*100,2), x = mean(rfresults$actual), y = mean(rfresults$prediction)*2)

rflm.us <- lm(rfresults.us$prediction ~ rfresults.us$actual)

paste(round(summary(rflm.us)$r.squared,3), "R^2")

paste(round(summary(rflm.us)$adj.r.squared,3), "Adj. R^2")

```
-->


<!--

```{r}
svmctrl <- trainControl(method = "LOOCV", #repeatedcv vs Leave one out cross validation
             #number = 10,
             #repeats = 10,
             #p = 0.7,
             #sampling = "up",
             )
             

stress.svm <- train(stressf2 ~ ., data = select(trainset2,-Ni.Vol.Corrected), 
                method = "svmPoly", #svmLinear is worse
                trControl = svmctrl)

stress.svmresults <- predict(stress.svm, testset2) %>%
  as.data.frame()

colnames(stress.svmresults)[1] <- "prediction"





stress.svmimp <- varImp(stress.svm)[1] %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(Overall)

stress.svmvarex <- stress.svm$results %>%
  select(RMSE) %>%
  slice(which.min(RMSE)) %>%
  as.numeric() %>%
  round(3)





stress.svmimp.verb <- stress.svmimp %>%
  mutate(variable = rowname) %>%
  select(-rowname) %>%
  mutate(variable = if_else(variable == "ave.ave.branches", "Average Branch Length", variable)) %>%
  mutate(variable = if_else(variable == "ave.max.branches", "Maximum Branch Length", variable)) %>%
  mutate(variable = if_else(variable == "ave.branches", "Average Number of Branches", variable)) %>%
  mutate(variable = if_else(variable == "aveAreafine", "Average Particle Area", variable)) %>%
  mutate(variable = if_else(variable == "avevoronoix", "Average Voronoi Spacing", variable)) %>%
  mutate(variable = if_else(variable == "fineavennd", "Average NND", variable)) %>%
  mutate(variable = if_else(variable == "finecount", "Counts Per Area", variable)) %>%
  mutate(variable = if_else(variable == "hrs", "Dwell Time", variable)) %>%
  mutate(variable = if_else(variable == "Temp", "Sintering Temperature", variable)) %>%
  mutate(variable = if_else(variable == "Th.Density", "Bulk Density", variable)) %>%
  mutate(variable = if_else(variable == "totNifrace", "Nickel Area Fraction", variable)) %>%
  mutate(variable = if_else(variable == "voronoicount", "Voronoi Map Coverage", variable)) %>%
  mutate(variable = if_else(variable == "Dim.1", "Size-PC-1", variable)) %>%
  mutate(variable = if_else(variable == "Dim.2", "Size-PC-2", variable)) %>%
  mutate(variable = if_else(variable == "Dim.3", "Size-PC-3", variable)) %>%
  mutate(variable = if_else(variable == "Dim.4", "Size-PC-4", variable)) %>%
  mutate(variable = if_else(variable == "Dim.5", "Size-PC-5", variable)) %>%
  mutate(variable = if_else(variable == "Dim.6", "Size-PC-6", variable))

ggplot() +
  geom_point(data = stress.svmimp.verb, aes(x = variable, y = Overall))

# stress.svmvar <- dotchart(stress.svmimp.verb$Overall, labels = stress.svmimp.verb$variable, main = paste("Stress (SVM-Poly.)",
#                       stress.svmvarex*100,
#                       "% Var Explained"))
# print(stress.svmvar)
# ggsave(filename = "./MLexports/stress.svmvar.png", plot = stress.svmvar, 
#          device = "png", width = 6,height = 4, units = "in")
# rm(stress.svmvar)
png("./MLexports/stresssvmvar.png")
print(dotchart(stress.svmimp.verb$Overall, xlab = "Importance", labels = stress.svmimp.verb$variable, main = paste("Stress SVM -",
                                                                                              stress.svmvarex,
                                                                                              "RMSE")))
dev.off()


varImp(stress.svm)[1] %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(desc(Overall))


stress.svmlm <- lm(stress.svmresults$prediction ~ testset2$stressf2)

paste(round(summary(stress.svmlm)$r.squared,3)*100, "R^2")

paste(round(summary(stress.svmlm)$adj.r.squared,3)*100, "Adj. R^2")

print(stress.svm)
#to try: ensemble SVM / cross validate across different test/train splits

stress.svmpredmeas <- cbind(stress.svmresults, testset2) %>%
  ggplot() +
  geom_point(aes(y = prediction, x = stressf2, color = as.factor(Ni.Vol.Corrected))) +
  geom_abline(slope = 1, intercept = 0) +
  guides(color = FALSE) +
  theme_classic() +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  coord_fixed() +
  xlab(expression(Scaled~sigma[fr])) +
  ylab(expression(sigma[fr]~'-'~predicted)) +
  geom_abline(slope = stress.svmlm$coefficients[2], 
              intercept = stress.svmlm$coefficients[1],
              color = "red",linetype = "dashed") +
  annotate("text", label = paste(round(summary(stress.svmlm)$adj.r.squared,3), "Adj. R^2"), 
           x = 1, 
           y = -1)

print(stress.svmpredmeas)
ggsave(filename = "./MLexports/stresssvmpredmeas.png", plot = stress.svmpredmeas, 
         device = "png", width = 6,height = 4, units = "in")
rm(stress.svmpredmeas)
```

-->


```{r}
#ML File Finished
```
