---
title: "LTO-Ni-NND-Voronoi-PCA"
author: "whh36"
date: "11/19/2020"
output: html_document
---

#NND

##scree

```{r}
prcomp.NND <- nnddensities %>%
  mutate(Label = substr(Labelfine, 1, 5)) %>%
  left_join(., fractSum, by = "Label") %>%
  #
  #same filters below as R3 PCA
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Label != "WH21B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  #
  select(nndx, nnddens, Labelfine) %>%
  mutate(nndx = round(nndx, digits = 3)) %>%
  spread(., key = nndx, value = nnddens) %>%
  select(-Labelfine) %>%
  prcomp(scale = TRUE)

prcomp.NND.meta <- nnddensities %>%
  mutate(Label = substr(Labelfine, 1, 5)) %>%
  left_join(., fractSum, by = "Label") %>%
  #
  #same filters below as R3 PCA
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Label != "WH21B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  #
  select(-nndx, -nnddens) %>%
  unique()

prcomp.NND.meta$Temp <- as.factor(prcomp.NND.meta$Temp)
prcomp.NND.meta$hrs <- as.factor(prcomp.NND.meta$hrs)
prcomp.NND.meta$Ni.Vol.Corrected <- as.factor(prcomp.NND.meta$Ni.Vol.Corrected)


fviz_eig(prcomp.NND, addlabels = TRUE)

loadingplot(prcomp.NND, comps = 1:5, legendpos = "right", labels = 'numbers', pretty.xlabels = TRUE, #xlab = 'Time (s)',
            ylab = 'Loading Value')

```

##scores

```{r}
autoplot(prcomp.NND, data = prcomp.NND.meta,
         x = 1,
         y = 2,
         colour = "Temp",
         #shape = "hrs",
         label = FALSE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  geom_hline(yintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  geom_vline(xintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  {if(cb == 1)scale_fill_scico_d(palette = "batlow", direction = 1, begin = 0, end = 0.7)} +
  {if(cb == 1)scale_color_scico_d(palette = "batlow", direction = 1, begin = 0, end = 0.7)} +
  theme_classic()

autoplot(prcomp.NND, data = prcomp.NND.meta,
         x = 1,
         y = 2,
         colour = "hrs",
         label = FALSE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  geom_hline(yintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  geom_vline(xintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  {if(cb == 1)scale_fill_scico_d(palette = "lajolla", direction = 1, begin = 0.4, end = 1)} +
  {if(cb == 1)scale_color_scico_d(palette = "lajolla", direction = 1, begin = 0.4, end = 1)} +
  theme_classic()

autoplot(prcomp.NND, data = prcomp.NND.meta,
         x = 1,
         y = 2,
         colour = "Ni.Vol.Corrected",
         #shape = "hrs",
         label = FALSE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  geom_hline(yintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  geom_vline(xintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  {if(cb == 1)scale_fill_scico_d(palette = "roma", direction = 1)} +
  {if(cb == 1)scale_color_scico_d(palette = "roma", direction = 1)} +
  labs(colour = "Ni [%]") +
  labs(fill = "Ni [%]") +
  scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  theme_classic()



autoplot(prcomp.NND, 
         x = 1,
         y = 2,
         data = prcomp.NND.meta,
         colour = "Temp",
         shape = "hrs",
         label = FALSE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  {if(cb == 1)scale_fill_scico_d(palette = "batlow", direction = 1, begin = 0, end = 0.7)} +
  {if(cb == 1)scale_color_scico_d(palette = "batlow", direction = 1, begin = 0, end = 0.7)} +
  theme_classic()
```

##filmstrip

```{r}
prcomp.NND.rot <- prcomp.NND$rotation %>%
  as.data.frame() %>%
  rownames_to_column(var = "nndx") %>%
  mutate(nndx = as.numeric(nndx)) %>%
  #filter(r3x >= -4) %>%
  #filter(r3x <= 4) %>%
  select(1:11)

prcomp.NND.rot %>%
  mutate(nndx = 10^nndx) %>% #log scale fix
  #
  ggplot() +
  geom_tile(aes(x = nndx, y = 1, width = 0.025, height = 0.1, fill = PC1)) +
  geom_tile(aes(x = nndx, y = 2, width = 0.025, height = 0.1, fill = PC2)) +
  geom_tile(aes(x = nndx, y = 3, width = 0.025, height = 0.1, fill = PC3)) +
  geom_tile(aes(x = nndx, y = 4, width = 0.025, height = 0.1, fill = PC4)) +
  geom_tile(aes(x = nndx, y = 5, width = 0.025, height = 0.1, fill = PC5)) +
  #
  scale_fill_scico(palette = "roma", limits = c(-0.2,0.2), 
                   direction = -1) +
  #scale_fill_gradientn(colors = brewer_pal(palette = "RdBu")(5), limits = c(-0.15,0.15)) +
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  ylab("PC") +
  xlab(expression(Nearest~Neighbor~Distance~'['*mu*m*']')) +
  labs(fill = "PC") +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))


```

```{r}
prcomp.NND.Var = get_pca_ind(prcomp.NND)

#prcomp.NND.Contrib = prcomp.NND.Var$contrib

prcomp.NND.Coord = as.data.frame(prcomp.NND.Var$coord)[1:10]

rm(prcomp.NND.Var)


prcomp.NND.results <- prcomp.NND.meta %>%
  select(Labelfine) %>%
  cbind(., prcomp.NND.Coord) %>%
  rename(NND.PC1 = Dim.1,
         NND.PC2 = Dim.2,
         NND.PC3 = Dim.3,
         NND.PC4 = Dim.4,
         NND.PC5 = Dim.5,
         NND.PC6 = Dim.6,
         NND.PC7 = Dim.7,
         NND.PC8 = Dim.8,
         NND.PC9 = Dim.9,
         NND.PC10 = Dim.10)

```


#EDGE

##scree

```{r}
prcomp.v <- voronoidens %>%
  #same filters below as R3 PCA
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Label != "WH21B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  #
  select(x, density, Labelfine) %>%
  mutate(x = round(x, digits = 3)) %>%
  spread(., key = x, value = density) %>%
  select(-Labelfine) %>%
  prcomp(scale = TRUE)
  
prcomp.v.meta <- voronoidens %>%
  #same filters below as R3 PCA
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Label != "WH21B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  select(-x,-density,-count) %>%
  unique()

prcomp.v.meta$Temp <- as.factor(prcomp.v.meta$Temp)
prcomp.v.meta$hrs <- as.factor(prcomp.v.meta$hrs)
prcomp.v.meta$Ni.Vol.Corrected <- as.factor(prcomp.v.meta$Ni.Vol.Corrected)

fviz_eig(prcomp.v, addlabels = TRUE)

loadingplot(prcomp.v, comps = 1:5, legendpos = "right", labels = 'numbers', pretty.xlabels = TRUE, #xlab = 'Time (s)',
            ylab = 'Loading Value')
```

##scores

```{r}
autoplot(prcomp.v, data = prcomp.v.meta,
         x = 1,
         y = 2,
         colour = "Temp",
         #shape = "hrs",
         label = FALSE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  geom_hline(yintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  geom_vline(xintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  {if(cb == 1)scale_fill_scico_d(palette = "batlow", direction = 1, begin = 0, end = 0.7)} +
  {if(cb == 1)scale_color_scico_d(palette = "batlow", direction = 1, begin = 0, end = 0.7)} +
  theme_classic()

autoplot(prcomp.v, data = prcomp.v.meta,
         x = 1,
         y = 2,
         colour = "hrs",
         label = FALSE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  geom_hline(yintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  geom_vline(xintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  {if(cb == 1)scale_fill_scico_d(palette = "lajolla", direction = 1, begin = 0.4, end = 1)} +
  {if(cb == 1)scale_color_scico_d(palette = "lajolla", direction = 1, begin = 0.4, end = 1)} +
  theme_classic()

autoplot(prcomp.v, data = prcomp.v.meta,
         x = 1,
         y = 2,
         colour = "Ni.Vol.Corrected",
         #shape = "hrs",
         label = FALSE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  geom_hline(yintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  geom_vline(xintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  {if(cb == 1)scale_fill_scico_d(palette = "roma", direction = 1)} +
  {if(cb == 1)scale_color_scico_d(palette = "roma", direction = 1)} +
  labs(colour = "Ni [%]") +
  labs(fill = "Ni [%]") +
  scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  theme_classic()



autoplot(prcomp.v, 
         x = 1,
         y = 2,
         data = prcomp.v.meta,
         colour = "Temp",
         shape = "hrs",
         label = FALSE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  {if(cb == 1)scale_fill_scico_d(palette = "batlow", direction = 1, begin = 0, end = 0.7)} +
  {if(cb == 1)scale_color_scico_d(palette = "batlow", direction = 1, begin = 0, end = 0.7)} +
  theme_classic()
```

##filmstrip

```{r}
prcomp.v.rot <- prcomp.v$rotation %>%
  as.data.frame() %>%
  rownames_to_column(var = "vx") %>%
  mutate(vx = as.numeric(vx)) %>%
  #filter(r3x >= -4) %>%
  #filter(r3x <= 4) %>%
  select(1:11)

prcomp.v.rot %>%
  mutate(vx = 10^vx) %>% #log scale fix
  #
  ggplot() +
  geom_tile(aes(x = vx, y = 1, width = 0.025, height = 0.1, fill = PC1)) +
  geom_tile(aes(x = vx, y = 2, width = 0.025, height = 0.1, fill = PC2)) +
  geom_tile(aes(x = vx, y = 3, width = 0.025, height = 0.1, fill = PC3)) +
  geom_tile(aes(x = vx, y = 4, width = 0.025, height = 0.1, fill = PC4)) +
  geom_tile(aes(x = vx, y = 5, width = 0.025, height = 0.1, fill = PC5)) +
  #
  scale_fill_scico(palette = "roma", limits = c(-0.2,0.2), 
                   direction = -1) +
  #scale_fill_gradientn(colors = brewer_pal(palette = "RdBu")(5), limits = c(-0.15,0.15)) +
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  ylab("PC") +
  #xlab(expression(Nearest~Neighbor~Distance~'['*mu*m*']')) +
  labs(fill = "PC") +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

```

```{r}
prcomp.v.Var = get_pca_ind(prcomp.v)

#prcomp.NND.Contrib = prcomp.NND.Var$contrib

prcomp.v.Coord = as.data.frame(prcomp.v.Var$coord)[1:10]

rm(prcomp.v.Var)

prcomp.v.meta <- prcomp.v.meta %>%
  arrange(Labelfine)

prcomp.v.results <- prcomp.v.meta %>%
  select(Labelfine) %>%
  cbind(., prcomp.v.Coord) %>%
  rename(v.PC1 = Dim.1,
         v.PC2 = Dim.2,
         v.PC3 = Dim.3,
         v.PC4 = Dim.4,
         v.PC5 = Dim.5,
         v.PC6 = Dim.6,
         v.PC7 = Dim.7,
         v.PC8 = Dim.8,
         v.PC9 = Dim.9,
         v.PC10 = Dim.10)



# merge(prcomp.NND.results, prcomp.v.results, by = "Labelfine") %>%
#   merge(., select(prcomp.R3.Results, 1:12, stressf, condAve), by = "Labelfine") %>%
#   write.table(., file = "./PCA-compiled.csv", row.names = FALSE, sep = ",")
  
```

```{r}
vrn.PC2.Temp <- voronoidens %>%
  #filter(Ni.Vol.Corrected == 0.35) %>%
  #filter(Temp == 900) %>%
  filter(hrs == 5) %>%
  filter(Label != "WH13A") %>%
  filter(Label != "WH03A") %>%
  #group_by(Labelfine) %>%
  #
  mutate(x = round(x, digits = 3)) %>%
  mutate(vx = x) %>%
  select(-x) %>%
  #filter(vx >= -4) %>%
  #filter(vx <= 4) %>%
  left_join(., prcomp.v.rot, by = "vx") %>%
  #
  #mutate(r3x = 10^r3x) %>%
  #
  ggplot(aes(fill = PC2)) +
  geom_ridgeline_gradient(aes(x = vx, y = Temp, 
                     #fill = PC1,
                     #height = count/200, 
                     height = density*75, #height is either density or count
                     group = Labelfine)) + 

  # geom_rect(color = "black", aes(xmin = avevoronoix-0.01,
  #               ymin = Temp,
  #               xmax = avevoronoix+0.01,
  #               ymax = Temp+100,
  #               fill = as.factor(Temp))) +

  geom_tile(aes(x = vx, y = 1250, width = 0.1, height = 10)) +
  scale_fill_scico(palette = "buda", limits = c(-0.1,0.1), direction = -1) +
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(breaks = c(700,800,900,1000,1100),
                     labels = c(700,800,900,1000,1100),
                     sec.axis = sec_axis(~., breaks = c(700,800,900,1000), labels = NULL)) +
  xlab(expression(Voronoi~Distance~'['*mu*m*']')) +
  ylab(expression(Sintering~Temperature~'['*degree*C*']')) +
  #
  theme_classic() +
  # guides(fill = guide_legend(reverse = TRUE, title = expression(Temp~'['*degree*C*']'), 
  #                              #override.aes = list(size=4), 
  #                              title.theme = element_text(colour = "black",
  #                                                         #face = "bold",
  #                                                         size = 12))) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(vrn.PC2.Temp)
{if(save == 1)ggsave(filename = "./PCAexports/vrn-PC2-Temp.png", plot = vrn.PC2.Temp, 
         device = "png", width = 6,height = 4, units = "in")}
rm(vrn.PC2.Temp)
```

```{r}
vrn.PC1.Ni <- voronoidens %>%
  mutate(Ni.Vol.Corrected2 = Ni.Vol.Corrected) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.05,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.05, 1), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.10,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.10, 2), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.20,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.20, 3), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.24,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.24, 4), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.28,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.28, 5), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.35,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.35, 6), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.40,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.40, 7), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.50,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.50, 8), Ni.Vol.Corrected2)) %>%
  
  filter(Temp == 900) %>%
  #filter(Ni.Vol.Corrected == 0.35) %>%
  filter(hrs == 5) %>%
  filter(Label != "WH13A") %>%
  filter(Labelfine != "WH15B/900-5-50B0008.tiff") %>%
  #group_by(Labelfine) %>%
  #
  mutate(x = round(x, digits = 3)) %>%
  mutate(vx = x) %>%
  select(-x) %>%
  #filter(vx >= -4) %>%
  #filter(vx <= 4) %>%
  left_join(., prcomp.v.rot, by = "vx") %>%
  #
  ggplot(aes(fill = PC1)) +
  geom_ridgeline_gradient(aes(x = vx, y = Ni.Vol.Corrected2,
                              #color = as.factor(Temp),
                     #fill = as.factor(Ni.Vol.Corrected),
                     #height = count/20000, 
                     height = density, #height is either density or count
                     group = Labelfine)) + 
  #geom_tile(aes(x = vx, y = 10, width = 0.1, height = 0.25)) +
  scale_fill_scico(palette = "buda", limits = c(-0.1,0.1), direction = -1) +
  #
  # geom_rect(color = "black", aes(xmin = avevoronoix-0.01, 
  #               ymin = Ni.Vol.Corrected2, 
  #               xmax = avevoronoix+0.01, 
  #               ymax = Ni.Vol.Corrected2+1,
  #               fill = as.factor(Ni.Vol.Corrected))) +
  #
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(breaks = c(1:8#,10
                                ),
                     labels = c("0.05", "0.10", "0.20", "0.24", "0.28", "0.35", "0.40", "0.50"#,"PC"
                                ),
                     sec.axis = sec_axis(~., breaks = c(1:8), labels = NULL)) +
  xlab(expression(Voronoi~Distance~'['*mu*m*']')) +
  ylab("Nickel Volume Fraction") +
  #
  theme_classic() +
  labs(tag = "(d)") +
  # guides(colour = FALSE, fill = guide_legend(reverse = TRUE, title = "PC", 
  #                              #override.aes = list(size=4), 
  #                              title.theme = element_text(colour = "black",
  #                                                         #face = "bold",
  #                                                         size = 12))) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        plot.tag = element_text(colour = "black", size = 18, face = "bold"),
        legend.text = element_text(colour="black", size = 12))


print(vrn.PC1.Ni)
{if(save == 1)ggsave(filename = "./PCAexports/vrn-PC1-Ni.png", plot = vrn.PC1.Ni, 
         device = "png", width = 6,height = 4, units = "in")}
rm(vrn.PC1.Ni)

#scico_palette_show()
```


```{r}
con.vrn.PC1 <- voronoidens %>%
  mutate(stresso = stressf*exp((1.05-Th.Density/100)*coef(fracmodel)[2]*-1)) %>%
  filter(Label != "WH03A") %>%
  filter(Label != "WH13A") %>%
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH35A/WH35A0010.tiff") %>%
  filter(is.na(condAve) == FALSE) %>%
  #filter(is.na(stressf) == FALSE) %>%
  #mutate(Label = substr(Label,0,4)) %>%
  group_by(Labelfine) %>%
  #
  #filter(hrs == 5) %>%
  #filter(Ni.Vol.Corrected == 0.35) %>%
  mutate(x = round(x, digits = 3)) %>%
  mutate(vx = x) %>%
  select(-x) %>%
  #filter(vx >= -4) %>%
  #filter(vx <= 4) %>%
  left_join(., prcomp.v.rot, by = "vx") %>%
  #
  ggplot(aes(fill = PC1)) +
  geom_ridgeline_gradient(aes(x = vx, y = condAve, 
                     #fill = as.factor(Ni.Vol.Corrected),
                     #height = count/100000, 
                     height = density, #height is either density or count
                     group = Labelfine)) + 
  geom_tile(aes(x = vx, y = 5*10^5, width = 0.1, height = 0.25)) +
  scale_fill_scico(palette = "buda", limits = c(-0.1,0.1), direction = -1) +
  # geom_rect(color = "black", aes(xmin = avevoronoix-0.01,
  #               ymin = condAve,
  #               xmax = avevoronoix+0.01,
  #               ymax = condAve*2,
  #               fill = as.factor(Ni.Vol.Corrected))) +
  scale_x_log10(limits = c(0.05, 10), sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_log10(sec.axis = sec_axis(~., labels = NULL)) +
  ylab("Electrical Conductivity [S/cm]") +
  xlab(expression('Edge-to-Edge'~Distance~'['*mu*m*']')) +
  theme_classic()

print(con.vrn.PC1)
{if(save == 1)ggsave(filename = "./PCAexports/con-vrn-PC1.png", plot = con.vrn.PC1, 
         device = "png", width = 6,height = 4, units = "in")}
rm(con.vrn.PC1)
```

```{r}
con.vrn.PC2 <- voronoidens %>%
  mutate(stresso = stressf*exp((1.05-Th.Density/100)*coef(fracmodel)[2]*-1)) %>%
  filter(Label != "WH03A") %>%
  filter(Label != "WH13A") %>%
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH35A/WH35A0010.tiff") %>%
  filter(is.na(condAve) == FALSE) %>%
  #filter(is.na(stressf) == FALSE) %>%
  #mutate(Label = substr(Label,0,4)) %>%
  group_by(Labelfine) %>%
  #
  #filter(hrs == 5) %>%
  #filter(Ni.Vol.Corrected == 0.35) %>%
  mutate(x = round(x, digits = 3)) %>%
  mutate(vx = x) %>%
  select(-x) %>%
  #filter(vx >= -4) %>%
  #filter(vx <= 4) %>%
  left_join(., prcomp.v.rot, by = "vx") %>%
  #
  ggplot(aes(fill = PC2)) +
  geom_ridgeline_gradient(aes(x = vx, y = condAve, 
                     #fill = as.factor(Ni.Vol.Corrected),
                     #height = count/100000, 
                     height = density, #height is either density or count
                     group = Labelfine)) + 
  geom_tile(aes(x = vx, y = 5*10^5, width = 0.1, height = 0.25)) +
  scale_fill_scico(palette = "buda", limits = c(-0.1,0.1), direction = -1) +
  # geom_rect(color = "black", aes(xmin = avevoronoix-0.01,
  #               ymin = condAve,
  #               xmax = avevoronoix+0.01,
  #               ymax = condAve*2,
  #               fill = as.factor(Ni.Vol.Corrected))) +
  scale_x_log10(limits = c(0.05, 10), sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_log10(sec.axis = sec_axis(~., labels = NULL)) +
  ylab("Electrical Conductivity [S/cm]") +
  xlab(expression('Edge-to-Edge'~Distance~'['*mu*m*']')) +
  theme_classic()

print(con.vrn.PC2)
{if(save == 1)ggsave(filename = "./PCAexports/con-vrn-PC2.png", plot = con.vrn.PC2, 
         device = "png", width = 6,height = 4, units = "in")}
rm(con.vrn.PC2)
```

```{r}
con.vrn.PC3 <- voronoidens %>%
  mutate(stresso = stressf*exp((1.05-Th.Density/100)*coef(fracmodel)[2]*-1)) %>%
  filter(Label != "WH03A") %>%
  filter(Label != "WH13A") %>%
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH35A/WH35A0010.tiff") %>%
  filter(is.na(condAve) == FALSE) %>%
  #filter(is.na(stressf) == FALSE) %>%
  #mutate(Label = substr(Label,0,4)) %>%
  group_by(Labelfine) %>%
  #
  #filter(hrs == 5) %>%
  #filter(Ni.Vol.Corrected == 0.35) %>%
  mutate(x = round(x, digits = 3)) %>%
  mutate(vx = x) %>%
  select(-x) %>%
  #filter(vx >= -4) %>%
  #filter(vx <= 4) %>%
  left_join(., prcomp.v.rot, by = "vx") %>%
  #
  ggplot(aes(fill = PC3)) +
  geom_ridgeline_gradient(aes(x = vx, y = condAve, 
                     #fill = as.factor(Ni.Vol.Corrected),
                     #height = count/100000, 
                     height = density, #height is either density or count
                     group = Labelfine)) + 
  geom_tile(aes(x = vx, y = 5*10^5, width = 0.1, height = 0.25)) +
  scale_fill_scico(palette = "buda", limits = c(-0.15,0.15), direction = -1) +
  # geom_rect(color = "black", aes(xmin = avevoronoix-0.01,
  #               ymin = condAve,
  #               xmax = avevoronoix+0.01,
  #               ymax = condAve*2,
  #               fill = as.factor(Ni.Vol.Corrected))) +
  scale_x_log10(limits = c(0.05, 10), sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_log10(sec.axis = sec_axis(~., labels = NULL)) +
  ylab("Electrical Conductivity [S/cm]") +
  xlab(expression('Edge-to-Edge'~Distance~'['*mu*m*']')) +
  theme_classic()

print(con.vrn.PC3)
{if(save == 1)ggsave(filename = "./PCAexports/con-vrn-PC3.png", plot = con.vrn.PC3, 
         device = "png", width = 6,height = 4, units = "in")}
rm(con.vrn.PC3)
```


