---
title: "LTO-Ni-Paper"
author: "whh36"
date: "12/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggpubr)

save <- 1
```

#Feature extraction

```{r}

line1 <- expression('Edge-to-Edge'~Distance~'['*mu*m*']')
line2 <- expression('Center-to-Center'~Distance~'['*mu*m*']')

voronoiTempave <- voronoidens %>%
  select(Label, Ni.Vol.Corrected, Temp, hrs, Th.Density,
         stressf, condAve, fineavennd, countperarea,
         avevoronoix, voronoicount) %>%
  unique() %>%
  #
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(hrs == 5) %>%
  filter(Label != "WH13A") %>%
  filter(Label != "WH03A") %>%
  #
  mutate(stresso = stressf*exp((1.05-Th.Density/100)*coef(fracmodel)[2]*-1)) %>%
  #
  ggplot() +
  #
  geom_boxplot(color = "purple", width = 25, aes(group = Temp, x = Temp, y = avevoronoix)) +
  geom_point(size = 2, shape = 19, color = "purple", aes(y = avevoronoix, x = Temp, 
                 #size = as.factor(hrs),
                 #shape = as.factor(Temp),
                 #color = as.factor(Temp)
                 )) +
  #
  geom_boxplot(color = "black", width = 25, aes(group = Temp, x = Temp, y = countperarea)) +
  geom_point(size = 2, shape = 17, color = "black", aes(y = countperarea, x = Temp, 
                 #size = as.factor(hrs),
                 #shape = as.factor(Temp),
                 #color = as.factor(Temp)
                 )) +
  #
  geom_boxplot(color = "red", width = 25, aes(group = Temp, x = Temp, y = fineavennd)) +
  geom_point(size = 2, shape = 15, color = "red", aes(x = Temp, y = fineavennd, color = as.factor(Temp))) +
  #
  xlab(expression(Temp~'['*degree*C*']')) +
  #ylab(expression(Relative~Particle~Spacing~'['*mu*m*']')) +
  ylab("") +
  #scale_y_continuous(limits = c(0,2.5), sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(limits = c(0,2.5), sec.axis = sec_axis(~., 
                                                            name = expression('Counts-Per-Area'~'['*cts*'/'*mu*m^2*']')
                                                            )
                     ) +
  #guides(color = FALSE) +
  theme_classic() +
  
  coord_cartesian(clip = "off") +
  annotation_custom(text_grob(line1, color = "purple", rot = 90, face = "bold", size = 16), 
                    xmin = 540, xmax = 540, ymin = 1.25, ymax = 1.25) +
  annotation_custom(text_grob(line2, color = "red", rot = 90, face = "bold" , size = 16),
                    xmin = 585, xmax = 585, ymin = 1.25, ymax = 1.25) +
  
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        plot.margin = margin(10,10,10,45),
        legend.text = element_text(colour="black", size = 12))

print(voronoiTempave)
{if(save == 1)ggsave(filename = "./paperexports/relspace-cts-Temp.png", plot = voronoiTempave, 
    device = "png", width = 6,height = 4, units = "in")}
rm(voronoiTempave)

```

```{r}

line1 <- expression('Edge-to-Edge'~Distance~'['*mu*m*']')
line2 <- expression('Center-to-Center'~Distance~'['*mu*m*']')

voronoiNiave <- voronoidens %>%
  select(Label, Labelfine, Ni.Vol.Corrected, Temp, hrs, Th.Density,
         stressf, condAve, fineavennd, countperarea,
         avevoronoix, voronoicount) %>%
  unique() %>%
  #
  filter(Temp == 900) %>%
  #filter(Ni.Vol.Corrected == 0.35) %>%
  filter(hrs == 5) %>%
  filter(Label != "WH13A") %>%
  filter(Labelfine != "WH15B/900-5-50B0008.tiff") %>%
  #
  mutate(stresso = stressf*exp((1.05-Th.Density/100)*coef(fracmodel)[2]*-1)) %>%
  #
  ggplot() +
  #
  geom_boxplot(color = "purple", aes(group = Ni.Vol.Corrected, x = Ni.Vol.Corrected, y = avevoronoix)) +
  geom_point(size = 2, shape = 19, color = "purple", aes(y = avevoronoix, x = Ni.Vol.Corrected, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 #color = as.factor(Ni.Vol.Corrected)
                 )) +
  #
  geom_boxplot(color = "black", aes(group = Ni.Vol.Corrected, x = Ni.Vol.Corrected, y = countperarea)) +
  geom_point(size = 2, shape = 17, color = "black", aes(y = countperarea, x = Ni.Vol.Corrected, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 #color = as.factor(Ni.Vol.Corrected)
                 )) +
  #
  geom_boxplot(color = "red", aes(group = Ni.Vol.Corrected, x = Ni.Vol.Corrected, y = fineavennd)) +
  geom_point(size = 2, shape = 15, color = "red", aes(x = Ni.Vol.Corrected, y = fineavennd, #color = as.factor(Ni.Vol.Corrected)
                                         )) +
  #
  xlab("Nickel Volume Fraction") +
  #ylab(expression(Relative~Particle~Spacing~'['*mu*m*']')) +
  ylab("") +
  #scale_y_continuous(limits = c(0,2.5), sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(limits = c(0,2.5), sec.axis = sec_axis(~., 
                                                            name = expression('Counts-Per-Area'~'['*cts*'/'*mu*m^2*']')
                                                            )
                     ) +
  #guides(color = FALSE) +
  guides(shape = FALSE) +
  theme_classic() +
  
  coord_cartesian(clip = "off") +
  annotation_custom(text_grob(line1, color = "purple", rot = 90, face = "bold", size = 16), 
                    xmin = -0.12, xmax = -0.12, ymin = 1.25, ymax = 1.25) +
  annotation_custom(text_grob(line2, color = "red", rot = 90, face = "bold" , size = 16),
                    xmin = -0.075, xmax = -0.075, ymin = 1.25, ymax = 1.25) +
  
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        plot.margin = margin(10,10,10,45),
        legend.text = element_text(colour="black", size = 12))

print(voronoiNiave)
{if(save == 1)ggsave(filename = "./paperexports/relspace-cts-ni.png", plot = voronoiNiave, 
    device = "png", width = 6,height = 4, units = "in")}
rm(voronoiNiave)
```

```{r}

line1 <- expression('Edge-to-Edge'~Distance~'['*mu*m*']')
line2 <- expression('Center-to-Center'~Distance~'['*mu*m*']')

voronoihrsave <- voronoidens %>%
  select(Label, Labelfine, Ni.Vol.Corrected, Temp, hrs, Th.Density,
         stressf, condAve, fineavennd, countperarea,
         avevoronoix, voronoicount, magx) %>%
  unique() %>%
  #
  filter(Temp == 900) %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(magx == 10) %>%
  #filter(hrs == 5) %>%
  filter(Label != "WH13A") %>%
  filter(Labelfine != "WH15B/900-5-50B0008.tiff") %>%
  #
  mutate(stresso = stressf*exp((1.05-Th.Density/100)*coef(fracmodel)[2]*-1)) %>%
  #
  ggplot() +
  #
  geom_boxplot(color = "red", aes(group = hrs, x = hrs, y = fineavennd)) +
  geom_point(size = 2, shape = 15, color = "red", aes(x = hrs, y = fineavennd, #color = as.factor(Ni.Vol.Corrected)
                                         )) +
  #
  geom_boxplot(color = "purple", aes(group = hrs, x = hrs, y = avevoronoix)) +
  geom_point(size = 2, shape = 19, color = "purple", aes(y = avevoronoix, x = hrs, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 #color = as.factor(Ni.Vol.Corrected)
                 )) +
  #
  geom_boxplot(color = "black", aes(group = hrs, x = hrs, y = countperarea)) +
  geom_point(size = 2, shape = 17, color = "black", aes(y = countperarea, x = hrs, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 #color = as.factor(Ni.Vol.Corrected)
                 )) +
  #
  
  xlab("Time [hrs]") +
  #ylab(expression(Relative~Particle~Spacing~'['*mu*m*']')) +
  ylab("") +
  #scale_y_continuous(limits = c(0,2.5), sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_log10(breaks = c(5,10,50,150),
                sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(limits = c(0,2.5), sec.axis = sec_axis(~., 
                                                            name = expression('Counts-Per-Area'~'['*cts*'/'*mu*m^2*']')
                                                            )
                     ) +
  #guides(color = FALSE) +
  guides(shape = FALSE) +
  theme_classic() +
  
  coord_cartesian(clip = "off") +
  annotation_custom(text_grob(line1, color = "purple", rot = 90, face = "bold", size = 16), 
                    xmin = 0.04, xmax = 0.04, ymin = 1.25, ymax = 1.25) +
  annotation_custom(text_grob(line2, color = "red", rot = 90, face = "bold" , size = 16),
                    xmin = 0.2, xmax = 0.2, ymin = 1.25, ymax = 1.25) +
  
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        plot.margin = margin(10,10,10,45),
        legend.text = element_text(colour="black", size = 12))

print(voronoihrsave)
{if(save == 1)ggsave(filename = "./paperexports/relspace-cts-hrs.png", plot = voronoihrsave, 
    device = "png", width = 6,height = 4, units = "in")}
#rm(voronoihrsave)
```

```{r}

line1 <- expression('Edge-to-Edge'~Distance~'['*mu*m*']')
line2 <- expression('Center-to-Center'~Distance~'['*mu*m*']')

voronoihrsave2 <- voronoidens %>%
  select(Label, Labelfine, Ni.Vol.Corrected, Temp, hrs, Th.Density,
         stressf, condAve, fineavennd, countperarea,
         avevoronoix, voronoicount, magx) %>%
  unique() %>%
  #
  mutate(hrs = as.double(hrs)) %>%
  mutate(hrs2 = hrs) %>%
  mutate(hrs2 = if_else(hrs == 5, replace(hrs, hrs == 5, 1), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 10, replace(hrs, hrs == 10, 2), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 50, replace(hrs, hrs == 50, 3), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 150, replace(hrs, hrs == 150, 4), hrs2)) %>%
  #
  filter(Temp == 900) %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(magx == 10) %>%
  #filter(hrs == 5) %>%
  filter(Label != "WH13A") %>%
  filter(Labelfine != "WH15B/900-5-50B0008.tiff") %>%
  #
  mutate(stresso = stressf*exp((1.05-Th.Density/100)*coef(fracmodel)[2]*-1)) %>%
  #
  ggplot() +
  #
  geom_boxplot(color = "red", aes(group = hrs, x = hrs2, y = fineavennd)) +
  geom_point(size = 2, shape = 15, color = "red", aes(x = hrs2, y = fineavennd, #color = as.factor(Ni.Vol.Corrected)
                                         )) +
  #
  geom_boxplot(color = "purple", aes(group = hrs, x = hrs2, y = avevoronoix)) +
  geom_point(size = 2, shape = 19, color = "purple", aes(y = avevoronoix, x = hrs2, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 #color = as.factor(Ni.Vol.Corrected)
                 )) +
  #
  geom_boxplot(color = "black", aes(group = hrs, x = hrs2, y = countperarea)) +
  geom_point(size = 2, shape = 17, color = "black", aes(y = countperarea, x = hrs2, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 #color = as.factor(Ni.Vol.Corrected)
                 )) +
  #
  
  xlab("Time [hrs]") +
  #ylab(expression(Relative~Particle~Spacing~'['*mu*m*']')) +
  ylab("") +
  #scale_y_continuous(limits = c(0,2.5), sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_continuous(breaks = c(1:4),
                     labels = c("5","10","50","150"),
                     sec.axis = sec_axis(~., breaks = c(1:4), labels = NULL)) +
  scale_y_continuous(limits = c(0,2.5), sec.axis = sec_axis(~., 
                                                            name = expression('Counts-Per-Area'~'['*cts*'/'*mu*m^2*']')
                                                            )
                     ) +
  #guides(color = FALSE) +
  guides(shape = FALSE) +
  theme_classic() +
  
  coord_cartesian(clip = "off") +
  annotation_custom(text_grob(line1, color = "purple", rot = 90, face = "bold", size = 16), 
                    xmin = -0.45, xmax = -0.45, ymin = 1.25, ymax = 1.25) +
  annotation_custom(text_grob(line2, color = "red", rot = 90, face = "bold" , size = 16),
                    xmin = -0.15, xmax = -0.15, ymin = 1.25, ymax = 1.25) +
  
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        plot.margin = margin(10,10,10,45),
        legend.text = element_text(colour="black", size = 12))

print(voronoihrsave2)
{if(save == 1)ggsave(filename = "./paperexports/relspace-cts-hrs2.png", plot = voronoihrsave2,
    device = "png", width = 6,height = 4, units = "in")}
#rm(voronoihrsave)
```


#Shape analysis

```{r}
scico(9, palette = "davos") %>%
show_col()

PAL <- "lapaz"
PALDir <- 1
PALs <- 0
PALe <- 0.65
PALn <- 3

#{if(cb == 1)scale_color_scico_d(palette = PAL, direction = PALDir, begin = PALs, end = PALe)} +
  
scico(PALn, begin = PALs, end = PALe, direction = PALDir, palette = PAL) %>%
  show_col()

PAL1 <- scico(PALn, begin = PALs, end = PALe, direction = PALDir, palette = PAL)[1]
PAL2 <- scico(PALn, begin = PALs, end = PALe, direction = PALDir, palette = PAL)[2]
PAL3 <- scico(PALn, begin = PALs, end = PALe, direction = PALDir, palette = PAL)[3]
```

<!--
```{r}
PAL <- "berlin"
PALDir <- 1
PALs <- 0
PALe <- 1
PALn <- 10

#{if(cb == 1)scale_color_scico_d(palette = PAL, direction = PALDir, begin = PALs, end = PALe)} +
  
scico(PALn, begin = PALs, end = PALe, direction = PALDir, palette = PAL) %>%
  show_col()

#PAL1 <- scico(PALn, begin = PALs, end = PALe, direction = PALDir, palette = PAL)[1]
#PAL2 <- scico(PALn, begin = PALs, end = PALe, direction = PALDir, palette = PAL)[2]
#PAL3 <- scico(PALn, begin = PALs, end = PALe, direction = PALDir, palette = PAL)[3]
```
-->


```{r}

line1 <- expression('Ave Ave'~Branch~'['*mu*m*']')
line2 <- expression('Ave Max'~Branch~'['*mu*m*']')

voronoiTempave <- skeleton.data %>%
  select(Label, Labelfine, Ni.Vol.Corrected, Temp, hrs, 
         ave.branches, ave.ave.branches, ave.max.branches) %>%
  unique() %>%
  #
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(hrs == 5) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  filter(Label != "WH03A") %>%
  #
  #mutate(stresso = stressf*exp((1.05-Th.Density/100)*coef(fracmodel)[2]*-1)) %>%
  #
  ggplot() +
  #
  geom_boxplot(color = PAL1, aes(group = Temp, x = Temp, y = ave.ave.branches)) +
  geom_point(size = 2, shape = 19, color = PAL1, aes(y = ave.ave.branches, x = Temp, 
                 #size = as.factor(hrs),
                 #shape = as.factor(Temp),
                 #color = as.factor(Temp)
                 )) +
  #
  geom_boxplot(color = PAL3, aes(group = Temp, x = Temp, y = ave.branches/4)) +
  geom_point(size = 2, shape = 17, color = PAL3, aes(y = ave.branches/4, x = Temp, 
                 #size = as.factor(hrs),
                 #shape = as.factor(Temp),
                 #color = as.factor(Temp)
                 )) +
  #
  geom_boxplot(color = PAL2, aes(group = Temp, x = Temp, y = ave.max.branches)) +
  geom_point(size = 2, shape = 15, color = PAL2, aes(x = Temp, y = ave.max.branches, color = as.factor(Temp))) +
  #
  xlab(expression(Temp~'['*degree*C*']')) +
  #ylab(expression(Relative~Particle~Spacing~'['*mu*m*']')) +
  ylab("") +
  #scale_y_continuous(limits = c(0,2.5), sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(limits = c(0,2.5), sec.axis = sec_axis(~.*4, 
                                                            name = expression('Ave Branch Count')
                                                            )
                     ) +
  #guides(color = FALSE) +
  theme_classic() +
  
  coord_cartesian(clip = "off") +
  annotation_custom(text_grob(line1, color = PAL1, rot = 90, face = "bold", size = 16), 
                    xmin = 510, xmax = 510, ymin = 1.25, ymax = 1.25) +
  annotation_custom(text_grob(line2, color = PAL2, rot = 90, face = "bold" , size = 16),
                    xmin = 555, xmax = 555, ymin = 1.25, ymax = 1.25) +
  
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        plot.margin = margin(10,10,10,45),
        axis.title.y.right = element_text(color = PAL3),
        legend.text = element_text(colour="black", size = 12))

print(voronoiTempave)
{if(save == 1)ggsave(filename = "./paperexports/relspace-branches-Temp.png", plot = voronoiTempave, 
    device = "png", width = 6,height = 4, units = "in")}
rm(voronoiTempave)

```

```{r}

line1 <- expression('Ave Ave'~Branch~'['*mu*m*']')
line2 <- expression('Ave Max'~Branch~'['*mu*m*']')

voronoiNiave <- skeleton.data %>%
  select(Label, Labelfine, Ni.Vol.Corrected, Temp, hrs, 
         ave.branches, ave.ave.branches, ave.max.branches) %>%
  unique() %>%
  #
  filter(Temp == 900) %>%
  #filter(Ni.Vol.Corrected == 0.35) %>%
  filter(hrs == 5) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #filter(Label != "WH13A") %>%
  #filter(Labelfine != "WH15B/900-5-50B0008.tiff") %>%
  #
  #mutate(stresso = stressf*exp((1.05-Th.Density/100)*coef(fracmodel)[2]*-1)) %>%
  #
  ggplot() +
  #
  geom_boxplot(color = PAL1, aes(group = Ni.Vol.Corrected, 
                                    x = Ni.Vol.Corrected, y = ave.ave.branches)) +
  geom_point(size = 2, shape = 17, color = PAL1, aes(y = ave.ave.branches, x = Ni.Vol.Corrected, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 #color = as.factor(Ni.Vol.Corrected)
                 )) +
  #
  geom_boxplot(color = PAL3, aes(group = Ni.Vol.Corrected, 
                                     x = Ni.Vol.Corrected, y = ave.branches/4)) +
  geom_point(size = 2, shape = 19, color = PAL3, aes(y = ave.branches/4, x = Ni.Vol.Corrected, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 #color = as.factor(Ni.Vol.Corrected)
                 )) +
  #
  geom_boxplot(color = PAL2, aes(group = Ni.Vol.Corrected, 
                                  x = Ni.Vol.Corrected, y = ave.max.branches)) +
  geom_point(size = 2, shape = 15, color = PAL2, aes(x = Ni.Vol.Corrected, y = ave.max.branches, #color = as.factor(Ni.Vol.Corrected)
                                         )) +
  #
  xlab("Nickel Volume Fraction") +
  #ylab(expression(Relative~Particle~Spacing~'['*mu*m*']')) +
  ylab("") +
  #scale_y_continuous(limits = c(0,2.5), sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(limits = c(0,2.5), 
                     sec.axis = sec_axis(~.*4, 
                                         name = expression('Ave Branch Count')
                                         )
                     ) +
  #guides(color = FALSE) +
  guides(shape = FALSE) +
  theme_classic() +
  
  coord_cartesian(clip = "off") +
  annotation_custom(text_grob(line1, color = PAL1, rot = 90, face = "bold", size = 16), 
                    xmin = -0.12, xmax = -0.12, ymin = 1.25, ymax = 1.25) +
  annotation_custom(text_grob(line2, color = PAL2, rot = 90, face = "bold" , size = 16),
                    xmin = -0.075, xmax = -0.075, ymin = 1.25, ymax = 1.25) +
  
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        plot.margin = margin(10,10,10,45),
        axis.title.y.right = element_text(color = PAL3),
        legend.text = element_text(colour="black", size = 12))

print(voronoiNiave)
{if(save == 1)ggsave(filename = "./paperexports/relspace-branches-ni.png", plot = voronoiNiave, 
    device = "png", width = 6,height = 4, units = "in")}
rm(voronoiNiave)
```




```{r}

line1 <- expression('Ave Ave'~Branch~'['*mu*m*']')
line2 <- expression('Ave Max'~Branch~'['*mu*m*']')

voronoihrsave <- skeleton.data %>%
  select(Label, Labelfine, Ni.Vol.Corrected, Temp, hrs, magx,
         ave.branches, ave.ave.branches, ave.max.branches) %>%
  unique() %>%
  #
  filter(Temp == 900) %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(magx == 10) %>%
  #filter(hrs == 5) %>%
  filter(Label != "WH13A") %>%
  filter(Labelfine != "WH15B/900-5-50B0008.tiff") %>%
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #
  #mutate(stresso = stressf*exp((1.05-Th.Density/100)*coef(fracmodel)[2]*-1)) %>%
  #
  ggplot() +
  #
  geom_boxplot(color = PAL1, aes(group = hrs, x = hrs, y = ave.ave.branches)) +
  geom_point(size = 2, shape = 19, color = PAL1, aes(y = ave.ave.branches, x = hrs, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 #color = as.factor(Ni.Vol.Corrected)
                 )) +
  #
  geom_boxplot(color = PAL3, aes(group = hrs, x = hrs, y = ave.branches/4)) +
  geom_point(size = 2, shape = 17, color = PAL3, aes(y = ave.branches/4, x = hrs, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 #color = as.factor(Ni.Vol.Corrected)
                 )) +
  #
  geom_boxplot(color = PAL2, aes(group = hrs, x = hrs, y = ave.max.branches)) +
  geom_point(size = 2, shape = 15, color = PAL2, aes(x = hrs, y = ave.max.branches, #color = as.factor(Ni.Vol.Corrected)
                                         )) +
  #
  xlab("Time [hrs]") +
  #ylab(expression(Relative~Particle~Spacing~'['*mu*m*']')) +
  ylab("") +
  #scale_y_continuous(limits = c(0,2.5), sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_log10(breaks = c(5,10,50,150),
                sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(limits = c(0,2.5), sec.axis = sec_axis(~.*4, 
                                                            name = expression('Ave Branch Count')
                                                            )
                     ) +
  #guides(color = FALSE) +
  guides(shape = FALSE) +
  theme_classic() +
  
  coord_cartesian(clip = "off") +
  annotation_custom(text_grob(line1, color = PAL1, rot = 90, face = "bold", size = 16), 
                    xmin = 0.04, xmax = 0.04, ymin = 1.25, ymax = 1.25) +
  annotation_custom(text_grob(line2, color = PAL2, rot = 90, face = "bold" , size = 16),
                    xmin = 0.2, xmax = 0.2, ymin = 1.25, ymax = 1.25) +
  
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        plot.margin = margin(10,10,10,45),
        axis.title.y.right = element_text(color = PAL3),
        legend.text = element_text(colour="black", size = 12))

print(voronoihrsave)
{if(save == 1)ggsave(filename = "./paperexports/relspace-branches-hrs.png", plot = voronoihrsave, 
    device = "png", width = 6,height = 4, units = "in")}
rm(voronoihrsave)
```


#density plots

```{r}
line1 <- expression('Edge-to-Edge'~Distance~'['*mu*m*']')
line2 <- expression('Center-to-Center'~Distance~'['*mu*m*']')

tempdata <- filter(df_particles_fine, Label != "WH13A" & Labelfine != "WH35A/WH35A0010.tiff" & Temp == 900 & Area >= 0.005 & Ni.Vol.Corrected == 0.35) %>%
  
  mutate(hrs = as.double(hrs)) %>%
  mutate(hrs2 = hrs) %>%
  mutate(hrs2 = if_else(hrs == 5, replace(hrs, hrs == 5, 1), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 10, replace(hrs, hrs == 10, 2), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 50, replace(hrs, hrs == 50, 3), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 150, replace(hrs, hrs == 150, 4), hrs2))

nudge <- 0.1

dens.space.hrs <- voronoidens %>%
  mutate(hrs = as.double(hrs)) %>%
  mutate(hrs2 = hrs) %>%
  mutate(hrs2 = if_else(hrs == 5, replace(hrs, hrs == 5, 1), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 10, replace(hrs, hrs == 10, 2), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 50, replace(hrs, hrs == 50, 3), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 150, replace(hrs, hrs == 150, 4), hrs2)) %>%
  
  filter(Temp == 900) %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(magx == 10) %>%
  #filter(hrs == 5) %>%
  filter(Label != "WH13A") %>%
  filter(Labelfine != "WH35A/WH35A0010.tiff") %>%
  group_by(Labelfine) %>%
  ggplot() +
  # geom_ridgeline(fill = "purple", aes(x = x, y = hrs2, 
  #                    #fill = as.factor(hrs),
  #                    #height = count/20000, 
  #                    height = density*0.35, #height is either density or count
  #                    group = Labelfine)) + 
  geom_ridgeline(fill = "purple", aes(x = x, y = hrs2,
                     #fill = as.factor(hrs),
                     #height = count/20000,
                     min_height = -10,
                     height = -density*0.35, #height is either density or count
                     group = Labelfine)) +
  
  geom_density_ridges(data = tempdata, fill = "red", scale = 0.35, rel_min_height = 0.01,
                      aes(x = nnd, y = hrs2, group = Label)) +
  geom_boxplot(color = "black", fill = "purple", width = 0.1, aes(group = hrs, y = hrs2-nudge, x = avevoronoix)) +
  geom_point(size = 1, shape = 21, fill = "purple", aes(x = avevoronoix, y = hrs2-nudge, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 #color = as.factor(Ni.Vol.Corrected)
                 )) +
  geom_boxplot(color = "black", fill = "red", width = 0.1, aes(group = hrs, y = hrs2+nudge, x = fineavennd)) +
  geom_point(size = 1, shape = 22, fill = "red", aes(y = hrs2+nudge, x = fineavennd)) +
  #geom_point(size = 1, shape = 24, fill = "black", aes(x = countperarea, y = hrs2)) +
  #
  # geom_rect(color = "black", aes(xmin = avevoronoix-0.01,
  #               ymin = hrs2,
  #               xmax = avevoronoix+0.01,
  #               ymax = hrs2+1,
  #               fill = as.factor(hrs))) +

  #geom_segment(fill = "purple", aes(x = avevoronoix, y = hrs2, xend = avevoronoix, yend = hrs2-nudge*5)) +
  #geom_segment(fill = "red", aes(x = fineavennd, y = hrs2, xend = fineavennd, yend = hrs2+nudge*5)) +
  
  #
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(breaks = c(1:4),
                     labels = c("5","10","50","150"),
                     sec.axis = sec_axis(~., breaks = c(1:4), labels = NULL)) +
  #scale_fill_manual(values=c("#00BF7D", "#BF7D00", "#7C00BF", "#BF0041")) +
  #
  ylab("Time [hrs]") +
  xlab("") +
  theme_classic() +
  coord_flip(clip = "off") +
  annotation_custom(text_grob(line1, color = "purple", rot = 90, face = "bold", size = 16),
                    xmin = 0, xmax = 0, ymin = -2.2, ymax = 1) +
  annotation_custom(text_grob(line2, color = "red", rot = 90, face = "bold" , size = 16),
                    xmin = 0, xmax = 0, ymin = -1.6, ymax = 1) +
  guides(color = "none", fill = guide_legend(reverse = TRUE, title = "Time [hrs]", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        plot.margin = margin(10,10,10,45),
        legend.text = element_text(colour="black", size = 12))

print(dens.space.hrs)
{if(save == 1)ggsave(filename = "./paperexports/dens_space-cts-hrs.png", plot = dens.space.hrs, 
    device = "png", width = 6,height = 4, units = "in")}
rm(dens.space.hrs)
```
```{r}
inset.plot <- voronoidens %>%
  mutate(hrs = as.double(hrs)) %>%
  mutate(hrs2 = hrs) %>%
  mutate(hrs2 = if_else(hrs == 5, replace(hrs, hrs == 5, 1), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 10, replace(hrs, hrs == 10, 2), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 50, replace(hrs, hrs == 50, 3), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 150, replace(hrs, hrs == 150, 4), hrs2)) %>%
  
  filter(Temp == 900) %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(magx == 10) %>%
  #filter(hrs == 5) %>%
  filter(Label != "WH13A") %>%
  filter(Labelfine != "WH35A/WH35A0010.tiff") %>%
  group_by(Labelfine) %>%
  ggplot() +
  # geom_ridgeline(fill = "purple", aes(x = x, y = hrs2, 
  #                    #fill = as.factor(hrs),
  #                    #height = count/20000, 
  #                    height = density*0.35, #height is either density or count
  #                    group = Labelfine)) + 
  geom_ridgeline(fill = "purple", aes(x = x, y = hrs2,
                     #fill = as.factor(hrs),
                     #height = count/20000,
                     min_height = -10,
                     height = -density*0.35, #height is either density or count
                     group = Labelfine)) +
  
  geom_density_ridges(data = tempdata, fill = "red", scale = 0.35, rel_min_height = 0.01,
                      aes(x = nnd, y = hrs2, group = Label)) +

  scale_x_log10(breaks = NULL, labels = NULL, sec.axis = sec_axis(~., breaks = NULL, labels = NULL)) +
  scale_y_continuous(breaks = NULL,
                     labels = NULL,
                     sec.axis = sec_axis(~., breaks = NULL, labels = NULL)) +
  #scale_fill_manual(values=c("#00BF7D", "#BF7D00", "#7C00BF", "#BF0041")) +
  #
  ylab("") +
  xlab("") +
  theme_classic() +
  coord_flip(clip = "off") +
  guides(color = FALSE, fill = guide_legend(reverse = TRUE, title = "Time [hrs]", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  theme(axis.text.x = element_text(colour = "black", size = 12),
        axis.text.y = element_text(colour = "black", size = 12),
        axis.ticks = element_line(colour = "black", size = 1),
        #axis.line = element_line(colour = 'black', size = 1),
        axis.line = element_line(colour='transparent'),
        axis.title.x = element_text(colour = "black", size = 12),
        axis.title.y = element_text(colour = "black", size = 12),
        panel.background = element_rect(fill='transparent'),
        plot.background = element_rect(fill='transparent', color=NA),
        legend.text = element_text(colour="black", size = 12))

extra <- voronoihrsave2 +
  annotation_custom(ggplotGrob(inset.plot),
                    xmin = 0.13,
                    xmax = 4.5,
                    ymin = 1.2,
                    ymax = 2.9)

{if(save == 1)ggsave(filename = "./paperexports/relspace-cts-hrs-extra.png", plot = extra, device = "png", width = 6,height = 4, units = "in")}

```

```{r}
line1 <- expression('Ave. Edge-to-Edge'~Distance~'['*mu*m*']')
line2 <- expression('Ave. Center-to-Center'~Distance~'['*mu*m*']')
line3 <- expression('Edge-to-Edge'~Distribution~'['*mu*m*']')
line4 <- expression('Center-to-Center'~Distribution~'['*mu*m*']')

inset.plot2 <- voronoidens %>%
  mutate(hrs = as.double(hrs)) %>%
  mutate(hrs2 = hrs) %>%
  mutate(hrs2 = if_else(hrs == 5, replace(hrs, hrs == 5, 1), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 10, replace(hrs, hrs == 10, 2), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 50, replace(hrs, hrs == 50, 3), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 150, replace(hrs, hrs == 150, 4), hrs2)) %>%
  
  filter(Temp == 900) %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(magx == 10) %>%
  #filter(hrs == 5) %>%
  filter(Label != "WH13A") %>%
  filter(Labelfine != "WH35A/WH35A0010.tiff") %>%
  group_by(Labelfine) %>%
  ggplot() +
  # geom_ridgeline(fill = "purple", aes(x = x, y = hrs2, 
  #                    #fill = as.factor(hrs),
  #                    #height = count/20000, 
  #                    height = density*0.35, #height is either density or count
  #                    group = Labelfine)) + 
  geom_ridgeline(fill = "purple", aes(x = x, y = hrs2,
                     #fill = as.factor(hrs),
                     #height = count/20000,
                     min_height = -10,
                     height = -density*0.35, #height is either density or count
                     group = Labelfine)) +
  
  geom_density_ridges(data = tempdata, fill = "red", scale = 0.35, rel_min_height = 0.01,
                      aes(x = nnd, y = hrs2, group = Label)) +

  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(breaks = c(1:4),
                     labels = c("5","10","50","150"),
                     sec.axis = sec_axis(~., breaks = c(1:4), labels = NULL)) +
  #scale_fill_manual(values=c("#00BF7D", "#BF7D00", "#7C00BF", "#BF0041")) +
  #
  ylab("") +
  xlab("") +
  theme_classic() +
  coord_flip(clip = "off") +
  guides(color = FALSE, fill = guide_legend(reverse = TRUE, title = "Time [hrs]", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  theme(axis.text.x = element_text(colour = "black", size = 12),
        axis.text.y = element_text(colour = "black", size = 12),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        #axis.line = element_line(colour='transparent'),
        axis.title.x = element_text(colour = "black", size = 12),
        axis.title.y = element_text(colour = "black", size = 12),
        panel.background = element_rect(fill='transparent'),
        plot.background = element_rect(fill='transparent', color=NA),
        legend.text = element_text(colour="black", size = 12))

extra2 <- voronoidens %>%
  select(Label, Labelfine, Ni.Vol.Corrected, Temp, hrs, Th.Density,
         stressf, condAve, fineavennd, countperarea,
         avevoronoix, voronoicount, magx) %>%
  unique() %>%
  #
  mutate(hrs = as.double(hrs)) %>%
  mutate(hrs2 = hrs) %>%
  mutate(hrs2 = if_else(hrs == 5, replace(hrs, hrs == 5, 1), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 10, replace(hrs, hrs == 10, 2), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 50, replace(hrs, hrs == 50, 3), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 150, replace(hrs, hrs == 150, 4), hrs2)) %>%
  #
  filter(Temp == 900) %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(magx == 10) %>%
  #filter(hrs == 5) %>%
  filter(Label != "WH13A") %>%
  filter(Labelfine != "WH15B/900-5-50B0008.tiff") %>%
  #
  mutate(stresso = stressf*exp((1.05-Th.Density/100)*coef(fracmodel)[2]*-1)) %>%
  #
  ggplot() +
  #
  geom_boxplot(color = "red", width = 0.25, aes(group = hrs, x = hrs2, y = fineavennd)) +
  geom_point(size = 2, shape = 15, color = "red", aes(x = hrs2, y = fineavennd, #color = as.factor(Ni.Vol.Corrected)
                                         )) +
  #
  geom_boxplot(color = "purple", width = 0.25, aes(group = hrs, x = hrs2, y = avevoronoix)) +
  geom_point(size = 2, shape = 19, color = "purple", aes(y = avevoronoix, x = hrs2, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 #color = as.factor(Ni.Vol.Corrected)
                 )) +
  #
  geom_boxplot(color = "transparent", aes(group = hrs, x = hrs2, y = countperarea)) +
  geom_boxplot(color = "black", width = 0.25, aes(group = hrs, x = hrs2, y = countperarea)) +
  geom_point(size = 2, shape = 17, color = "black", aes(y = countperarea, x = hrs2, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 #color = as.factor(Ni.Vol.Corrected)
                 )) +
  #
  
  xlab("Time [hrs]") +
  #ylab(expression(Relative~Particle~Spacing~'['*mu*m*']')) +
  ylab("") +
  #scale_y_continuous(limits = c(0,2.5), sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_continuous(breaks = c(1:4),
                     labels = c("5","10","50","150"),
                     sec.axis = sec_axis(~., breaks = c(1:4), labels = NULL)) +
  scale_y_continuous(limits = c(0,2.5), sec.axis = sec_axis(~., 
                                                            name = expression('Counts-Per-Area'~'['*cts*'/'*mu*m^2*']')
                                                            )
                     ) +
  #guides(color = FALSE) +
  guides(shape = FALSE) +
  theme_classic() +
  
  coord_cartesian(clip = "off") +
  annotation_custom(text_grob(line1, color = "purple", rot = 90, face = "bold", size = 12), 
                    xmin = -0.45, xmax = -0.45, ymin = 1.25, ymax = 1.25) +
  annotation_custom(text_grob(line2, color = "red", rot = 90, face = "bold" , size = 12),
                    xmin = -0.15, xmax = -0.15, ymin = 1.25, ymax = 1.25) +
  annotation_custom(text_grob(line3, color = "purple", rot = 90, face = "bold", size = 12), 
                    xmin = -0.45, xmax = -0.45, ymin = 3.85, ymax = 3.85) +
  annotation_custom(text_grob(line4, color = "red", rot = 90, face = "bold" , size = 12),
                    xmin = -0.15, xmax = -0.15, ymin = 3.85, ymax = 3.85) +
  
  theme(axis.text.x = element_text(colour = "black", size = 12),
        axis.text.y = element_text(colour = "black", size = 12),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 12),
        axis.title.y = element_text(colour = "black", size = 12),
        plot.margin = margin(180,10,10,45),
        legend.text = element_text(colour="black", size = 12)) +
  annotation_custom(ggplotGrob(inset.plot2),
                    xmin = -0.3,
                    xmax = 4.65,
                    ymin = 2.5,
                    ymax = 5)

{if(save == 1)ggsave(filename = "./paperexports/relspace-cts-hrs-extra2.png", plot = extra2, device = "png", width = 6,height = 6, units = "in")}
```

```{r}

tempdata <- filter(df_particles_fine, Label != "WH13A" & Labelfine != "WH35A/WH35A0010.tiff" & hrs == 5 & Area >= 0.005 & Ni.Vol.Corrected == 0.35)

line1 <- expression('Ave. Edge-to-Edge'~Distance~'['*mu*m*']')
line2 <- expression('Ave. Center-to-Center'~Distance~'['*mu*m*']')
line3 <- expression('Edge-to-Edge'~Distribution~'['*mu*m*']')
line4 <- expression('Center-to-Center'~Distribution~'['*mu*m*']')

inset.plot2 <- voronoidens %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(hrs == 5) %>%
  filter(Label != "WH13A") %>%
  filter(Label != "WH03A") %>%
  filter(magx == 10) %>%
  filter(Labelfine != "WH35A/WH35A0010.tiff") %>%
  group_by(Labelfine) %>%
  ggplot() +
  # geom_ridgeline(fill = "purple", aes(x = x, y = hrs2, 
  #                    #fill = as.factor(hrs),
  #                    #height = count/20000, 
  #                    height = density*0.35, #height is either density or count
  #                    group = Labelfine)) + 
  geom_ridgeline(fill = "purple", aes(x = x, y = Temp,
                     #fill = as.factor(hrs),
                     #height = count/20000,
                     min_height = -1000,
                     height = -density*0.35*100, #height is either density or count
                     group = Labelfine)) +
  
  geom_density_ridges(data = tempdata, fill = "red", scale = 0.35, rel_min_height = 0.01,
                      aes(x = nnd, y = Temp, group = Label)) +

  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(breaks = c(700,800,900,1000,1100),
                     labels = c(700,800,900,1000,1100),
                     sec.axis = sec_axis(~., breaks = c(700,800,900,1000), labels = NULL)) +
  #scale_fill_manual(values=c("#00BF7D", "#BF7D00", "#7C00BF", "#BF0041")) +
  #
  ylab("") +
  xlab("") +
  theme_classic() +
  coord_flip(clip = "off") +
  guides(color = FALSE, fill = guide_legend(reverse = TRUE, title = "Time [hrs]", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  theme(axis.text.x = element_text(colour = "black", size = 12),
        axis.text.y = element_text(colour = "black", size = 12),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        #axis.line = element_line(colour='transparent'),
        axis.title.x = element_text(colour = "black", size = 12),
        axis.title.y = element_text(colour = "black", size = 12),
        panel.background = element_rect(fill='transparent'),
        plot.background = element_rect(fill='transparent', color=NA),
        legend.text = element_text(colour="black", size = 12))

extra2 <- voronoidens %>%
  select(Label, Labelfine, Ni.Vol.Corrected, Temp, hrs, Th.Density,
         stressf, condAve, fineavennd, countperarea,
         avevoronoix, voronoicount, magx) %>%
  unique() %>%
  #
  mutate(hrs = as.double(hrs)) %>%
  mutate(hrs2 = hrs) %>%
  mutate(hrs2 = if_else(hrs == 5, replace(hrs, hrs == 5, 1), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 10, replace(hrs, hrs == 10, 2), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 50, replace(hrs, hrs == 50, 3), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 150, replace(hrs, hrs == 150, 4), hrs2)) %>%
  #
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(hrs == 5) %>%
  filter(Label != "WH13A") %>%
  filter(Label != "WH03A") %>%
  filter(magx == 10) %>%
  filter(Labelfine != "WH35A/WH35A0010.tiff") %>%
  #
  ggplot() +
  #
  geom_boxplot(color = "red", width = 25, aes(group = Temp, x = Temp, y = fineavennd)) +
  geom_point(size = 2, shape = 15, color = "red", aes(x = Temp, y = fineavennd, #color = as.factor(Ni.Vol.Corrected)
                                         )) +
  #
  geom_boxplot(color = "purple", width = 25, aes(group = Temp, x = Temp, y = avevoronoix)) +
  geom_point(size = 2, shape = 19, color = "purple", aes(y = avevoronoix, x = Temp, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 #color = as.factor(Ni.Vol.Corrected)
                 )) +
  #
  geom_boxplot(color = "transparent", aes(group = Temp, x = Temp, y = countperarea)) +
  geom_boxplot(color = "black", width = 25, aes(group = Temp, x = Temp, y = countperarea)) +
  geom_point(size = 2, shape = 17, color = "black", aes(y = countperarea, x = Temp, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 #color = as.factor(Ni.Vol.Corrected)
                 )) +
  #
  
  xlab(expression(Sintering~Temperature~'['*degree*C*']')) +
  #ylab(expression(Relative~Particle~Spacing~'['*mu*m*']')) +
  ylab("") +
  #scale_y_continuous(limits = c(0,2.5), sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_continuous(breaks = c(700,800,900,1000,1100),
                     labels = c(700,800,900,1000,1100),
                     sec.axis = sec_axis(~., breaks = c(700,800,900,1000), labels = NULL)) +
  scale_y_continuous(limits = c(0,2.5), sec.axis = sec_axis(~., 
                                                            name = expression('Counts-Per-Area'~'['*cts*'/'*mu*m^2*']')
                                                            )
                     ) +
  #guides(color = FALSE) +
  guides(shape = FALSE) +
  theme_classic() +
  
  coord_cartesian(clip = "off") +
  annotation_custom(text_grob(line1, color = "purple", rot = 90, face = "bold", size = 12), 
                    xmin = 530, xmax = 530, ymin = 1.25, ymax = 1.25) +
  annotation_custom(text_grob(line2, color = "red", rot = 90, face = "bold" , size = 12),
                    xmin = 565, xmax = 565, ymin = 1.25, ymax = 1.25) +
  annotation_custom(text_grob(line3, color = "purple", rot = 90, face = "bold", size = 12), 
                    xmin = 530, xmax = 530, ymin = 3.85, ymax = 3.85) +
  annotation_custom(text_grob(line4, color = "red", rot = 90, face = "bold" , size = 12),
                    xmin = 565, xmax = 565, ymin = 3.85, ymax = 3.85) +
  
  theme(axis.text.x = element_text(colour = "black", size = 12),
        axis.text.y = element_text(colour = "black", size = 12),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 12),
        axis.title.y = element_text(colour = "black", size = 12),
        plot.margin = margin(180,10,10,45),
        legend.text = element_text(colour="black", size = 12)) +
  annotation_custom(ggplotGrob(inset.plot2),
                    xmin = 555,
                    xmax = 1175,
                    ymin = 2.5,
                    ymax = 5)

{if(save == 1)ggsave(filename = "./paperexports/relspace-cts-Temp-extra2.png", plot = extra2, device = "png", width = 6,height = 6, units = "in")}
```

```{r}
nudge <- 8

dens.space.Temp <- voronoidens %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(hrs == 5) %>%
  filter(Label != "WH13A") %>%
  filter(Label != "WH03A") %>%
  filter(magx == 10) %>%
  filter(Labelfine != "WH35A/WH35A0010.tiff") %>%
  group_by(Labelfine) %>%
  ggplot() +
  # geom_ridgeline(fill = "purple", aes(x = x, y = hrs2, 
  #                    #fill = as.factor(hrs),
  #                    #height = count/20000, 
  #                    height = density*0.35, #height is either density or count
  #                    group = Labelfine)) + 
  geom_ridgeline(fill = "purple", aes(x = x, y = Temp,
                     #fill = as.factor(hrs),
                     #height = count/20000,
                     min_height = -1000,
                     height = -density*0.35*100, #height is either density or count
                     group = Labelfine)) +
  
  geom_density_ridges(data = tempdata, fill = "red", scale = 0.35, rel_min_height = 0.01,
                      aes(x = nnd, y = Temp, group = Label)) +

  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(breaks = c(700,800,900,1000,1100),
                     labels = c(700,800,900,1000,1100),
                     sec.axis = sec_axis(~., breaks = c(700,800,900,1000), labels = NULL)) +
  #
  geom_boxplot(color = "black", fill = "purple", width = 12, aes(group = Temp, y = Temp-nudge, x = avevoronoix)) +
  geom_point(size = 1, shape = 21, fill = "purple", aes(x = avevoronoix, y = Temp-nudge, 
                 #size = as.factor(hrs),
                 #shape = as.factor(Temp),
                 #color = as.factor(Ni.Vol.Corrected)
                 )) +
  geom_boxplot(color = "black", fill = "red", width = 12, aes(group = Temp, y = Temp+nudge, x = fineavennd)) +
  geom_point(size = 1, shape = 22, fill = "red", aes(y = Temp+nudge, x = fineavennd)) +
  #
  
  #scale_fill_manual(values=c("#00BF7D", "#BF7D00", "#7C00BF", "#BF0041")) +
  #
  ylab(expression(Sintering~Temperature~'['*degree*C*']')) +
  xlab("") +
  theme_classic() +
  coord_flip(clip = "off") +
  annotation_custom(text_grob(line1, color = "purple", rot = 90, face = "bold", size = 16), 
                    ymin = 530, ymax = 530, xmin = 0.75, xmax = 1.25) +
  annotation_custom(text_grob(line2, color = "red", rot = 90, face = "bold" , size = 16),
                    ymin = 565, ymax = 565, xmin = 0.5, xmax = 1.25) +
  guides(color = "none", fill = guide_legend(reverse = TRUE, title = "Time [hrs]", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        plot.margin = margin(10,10,10,45),
        legend.text = element_text(colour="black", size = 12))

print(dens.space.Temp)
{if(save == 1)ggsave(filename = "./paperexports/dens_space-cts-Temp.png", plot = dens.space.Temp, 
    device = "png", width = 6,height = 4, units = "in")}
rm(dens.space.Temp)
```



```{r}

tempdata.ni <- filter(df_particles_fine, Temp == 900 & Label != "WH13A" & Labelfine != "WH35A/WH35A0010.tiff" & Label != "WH15B" & hrs == 5 & Area >= 0.005) %>%
  mutate(Ni.Vol.Corrected2 = Ni.Vol.Corrected) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.05,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.05, 1), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.10,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.10, 2), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.20,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.20, 3), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.24,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.24, 4), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.28,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.28, 5), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.35,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.35, 6), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.40,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.40, 7), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.50,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.50, 8), Ni.Vol.Corrected2))

line1 <- expression('Ave. Edge-to-Edge'~Distance~'['*mu*m*']')
line2 <- expression('Ave. Center-to-Center'~Distance~'['*mu*m*']')
line3 <- expression('Edge-to-Edge'~Distribution~'['*mu*m*']')
line4 <- expression('Center-to-Center'~Distribution~'['*mu*m*']')

inset.plot.ni <- voronoidens %>%
  mutate(Ni.Vol.Corrected2 = Ni.Vol.Corrected) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.05,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.05, 1), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.10,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.10, 2), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.20,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.20, 3), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.24,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.24, 4), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.28,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.28, 5), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.35,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.35, 6), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.40,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.40, 7), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.50,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.50, 8), Ni.Vol.Corrected2)) %>%
  filter(Temp == 900) %>%
  filter(hrs == 5) %>%
  filter(Label != "WH13A") %>%
  filter(Labelfine != "WH15B/900-5-50B0008.tiff") %>%
  filter(Label != "WH03A") %>%
  filter(magx == 10) %>%
  filter(Labelfine != "WH35A/WH35A0010.tiff") %>%
  group_by(Labelfine) %>%
  ggplot() +
  # geom_ridgeline(fill = "purple", aes(x = x, y = hrs2, 
  #                    #fill = as.factor(hrs),
  #                    #height = count/20000, 
  #                    height = density*0.35, #height is either density or count
  #                    group = Labelfine)) + 
  geom_ridgeline(fill = "purple", aes(x = x, y = Ni.Vol.Corrected2,
                     #fill = as.factor(hrs),
                     #height = count/20000,
                     min_height = -1000,
                     height = -density*0.35, #height is either density or count
                     group = Labelfine)) +
  
  geom_density_ridges(data = tempdata.ni, fill = "red", scale = 0.35, rel_min_height = 0.01,
                      aes(x = nnd, y = Ni.Vol.Corrected2, group = Label)) +

  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(breaks = c(1:8),
                     labels = c("0.05", "0.10", "0.20", "0.24", "0.28", "0.35", "0.40", "0.50"),
                     sec.axis = sec_axis(~., breaks = c(1:8), labels = NULL)) +
  #scale_fill_manual(values=c("#00BF7D", "#BF7D00", "#7C00BF", "#BF0041")) +
  #
  ylab("") +
  xlab("") +
  theme_classic() +
  coord_flip(clip = "off") +
  guides(color = FALSE, fill = guide_legend(reverse = TRUE, title = "Ni", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  theme(axis.text.x = element_text(colour = "black", size = 12),
        axis.text.y = element_text(colour = "black", size = 12),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        #axis.line = element_line(colour='transparent'),
        axis.title.x = element_text(colour = "black", size = 12),
        axis.title.y = element_text(colour = "black", size = 12),
        panel.background = element_rect(fill='transparent'),
        plot.background = element_rect(fill='transparent', color=NA),
        legend.text = element_text(colour="black", size = 12))

extra.ni <- voronoidens %>%
  select(Label, Labelfine, Ni.Vol.Corrected, Temp, hrs, Th.Density,
         stressf, condAve, fineavennd, countperarea,
         avevoronoix, voronoicount, magx) %>%
  unique() %>%
  #
  mutate(Ni.Vol.Corrected2 = Ni.Vol.Corrected) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.05,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.05, 1), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.10,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.10, 2), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.20,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.20, 3), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.24,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.24, 4), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.28,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.28, 5), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.35,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.35, 6), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.40,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.40, 7), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.50,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.50, 8), Ni.Vol.Corrected2)) %>%
  #
  filter(Temp == 900) %>%
  filter(hrs == 5) %>%
  filter(Label != "WH13A") %>%
  filter(Labelfine != "WH15B/900-5-50B0008.tiff") %>%
  filter(Label != "WH03A") %>%
  filter(magx == 10) %>%
  filter(Labelfine != "WH35A/WH35A0010.tiff") %>%
  #
  ggplot() +
  #
  geom_boxplot(color = "red", width = 0.25, aes(group = Ni.Vol.Corrected2, x = Ni.Vol.Corrected2, y = fineavennd)) +
  geom_point(size = 2, shape = 15, color = "red", aes(x = Ni.Vol.Corrected2, y = fineavennd, #color = as.factor(Ni.Vol.Corrected)
                                         )) +
  #
  geom_boxplot(color = "purple", width = 0.25, aes(group = Ni.Vol.Corrected2, x = Ni.Vol.Corrected2, y = avevoronoix)) +
  geom_point(size = 2, shape = 19, color = "purple", aes(y = avevoronoix, x = Ni.Vol.Corrected2, 
                 #size = as.factor(hrs),
                 #shape = as.factor(Temp),
                 #color = as.factor(Ni.Vol.Corrected)
                 )) +
  #
  geom_boxplot(color = "transparent", aes(group = Ni.Vol.Corrected2, x = Ni.Vol.Corrected2, y = countperarea)) +
  geom_boxplot(color = "black", width = 0.25, aes(group = Ni.Vol.Corrected2, x = Ni.Vol.Corrected2, y = countperarea)) +
  geom_point(size = 2, shape = 17, color = "black", aes(y = countperarea, x = Ni.Vol.Corrected2, 
                 #size = as.factor(hrs),
                 #shape = as.factor(Temp),
                 #color = as.factor(Ni.Vol.Corrected)
                 )) +
  #
  
  xlab("Nickel Volume Fraction") +
  #ylab(expression(Relative~Particle~Spacing~'['*mu*m*']')) +
  ylab("") +
  #scale_y_continuous(limits = c(0,2.5), sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_continuous(breaks = c(1:8),
                     labels = c("0.05", "0.10", "0.20", "0.24", "0.28", "0.35", "0.40", "0.50"),
                     sec.axis = sec_axis(~., breaks = c(1:8), labels = NULL)) +
  scale_y_continuous(limits = c(0,2.5), sec.axis = sec_axis(~., 
                                                            name = expression('Counts-Per-Area'~'['*cts*'/'*mu*m^2*']')
                                                            )
                     ) +
  #guides(color = FALSE) +
  guides(shape = FALSE) +
  theme_classic() +
  
  coord_cartesian(clip = "off") +
  annotation_custom(text_grob(line1, color = "purple", rot = 90, face = "bold", size = 12), 
                    xmin = -1.4, xmax = -1.4, ymin = 1.25, ymax = 1.25) +
  annotation_custom(text_grob(line2, color = "red", rot = 90, face = "bold" , size = 12),
                    xmin = -0.8, xmax = -0.8, ymin = 1.25, ymax = 1.25) +
  annotation_custom(text_grob(line3, color = "purple", rot = 90, face = "bold", size = 12), 
                    xmin = -1.4, xmax = -1.4, ymin = 3.85, ymax = 3.85) +
  annotation_custom(text_grob(line4, color = "red", rot = 90, face = "bold" , size = 12),
                    xmin = -0.8, xmax = -0.8, ymin = 3.85, ymax = 3.85) +
  
  theme(axis.text.x = element_text(colour = "black", size = 12),
        axis.text.y = element_text(colour = "black", size = 12),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 12),
        axis.title.y = element_text(colour = "black", size = 12),
        plot.margin = margin(180,10,10,45),
        legend.text = element_text(colour="black", size = 12)) +
  annotation_custom(ggplotGrob(inset.plot.ni),
                    xmin = -0.9,
                    xmax = 8.9,
                    ymin = 2.5,
                    ymax = 5)

#print(extra.ni)
{if(save == 1)ggsave(filename = "./paperexports/relspace-cts-Ni-extra2.png", plot = extra.ni, device = "png", width = 6,height = 6, units = "in")}
```

```{r}
nudge <- 0.1

dens.space.ni <- voronoidens %>%
  mutate(Ni.Vol.Corrected2 = Ni.Vol.Corrected) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.05,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.05, 1), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.10,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.10, 2), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.20,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.20, 3), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.24,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.24, 4), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.28,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.28, 5), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.35,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.35, 6), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.40,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.40, 7), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.50,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.50, 8), Ni.Vol.Corrected2)) %>%
  filter(Temp == 900) %>%
  filter(hrs == 5) %>%
  filter(Label != "WH13A") %>%
  filter(Labelfine != "WH15B/900-5-50B0008.tiff") %>%
  filter(Label != "WH03A") %>%
  filter(magx == 10) %>%
  filter(Labelfine != "WH35A/WH35A0010.tiff") %>%
  group_by(Labelfine) %>%
  ggplot() +
  # geom_ridgeline(fill = "purple", aes(x = x, y = hrs2, 
  #                    #fill = as.factor(hrs),
  #                    #height = count/20000, 
  #                    height = density*0.35, #height is either density or count
  #                    group = Labelfine)) + 
  geom_ridgeline(fill = "purple", aes(x = x, y = Ni.Vol.Corrected2,
                     #fill = as.factor(hrs),
                     #height = count/20000,
                     min_height = -1000,
                     height = -density*0.35, #height is either density or count
                     group = Labelfine)) +
  
  geom_density_ridges(data = tempdata.ni, fill = "red", scale = 0.35, rel_min_height = 0.01,
                      aes(x = nnd, y = Ni.Vol.Corrected2, group = Label)) +
  #
  geom_boxplot(color = "black", fill = "purple", width = 0.1, aes(group = Ni.Vol.Corrected, y = Ni.Vol.Corrected2-nudge, x = avevoronoix)) +
  geom_point(size = 1, shape = 21, fill = "purple", aes(x = avevoronoix, y = Ni.Vol.Corrected2-nudge, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 #color = as.factor(Ni.Vol.Corrected)
                 )) +
  geom_boxplot(color = "black", fill = "red", width = 0.1, aes(group = Ni.Vol.Corrected, y = Ni.Vol.Corrected2+nudge, x = fineavennd)) +
  geom_point(size = 1, shape = 22, fill = "red", aes(y = Ni.Vol.Corrected2+nudge, x = fineavennd)) +
  #
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(breaks = c(1:8),
                     labels = c("0.05", "0.10", "0.20", "0.24", "0.28", "0.35", "0.40", "0.50"),
                     sec.axis = sec_axis(~., breaks = c(1:8), labels = NULL)) +
  #scale_fill_manual(values=c("#00BF7D", "#BF7D00", "#7C00BF", "#BF0041")) +
  #
  ylab("Nickel Volume Fraction") +
  xlab("") +
  theme_classic() +
  coord_flip(clip = "off") +
  annotation_custom(text_grob(line1, color = "purple", rot = 90, face = "bold", size = 16),
                    xmin = 0, xmax = 0, ymin = -2.2, ymax = 1) +
  annotation_custom(text_grob(line2, color = "red", rot = 90, face = "bold" , size = 16),
                    xmin = 0, xmax = 0, ymin = -1.6, ymax = 1) +
  guides(color = "none", fill = guide_legend(reverse = TRUE, title = "Time [hrs]", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        plot.margin = margin(10,10,10,45),
        legend.text = element_text(colour="black", size = 12))

print(dens.space.ni)
{if(save == 1)ggsave(filename = "./paperexports/dens_space-cts-ni.png", plot = dens.space.ni, 
    device = "png", width = 6,height = 4, units = "in")}
rm(dens.space.ni)
```

