---
title: "LTO-Ni-R3-PCA"
author: "whh36"
date: "8/17/2020"
output: html_document
---

```{r setup, include=FALSE}
#SETUP OF LIBRARIES
knitr::opts_chunk$set(echo = FALSE, warning=TRUE, message=TRUE) #set echo to FALSE to hide code
library(viridis)
library(wesanderson)
library(scico)
library(paletteer)

save <- 0
```



<!--
# PCA on slices of sample matrix


```{r}
prcomp.R3 <- r3densities %>%
  mutate(Label = substr(Labelfine, 1, 5)) %>%
  left_join(., fractSum, by = "Label") %>%
  #
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(hrs == 5) %>%
  #
  filter(Label != "WH13A") %>% #weird outlier
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  #
  select(x, density, Labelfine) %>%
  mutate(x = round(x, digits = 3)) %>%
  spread(., key = x, value = density) %>%
  select(-Labelfine) %>%
  prcomp(scale = TRUE)

fviz_eig(prcomp.R3, addlabels = TRUE)

#fviz_pca_ind(prcomp.R3, col.ind = "contrib", gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), repel = TRUE)

loadingplot(prcomp.R3, comps = 1:3, legendpos = "right", labels = 'numbers', pretty.xlabels = TRUE, #xlab = 'Time (s)',
            ylab = 'Loading Value')

prcomp.R3.fractSum <- df_particles_fine %>%
  #same filters as used for PCA BIG BIG BIG THIS IS WHERE I WILL GO WRONG
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(hrs == 5) %>%
  #
  filter(Label != "WH13A") %>% #weird outlier
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  #
  select(Labelfine) %>%
  unique() %>%
  mutate(Label = substr(Labelfine, 1, 5)) %>%
  left_join(., fractSum, by = "Label")


prcomp.R3.fractSum$Temp <- as.factor(prcomp.R3.fractSum$Temp)

autoplot(prcomp.R3, data = prcomp.R3.fractSum,
         colour = "Temp",
         label = TRUE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  theme_classic()

#fviz_contrib(prcomp.R3, choice = "var", axes = 1)
#fviz_contrib(prcomp.R3, choice = "var", axes = 2)

autoplot(prcomp.R3, 
         x = 2,
         y = 3,
         data = prcomp.R3.fractSum,
         colour = "Temp",
         label = TRUE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  theme_classic()

autoplot(prcomp.R3, 
         x = 1,
         y = 3,
         data = prcomp.R3.fractSum,
         colour = "Temp",
         label = TRUE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  theme_classic()
```



```{r}
prcomp.R3.pcsx <- data.frame()

prcomp.R3.pcsx <- as.data.frame(prcomp.R3$rotation) %>%
  rownames_to_column(var = "r3x") %>%
  slice(which.min(PC1)) %>%
  select(r3x) %>%
  rbind(prcomp.R3.pcsx, .)

prcomp.R3.pcsx <- as.data.frame(prcomp.R3$rotation) %>%
  rownames_to_column(var = "r3x") %>%
  filter(r3x > 0) %>%
  slice(which.max(PC1)) %>%
  select(r3x) %>%
  rbind(prcomp.R3.pcsx, .)

prcomp.R3.pcsx <- as.data.frame(prcomp.R3$rotation) %>%
  rownames_to_column(var = "r3x") %>%
  slice(which.min(PC2)) %>%
  select(r3x) %>%
  rbind(prcomp.R3.pcsx, .)

prcomp.R3.pcsx <- as.data.frame(prcomp.R3$rotation) %>%
  rownames_to_column(var = "r3x") %>%
  slice(which.max(PC2)) %>%
  select(r3x) %>%
  rbind(prcomp.R3.pcsx, .)

prcomp.R3.pcsx <- as.data.frame(prcomp.R3$rotation) %>%
  rownames_to_column(var = "r3x") %>%
  filter(r3x > 0) %>%
  slice(which.min(PC3)) %>%
  select(r3x) %>%
  rbind(prcomp.R3.pcsx, .)

prcomp.R3.pcsx <- as.data.frame(prcomp.R3$rotation) %>%
  rownames_to_column(var = "r3x") %>%
  filter(r3x < 0) %>%
  slice(which.max(PC3)) %>%
  select(r3x) %>%
  rbind(prcomp.R3.pcsx, .)


df_particles %>%
  filter(Label != "WH19A") %>%
  mutate(Label = substr(Label,0,4)) %>%
  #
  group_by(Label) %>%
  mutate(rstar = R3/mean(R3)) %>%
  #
  filter(Label != "WH15B") %>%
  filter(Area >= 0.005) %>%
  filter(hrs == 5) %>%
  filter(Label != "WH19") %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  ggplot() +
  geom_density_ridges(size = 1, aes(x = R3, y = Temp, group = Temp, 
                                    #color = black,
                                    fill = as.factor(Temp))) +
  #
  geom_vline(xintercept = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[1], 
             color = "black", linetype = "dashed") +
  geom_vline(xintercept = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[2], color = "black") +
  geom_vline(xintercept = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[3], 
             color = "red", linetype = "dashed") +
  geom_vline(xintercept = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[4], color = "red") +
  geom_vline(xintercept = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[5], 
             color = "green", linetype = "dashed") +
  geom_vline(xintercept = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[6], color = "green") +
  #
  annotate("text", x = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[1], 
             y = 1250, fontface = 1, label = paste("PC1 ", round(10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[1],2))) +
  annotate("text", x = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[2], 
             y = 1200, fontface = 1, label = paste("PC1 ", round(10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[2],2))) +
  annotate("text", x = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[3], 
             y = 1150, fontface = 1, label = paste("PC2 ", round(10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[3],2))) +
  annotate("text", x = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[4], 
             y = 1100, fontface = 1, label = paste("PC2 ", round(10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[4],2))) +
  annotate("text", x = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[5], 
             y = 1050, fontface = 1, label = paste("PC3 ", round(10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[5],2))) +
  annotate("text", x = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[6], 
             y = 1000, fontface = 1, label = paste("PC3 ", round(10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[6],2))) +
  
  #
  scale_x_log10(sec.axis = sec_axis(~.^(1/3)*2, name = expression(D~'['*mu*m*']')),
                limits = c(0.0001, 10000),
                breaks = scales::trans_breaks("log10", function(x) 10^x),
                labels = trans_format("log10", math_format(10^.x))) +
  scale_y_continuous(breaks = c(700,800,900,1000,1100),
                     sec.axis = sec_axis(~., labels = NULL)) +
  
  #geom_hline(yintercept = 0, color = "White", size = 1.5) +
  theme_classic() +


  ylab("") +
  xlab(expression(R^3~'['*mu*m^3*']')) +
  #annotation_logticks(sides = "b") +
  guides(color = FALSE, fill = guide_legend(reverse = TRUE, title = expression(Temp~'['*degree*C*']'), 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))
```

```{r}
prcomp.R3.Var = get_pca_ind(prcomp.R3)

prcomp.R3.Contrib = prcomp.R3.Var$contrib
prcomp.R3.Coord = as.data.frame(prcomp.R3.Var$coord)

prcomp.R3.Coord <- cbind(prcomp.R3.Coord, prcomp.R3.fractSum)

plot_ly(x = prcomp.R3.Coord$Dim.1, y = prcomp.R3.Coord$Dim.2, z = prcomp.R3.Coord$Dim.3, 
        color = prcomp.R3.Coord$Temp,
        colors = hue_pal()(5),
        type = 'scatter3d') %>%
  layout(title = 'PCs 1,2,3',
         scene = list(
           xaxis = list(title = "PC1"),
           yaxis = list(title = "PC2"),
           zaxis = list(title = "PC3")
         ))

plot_ly(x = prcomp.R3.Coord$Dim.1, y = prcomp.R3.Coord$Dim.2, z = prcomp.R3.Coord$Dim.4, 
        color = prcomp.R3.Coord$Temp,
        colors = hue_pal()(5),
        type = 'scatter3d') %>%
  layout(title = 'PCs 1,2,4',
         scene = list(
           xaxis = list(title = "PC1"),
           yaxis = list(title = "PC2"),
           zaxis = list(title = "PC4")
         ))

#plot3d(x = prcomp.R3.Coord$Dim.1, y = prcomp.R3.Coord$Dim.2, z = prcomp.R3.Coord$Dim.3)
#text3d(x = prcomp.R3.Coord$Dim.1, y = prcomp.R3.Coord$Dim.2, z = prcomp.R3.Coord$Dim.3, texts= rownames(prcomp.R3.Coord), col=4)

```


```{r}
#Comparison of R3 distributions for 1000C-5hrs-35Ni images used in PCA of R3 values

nine %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(hrs == 5) %>%
  filter(Temp == 1000) %>% #Temperature of interest
  filter(Area >= 0.005) %>% #Noise reduction
  #
  #select(Labelfine) %>%
  #unique()
  #
  group_by(Labelfine) %>%
  #
  ggplot() +
  geom_density_ridges(size = 1, aes(x = R3, y = as.factor(Labelfine), group = Labelfine,
                                                 fill = as.factor(Label))) + 
  #
  geom_vline(xintercept = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[1], 
             color = "black", linetype = "dashed") +
  geom_vline(xintercept = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[2], color = "black") +
  geom_vline(xintercept = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[3], 
             color = "red", linetype = "dashed") +
  geom_vline(xintercept = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[4], color = "red") +
  geom_vline(xintercept = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[5], 
             color = "green", linetype = "dashed") +
  geom_vline(xintercept = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[6], color = "green") +
  #
  annotate("text", x = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[1], 
             y = 1, fontface = 1, label = paste("PC1 ", round(10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[1],2))) +
  annotate("text", x = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[2], 
             y = 2, fontface = 1, label = paste("PC1 ", round(10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[2],2))) +
  annotate("text", x = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[3], 
             y = 3, fontface = 1, label = paste("PC2 ", round(10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[3],2))) +
  annotate("text", x = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[4], 
             y = 4, fontface = 1, label = paste("PC2 ", round(10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[4],2))) +
  annotate("text", x = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[5], 
             y = 5, fontface = 1, label = paste("PC3 ", round(10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[5],2))) +
  annotate("text", x = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[6], 
             y = 6, fontface = 1, label = paste("PC3 ", round(10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[6],2))) +
  #
  scale_x_log10(sec.axis = sec_axis(~.^(1/3)*2, name = expression(D~'['*mu*m*']')),
                limits = c(0.0001, 10000),
                breaks = scales::trans_breaks("log10", function(x) 10^x),
                labels = trans_format("log10", math_format(10^.x))) +
  #scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  theme_classic() +
  guides(fill = FALSE, colour = guide_legend(title = "Mag. [x]", reverse = TRUE,
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour="black",
                                                          #face = "bold",
                                                          size = 12))) +
  ylab("") +
  xlab(expression(R^3~'['*mu*m^3*']')) +
  geom_hline(yintercept = 0, color = "White", size = 1.5) +
  #annotation_logticks() +
  #scale_fill_manual(values=c("#00BF7D", "#BF7D00", "#7C00BF", "#BF0041")) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))
```


```{r}
prcomp.R3.Ni <- r3densities %>%
  mutate(Label = substr(Labelfine, 1, 5)) %>%
  left_join(., fractSum, by = "Label") %>%
  #filter(Ni.Vol.Corrected == 0.35) %>%
  filter(Temp == 900) %>%
  filter(hrs == 5) %>%
  filter(Label != "WH13A") %>% #weird outlier
  select(x, density, Labelfine) %>%
  mutate(x = round(x, digits = 3)) %>%
  spread(., key = x, value = density) %>%
  select(-Labelfine) %>%
  prcomp(scale = TRUE)

fviz_eig(prcomp.R3.Ni, addlabels = TRUE)

loadingplot(prcomp.R3.Ni, comps = 1:3, legendpos = "right", labels = 'numbers', pretty.xlabels = TRUE, #xlab = 'Time (s)',
            ylab = 'Loading Value')

prcomp.R3.fractSum.Ni <- df_particles_fine %>%
  #same filters as used for PCA BIG BIG BIG THIS IS WHERE I WILL GO WRONG
  #filter(Ni.Vol.Corrected == 0.35) %>%
  filter(Temp == 900) %>%
  filter(hrs == 5) %>%
  #filter(Labelfine != "WH13A/LTO-35Ni0010.jpg") %>% #weird outlier
  select(Labelfine) %>%
  unique() %>%
  mutate(Label = substr(Labelfine, 1, 5)) %>%
  left_join(., fractSum, by = "Label") %>%
  filter(Label != "WH15B") %>%
  filter(Label != "WH13A")


prcomp.R3.fractSum.Ni$Ni.Vol.Corrected <- as.factor(prcomp.R3.fractSum.Ni$Ni.Vol.Corrected)

autoplot(prcomp.R3.Ni, data = prcomp.R3.fractSum.Ni,
         colour = "Ni.Vol.Corrected",
         label = FALSE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  theme_classic()

autoplot(prcomp.R3.Ni, data = prcomp.R3.fractSum.Ni,
         colour = "Ni.Vol.Corrected",
         label = FALSE, frame = TRUE) +
  scale_x_continuous(limits = c(-0.15,0.025), sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  theme_classic()

#fviz_contrib(prcomp.R3.Ni, choice = "var", axes = 1)
#fviz_contrib(prcomp.R3.Ni, choice = "var", axes = 2)
```

```{r}
prcomp.R3.pcsx.Ni <- data.frame()

prcomp.R3.pcsx.Ni <- as.data.frame(prcomp.R3.Ni$rotation) %>%
  rownames_to_column(var = "r3x") %>%
  slice(which.min(PC1)) %>%
  select(r3x) %>%
  rbind(prcomp.R3.pcsx.Ni, .)

prcomp.R3.pcsx.Ni <- as.data.frame(prcomp.R3.Ni$rotation) %>%
  rownames_to_column(var = "r3x") %>%
  filter(r3x > 0) %>%
  slice(which.max(PC1)) %>%
  select(r3x) %>%
  rbind(prcomp.R3.pcsx.Ni, .)

prcomp.R3.pcsx.Ni <- as.data.frame(prcomp.R3.Ni$rotation) %>%
  rownames_to_column(var = "r3x") %>%
  mutate(r3x = as.numeric(r3x)) %>%
  filter(r3x > -3) %>%
  filter(r3x < 1) %>%
  slice(which.min(PC2)) %>%
  select(r3x) %>%
  rbind(prcomp.R3.pcsx.Ni, .)

prcomp.R3.pcsx.Ni <- as.data.frame(prcomp.R3.Ni$rotation) %>%
  rownames_to_column(var = "r3x") %>%
  slice(which.max(PC2)) %>%
  select(r3x) %>%
  rbind(prcomp.R3.pcsx.Ni, .)

prcomp.R3.pcsx.Ni <- as.data.frame(prcomp.R3.Ni$rotation) %>%
  rownames_to_column(var = "r3x") %>%
  slice(which.min(PC3)) %>%
  select(r3x) %>%
  rbind(prcomp.R3.pcsx.Ni, .)

prcomp.R3.pcsx.Ni <- as.data.frame(prcomp.R3.Ni$rotation) %>%
  rownames_to_column(var = "r3x") %>%
  slice(which.max(PC3)) %>%
  select(r3x) %>%
  rbind(prcomp.R3.pcsx.Ni, .)


nifix <- function(z){
  if(z == 0.05) 1 else if(z == 0.1) 2 else if(z == 0.2) 3 else if(z == 0.24) 4 else if(z == 0.28) 5 else if(z == 0.35) 6 else if(z == 0.4) 7 else if(z == 0.5) 8
}

df_particles %>%
  mutate(Label = substr(Label,0,4)) %>%
  #
  group_by(Label) %>%
  mutate(rstar = R3/mean(R3)) %>%
  #
  mutate(ni2 = nifix(Ni.Vol.Corrected)) %>%
  #
  filter(Label != "WH15B") %>%
  filter(Area >= 0.005) %>%
  filter(Label != "WH19") %>%
  filter(Temp == 900) %>%
  filter(hrs == 5) %>%
  ggplot() +
  geom_density_ridges(size = 1, aes(x = R3, y = ni2-1, group = Ni.Vol.Corrected, 
                   fill = as.factor(Ni.Vol.Corrected))) + 
  #
  geom_vline(xintercept = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx.Ni))))[1], 
             color = "black", linetype = "dashed") +
  geom_vline(xintercept = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx.Ni))))[2], 
             color = "black") +
  geom_vline(xintercept = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx.Ni))))[3], 
             color = "red", linetype = "dashed") +
  geom_vline(xintercept = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx.Ni))))[4], 
             color = "red") +
  geom_vline(xintercept = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx.Ni))))[5], 
             color = "green", linetype = "dashed") +
  geom_vline(xintercept = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx.Ni))))[6], 
             color = "green") +
  #
  annotate("text", x = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx.Ni))))[1], 
             y = 9, fontface = 1, label = paste("PC1 ", round(10^as.numeric(c(t(as.vector(prcomp.R3.pcsx.Ni))))[1],2))) +
  annotate("text", x = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx.Ni))))[2], 
             y = 8, fontface = 1, label = paste("PC1 ", round(10^as.numeric(c(t(as.vector(prcomp.R3.pcsx.Ni))))[2],2))) +
  annotate("text", x = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx.Ni))))[3], 
             y = 7, fontface = 1, label = paste("PC2 ", round(10^as.numeric(c(t(as.vector(prcomp.R3.pcsx.Ni))))[3],2))) +
  annotate("text", x = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx.Ni))))[4], 
             y = 6, fontface = 1, label = paste("PC2 ", round(10^as.numeric(c(t(as.vector(prcomp.R3.pcsx.Ni))))[4],2))) +
  annotate("text", x = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx.Ni))))[5], 
             y = 5, fontface = 1, label = paste("PC3 ", round(10^as.numeric(c(t(as.vector(prcomp.R3.pcsx.Ni))))[5],2))) +
  annotate("text", x = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx.Ni))))[6], 
             y = 4, fontface = 1, label = paste("PC3 ", round(10^as.numeric(c(t(as.vector(prcomp.R3.pcsx.Ni))))[6],2))) +
  #
  scale_x_log10(sec.axis = sec_axis(~.^(1/3)*2, name = expression(D~'['*mu*m*']')),
                limits = c(0.0001, 10000),
                breaks = scales::trans_breaks("log10", function(x) 10^x),
                labels = trans_format("log10", math_format(10^.x))) +
  scale_y_continuous(breaks = c(0,1,2,3,4,5,6,7),
                     labels = c("0.05", "0.10", "0.20", "0.24", "0.28", "0.35", "0.40", "0.50"),
                     sec.axis = sec_axis(~., breaks = c(0,1,2,3,4,5,6,7), labels = NULL)) +
  #geom_hline(yintercept = 0, color = "White", size = 1.5) +
  theme_classic() +
  ylab("") +
  xlab(expression(R^3~'['*mu*m^3*']')) +
  #annotation_logticks(sides = "tb") +
  guides(colour = FALSE, fill = guide_legend(reverse = TRUE, title = "Ni Vol.", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))
```

```{r}
#cleanup

rm(prcomp.R3.fractSum)
rm(prcomp.R3.Var)
rm(prcomp.R3.Contrib)
rm(prcomp.R3.Coord)

rm(prcomp.R3)
rm(prcomp.R3.pcsx)

rm(prcomp.R3.fractSum.Ni)

rm(nifix)
rm(prcomp.R3.pcsx.Ni)
rm(prcomp.R3.Ni)
```

-->

<!--

# PCA on all samples for 5 and 10 hours

```{r}
#PCA on all samples together

prcomp.R3 <- r3densities %>%
  mutate(Label = substr(Labelfine, 1, 5)) %>%
  left_join(., fractSum, by = "Label") %>%
  filter(hrs != 50) %>%
  filter(hrs != 150) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Label != "WH21B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  #
  #filter(Labelfine != "WH32A/LTO-35Ni-900-50-A0002.tiff") %>%
  #filter(Labelfine != "WH31C/LTO28Ni900-50-C0004.tiff") %>%
  #filter(Labelfine != "WH31C/LTO28Ni900-50-C0006.tiff") %>%
  #
  select(x, density, Labelfine) %>%
  mutate(x = round(x, digits = 3)) %>%
  spread(., key = x, value = density) %>%
  select(-Labelfine) %>%
  prcomp(scale = TRUE)

fviz_eig(prcomp.R3, addlabels = TRUE)

#fviz_pca_ind(prcomp.R3, col.ind = "contrib", gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), repel = TRUE)

loadingplot(prcomp.R3, comps = 1:5, legendpos = "right", labels = 'numbers', pretty.xlabels = TRUE, #xlab = 'Time (s)',
            ylab = 'Loading Value')

prcomp.R3.fractSum <- df_particles_fine %>%
  #same filters as used for PCA BIG BIG BIG THIS IS WHERE I WILL GO WRONG
  filter(hrs != 50) %>%
  filter(hrs != 150) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Label != "WH21B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  #
  #filter(Labelfine != "WH32A/LTO-35Ni-900-50-A0002.tiff") %>%
  #filter(Labelfine != "WH31C/LTO28Ni900-50-C0004.tiff") %>%
  #filter(Labelfine != "WH31C/LTO28Ni900-50-C0006.tiff") %>%
  #
  select(Labelfine) %>%
  unique() %>%
  mutate(Label = substr(Labelfine, 1, 5)) %>%
  left_join(., fractSum, by = "Label")

prcomp.R3.fractSum$Temp <- as.factor(prcomp.R3.fractSum$Temp)
prcomp.R3.fractSum$hrs <- as.factor(prcomp.R3.fractSum$hrs)
prcomp.R3.fractSum$Ni.Vol.Corrected <- as.factor(prcomp.R3.fractSum$Ni.Vol.Corrected)




autoplot(prcomp.R3, data = prcomp.R3.fractSum,
         x = 1,
         y = 2,
         colour = "Temp",
         #shape = "hrs",
         label = FALSE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  geom_hline(yintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  geom_vline(xintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  {if(cb == 1)scale_fill_scico_d(palette = "batlow", direction = 1, begin = 0, end = 0.7)} +
  {if(cb == 1)scale_color_scico_d(palette = "batlow", direction = 1, begin = 0, end = 0.7)} +
  theme_classic()

autoplot(prcomp.R3, data = prcomp.R3.fractSum,
         x = 1,
         y = 2,
         colour = "hrs",
         label = FALSE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  geom_hline(yintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  geom_vline(xintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  {if(cb == 1)scale_fill_scico_d(palette = "lajolla", direction = 1, begin = 0.4, end = 1)} +
  {if(cb == 1)scale_color_scico_d(palette = "lajolla", direction = 1, begin = 0.4, end = 1)} +
  theme_classic()

autoplot(prcomp.R3, data = prcomp.R3.fractSum,
         x = 1,
         y = 2,
         colour = "Ni.Vol.Corrected",
         #shape = "hrs",
         label = FALSE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  geom_hline(yintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  geom_vline(xintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  {if(cb == 1)scale_fill_scico_d(palette = "roma", direction = 1)} +
  {if(cb == 1)scale_color_scico_d(palette = "roma", direction = 1)} +
  labs(colour = "Ni [%]") +
  labs(fill = "Ni [%]") +
  scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  theme_classic()



autoplot(prcomp.R3, 
         x = 1,
         y = 2,
         data = prcomp.R3.fractSum,
         colour = "Temp",
         shape = "hrs",
         label = FALSE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  {if(cb == 1)scale_fill_scico_d(palette = "batlow", direction = 1, begin = 0, end = 0.7)} +
  {if(cb == 1)scale_color_scico_d(palette = "batlow", direction = 1, begin = 0, end = 0.7)} +
  theme_classic()
```

-->









# PCA on all samples together

```{r}
#PCA on all samples together

prcomp.R3 <- r3densities %>%
  mutate(Label = substr(Labelfine, 1, 5)) %>%
  left_join(., fractSum, by = "Label") %>%
  #filter(Ni.Vol.Corrected == 0.35) %>%
  #filter(hrs == 5) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Label != "WH21B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  #
  #filter(Labelfine != "WH32A/LTO-35Ni-900-50-A0002.tiff") %>%
  #filter(Labelfine != "WH31C/LTO28Ni900-50-C0004.tiff") %>%
  #filter(Labelfine != "WH31C/LTO28Ni900-50-C0006.tiff") %>%
  #
  select(x, density, Labelfine) %>%
  mutate(x = round(x, digits = 3)) %>%
  spread(., key = x, value = density) %>%
  select(-Labelfine) %>%
  prcomp(scale = TRUE)


prcomp.R3.fractSum <- df_particles_fine %>%
  #same filters as used for PCA BIG BIG BIG THIS IS WHERE I WILL GO WRONG
  #filter(Ni.Vol.Corrected == 0.35) %>%
  #filter(hrs == 5) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Label != "WH21B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  #
  #filter(Labelfine != "WH32A/LTO-35Ni-900-50-A0002.tiff") %>%
  #filter(Labelfine != "WH31C/LTO28Ni900-50-C0004.tiff") %>%
  #filter(Labelfine != "WH31C/LTO28Ni900-50-C0006.tiff") %>%
  #
  select(Labelfine) %>%
  unique() %>%
  mutate(Label = substr(Labelfine, 1, 5)) %>%
  left_join(., fractSum, by = "Label")

prcomp.R3.fractSum$Temp <- as.factor(prcomp.R3.fractSum$Temp)
prcomp.R3.fractSum$hrs <- as.factor(prcomp.R3.fractSum$hrs)
prcomp.R3.fractSum$Ni.Vol.Corrected <- as.factor(prcomp.R3.fractSum$Ni.Vol.Corrected)
```


```{r}
PCAscree <- fviz_eig(prcomp.R3, addlabels = TRUE, barfill = "#00A9FF") +
  labs(title = "") +
  theme_classic() +
  scale_y_continuous(limits = c(0,37), expand = c(0,0), sec.axis = sec_axis(~., labels = NULL)) +
  geom_hline(yintercept = 37, size = 1)

print(PCAscree)
{if(save == 1)ggsave(filename = "./PCAexports/PCAscree.png", plot = PCAscree, 
         device = "png", width = 6,height = 4, units = "in")}
rm(PCAscree)



#fviz_pca_ind(prcomp.R3, col.ind = "contrib", gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), repel = TRUE)

#loadingplot(prcomp.R3, comps = 1:6, legendpos = "right", labels = 'numbers', 
#            pretty.xlabels = TRUE, xlab = expression(R^3~'['*mu*m^3*']'), ylab = 'Loading Value')

```

```{r}
scoresTemp <- autoplot(prcomp.R3, data = prcomp.R3.fractSum,
         x = 1,
         y = 2,
         colour = "Temp",
         #shape = "hrs",
         label = FALSE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  geom_hline(yintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  geom_vline(xintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  {if(cb == 1)scale_fill_scico_d(palette = "batlow", direction = 1, begin = 0, end = 0.7)} + #Temp
  {if(cb == 1)scale_color_scico_d(palette = "batlow", direction = 1, begin = 0, end = 0.7)} + #Temp
  theme_classic() +
  guides(fill = guide_legend(reverse = FALSE, title = expression(Temp~'['*degree*C*']'), 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10))) +
  guides(color = guide_legend(reverse = FALSE, title = expression(Temp~'['*degree*C*']'), 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10)))

print(scoresTemp)
{if(save == 1)ggsave(filename = "./PCAexports/scoresTemp.png", plot = scoresTemp, 
         device = "png", width = 6,height = 4, units = "in")}
rm(scoresTemp)

scoreshrs <- autoplot(prcomp.R3, data = prcomp.R3.fractSum,
         x = 1,
         y = 2,
         colour = "hrs",
         label = FALSE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  geom_hline(yintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  geom_vline(xintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  {if(cb == 1)scale_fill_scico_d(palette = "lajolla", direction = 1, begin = 0.4, end = 1)} + #hrs
  {if(cb == 1)scale_color_scico_d(palette = "lajolla", direction = 1, begin = 0.4, end = 1)} + #hrs
  theme_classic() +
  guides(fill = guide_legend(title = "Time [hrs]", reverse = TRUE,
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour="black",
                                                          #face = "bold",
                                                          size = 10))) +
  guides(color = guide_legend(title = "Time [hrs]", reverse = TRUE,
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour="black",
                                                          #face = "bold",
                                                          size = 10)))

print(scoreshrs)
{if(save == 1)ggsave(filename = "./PCAexports/scoreshrs.png", plot = scoreshrs, 
         device = "png", width = 6,height = 4, units = "in")}
rm(scoreshrs)


scoresNi <- autoplot(prcomp.R3, data = prcomp.R3.fractSum,
         x = 1,
         y = 2,
         colour = "Ni.Vol.Corrected",
         #shape = "hrs",
         label = FALSE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  geom_hline(yintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  geom_vline(xintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  {if(cb == 1)scale_fill_scico_d(palette = "roma", direction = 1)} + #nickel
  {if(cb == 1)scale_color_scico_d(palette = "roma", direction = 1)} + #nickel
  labs(colour = "Ni Vol.") +
  labs(fill = "Ni Vol.") +
  scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  theme_classic() +
  guides(fill = guide_legend(reverse = TRUE, title = "Ni Vol.", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10))) +
  guides(colour = guide_legend(reverse = TRUE, title = "Ni Vol.", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10)))

print(scoresNi)
{if(save == 1)ggsave(filename = "./PCAexports/scoresNi.png", plot = scoresNi, 
         device = "png", width = 6,height = 4, units = "in")}
rm(scoresNi)


scoresTemphrs <- autoplot(prcomp.R3, 
         x = 1,
         y = 2,
         data = prcomp.R3.fractSum,
         colour = "Temp",
         shape = "hrs",
         label = FALSE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  geom_hline(yintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  geom_vline(xintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  {if(cb == 1)scale_fill_scico_d(palette = "batlow", direction = 1, begin = 0, end = 0.7)} +
  {if(cb == 1)scale_color_scico_d(palette = "batlow", direction = 1, begin = 0, end = 0.7)} +
  theme_classic() +
  guides(shape = guide_legend(title = "Time [hrs]", reverse = TRUE,
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour="black",
                                                          #face = "bold",
                                                          size = 10))) +
  guides(fill = guide_legend(reverse = FALSE, title = expression(Temp~'['*degree*C*']'), 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10))) +
  guides(color = guide_legend(reverse = FALSE, title = expression(Temp~'['*degree*C*']'), 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10)))
print(scoresTemphrs)
{if(save == 1)ggsave(filename = "./PCAexports/scoresTemphrs.png", plot = scoresTemphrs, 
         device = "png", width = 6,height = 4, units = "in")}
rm(scoresTemphrs)
```

```{r}
scoresNiTemp <- autoplot(prcomp.R3, data = prcomp.R3.fractSum,
         x = 1,
         y = 2,
         colour = "Ni.Vol.Corrected",
         shape = "Temp",
         label = FALSE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  geom_hline(yintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  geom_vline(xintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  {if(cb == 1)scale_fill_scico_d(palette = "roma", direction = 1)} + #nickel
  {if(cb == 1)scale_color_scico_d(palette = "roma", direction = 1)} + #nickel
  labs(colour = "Ni Vol.") +
  labs(fill = "Ni Vol.") +
  scale_shape_manual(values=c(8, 17, 16, 0, 2)) + #Temp
  guides(shape = guide_legend(reverse = TRUE, title = expression(Temp~'['*degree*C*']'), 
                              title.theme = element_text(colour="black", 
                                                         size = 10))) +
  theme_classic() +
  guides(fill = guide_legend(reverse = TRUE, title = "Ni Vol.", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10))) +
  guides(colour = guide_legend(reverse = TRUE, title = "Ni Vol.", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10))) +
  labs(tag = "(b)") +
  theme(legend.key.height = unit(0.2, 'in')) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        plot.margin = margin(10,10,10,45),
        plot.tag = element_text(colour = "black", size = 18, face = "bold"),
        legend.text = element_text(colour="black", size = 12))

print(scoresNiTemp)
{if(save == 1)ggsave(filename = "./PCAexports/scoresNiTemp.png", plot = scoresNiTemp, 
         device = "png", width = 6,height = 4, units = "in")}
rm(scoresNiTemp)
```

```{r}
scoresTemp34 <- autoplot(prcomp.R3, 
         x = 3,
         y = 4,
         data = prcomp.R3.fractSum,
         colour = "Temp",
         shape = "hrs",
         label = FALSE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  geom_hline(yintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  geom_vline(xintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  {if(cb == 1)scale_fill_scico_d(palette = "batlow", direction = 1, begin = 0, end = 0.7)} +
  {if(cb == 1)scale_color_scico_d(palette = "batlow", direction = 1, begin = 0, end = 0.7)} +
  theme_classic() +
  guides(shape = guide_legend(title = "Time [hrs]", reverse = TRUE,
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour="black",
                                                          #face = "bold",
                                                          size = 10))) +
  guides(fill = guide_legend(reverse = FALSE, title = expression(Temp~'['*degree*C*']'), 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10))) +
  guides(color = guide_legend(reverse = FALSE, title = expression(Temp~'['*degree*C*']'), 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10)))

print(scoresTemp34)
{if(save == 1)ggsave(filename = "./PCAexports/scoresTemp34.png", plot = scoresTemp34, 
         device = "png", width = 6,height = 4, units = "in")}
rm(scoresTemp34)

scoreshrs34 <- autoplot(prcomp.R3, data = prcomp.R3.fractSum,
         x = 3,
         y = 4,
         colour = "hrs",
         label = FALSE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  geom_hline(yintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  geom_vline(xintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  {if(cb == 1)scale_fill_scico_d(palette = "lajolla", direction = 1, begin = 0.4, end = 1)} +
  {if(cb == 1)scale_color_scico_d(palette = "lajolla", direction = 1, begin = 0.4, end = 1)} +
  theme_classic() +
  guides(fill = guide_legend(title = "Time [hrs]", reverse = TRUE,
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour="black",
                                                          #face = "bold",
                                                          size = 10))) +
  guides(color = guide_legend(title = "Time [hrs]", reverse = TRUE,
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour="black",
                                                          #face = "bold",
                                                          size = 10)))

print(scoreshrs34)
{if(save == 1)ggsave(filename = "./PCAexports/scoreshrs34.png", plot = scoreshrs34, 
         device = "png", width = 6,height = 4, units = "in")}
rm(scoreshrs34)


scoresNi34 <- autoplot(prcomp.R3, data = prcomp.R3.fractSum,
         x = 3,
         y = 4,
         colour = "Ni.Vol.Corrected",
         #shape = "hrs",
         label = FALSE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  geom_hline(yintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  geom_vline(xintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  {if(cb == 1)scale_fill_scico_d(palette = "roma", direction = 1)} +
  {if(cb == 1)scale_color_scico_d(palette = "roma", direction = 1)} +
  labs(colour = "Ni Vol.") +
  labs(fill = "Ni Vol.") +
  scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  theme_classic() +
  guides(fill = guide_legend(reverse = TRUE, title = "Ni Vol.", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10))) +
  guides(colour = guide_legend(reverse = TRUE, title = "Ni Vol.", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10)))

print(scoresNi34)
{if(save == 1)ggsave(filename = "./PCAexports/scoresNi34.png", plot = scoresNi34, 
         device = "png", width = 6,height = 4, units = "in")}
rm(scoresNi34)
```

<!--
```{r}
autoplot(prcomp.R3, 
         x = 5,
         y = 6,
         data = prcomp.R3.fractSum,
         colour = "Temp",
         shape = "hrs",
         label = FALSE, frame = TRUE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  geom_hline(yintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  geom_vline(xintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  {if(cb == 1)scale_fill_scico_d(palette = "batlow", direction = 1, begin = 0, end = 0.7)} +
  {if(cb == 1)scale_color_scico_d(palette = "batlow", direction = 1, begin = 0, end = 0.7)} +
  theme_classic() +
  guides(shape = guide_legend(title = "Time [hrs]", reverse = TRUE,
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour="black",
                                                          #face = "bold",
                                                          size = 10))) +
  guides(fill = guide_legend(reverse = FALSE, title = expression(Temp~'['*degree*C*']'), 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10))) +
  guides(color = guide_legend(reverse = FALSE, title = expression(Temp~'['*degree*C*']'), 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10)))
```
-->


```{r}
prcomp.R3.rot <- prcomp.R3$rotation %>%
  as.data.frame() %>%
  rownames_to_column(var = "r3x") %>%
  mutate(r3x = as.numeric(r3x)) %>%
  filter(r3x >= -4) %>%
  filter(r3x <= 4) %>%
  select(1:11)
```

<!--
```{r}
prcomp.R3.pcsx <- data.frame()

prcomp.R3.pcsx <- as.data.frame(prcomp.R3$rotation) %>%
  rownames_to_column(var = "r3x") %>%
  slice(which.min(PC1)) %>%
  select(r3x) %>%
  rbind(prcomp.R3.pcsx, .)

prcomp.R3.pcsx <- as.data.frame(prcomp.R3$rotation) %>%
  rownames_to_column(var = "r3x") %>%
  filter(r3x > 0) %>%
  slice(which.max(PC1)) %>%
  select(r3x) %>%
  rbind(prcomp.R3.pcsx, .)

prcomp.R3.pcsx <- as.data.frame(prcomp.R3$rotation) %>%
  rownames_to_column(var = "r3x") %>%
  slice(which.min(PC2)) %>%
  select(r3x) %>%
  rbind(prcomp.R3.pcsx, .)

prcomp.R3.pcsx <- as.data.frame(prcomp.R3$rotation) %>%
  rownames_to_column(var = "r3x") %>%
  slice(which.max(PC2)) %>%
  select(r3x) %>%
  rbind(prcomp.R3.pcsx, .)

prcomp.R3.pcsx <- as.data.frame(prcomp.R3$rotation) %>%
  rownames_to_column(var = "r3x") %>%
  filter(r3x > 0) %>%
  slice(which.min(PC3)) %>%
  select(r3x) %>%
  rbind(prcomp.R3.pcsx, .)

prcomp.R3.pcsx <- as.data.frame(prcomp.R3$rotation) %>%
  rownames_to_column(var = "r3x") %>%
  filter(r3x < 0) %>%
  slice(which.max(PC3)) %>%
  select(r3x) %>%
  rbind(prcomp.R3.pcsx, .)

nifix <- function(z){
  if_else(z == 0.05, 1, 
        if_else(z == 0.1, 2, 
                if_else(z == 0.2, 3, 
                        if_else(z == 0.24, 4, 
                                if_else(z == 0.28, 5, 
                                        if_else(z == 0.35, 6,
                                                if_else(z == 0.4, 7, 
                                                        if_else(z == 0.5, 8, 0))))))))
}



df_particles_fine %>%
  filter(Label != "WH19A") %>%
  mutate(Label = substr(Label,0,4)) %>%
  #
  group_by(Label) %>%
  #
  filter(Label != "WH15B") %>%
  filter(Area >= 0.005) %>%
  filter(Label != "WH19") %>%
  mutate(ni2 = nifix(Ni.Vol.Corrected)) %>%
  ggplot() +
  geom_density_ridges(size = 1, aes(x = R3, y = ni2-1, group = Labelfine, 
                                    #color = black,
                                    fill = as.factor(Temp))) +
  #
  geom_vline(xintercept = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[1], 
             color = "black", linetype = "dashed") +
  geom_vline(xintercept = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[2], color = "black") +
  geom_vline(xintercept = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[3], 
             color = "red", linetype = "dashed") +
  geom_vline(xintercept = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[4], color = "red") +
  geom_vline(xintercept = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[5], 
             color = "green", linetype = "dashed") +
  geom_vline(xintercept = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[6], color = "green") +
  #
  # annotate("text", x = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[1], 
  #            y = 1250, fontface = 1, label = paste("PC1 ", round(10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[1],2))) +
  # annotate("text", x = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[2], 
  #            y = 1200, fontface = 1, label = paste("PC1 ", round(10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[2],2))) +
  # annotate("text", x = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[3], 
  #            y = 1150, fontface = 1, label = paste("PC2 ", round(10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[3],2))) +
  # annotate("text", x = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[4], 
  #            y = 1100, fontface = 1, label = paste("PC2 ", round(10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[4],2))) +
  # annotate("text", x = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[5], 
  #            y = 1050, fontface = 1, label = paste("PC3 ", round(10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[5],2))) +
  # annotate("text", x = 10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[6], 
  #            y = 1000, fontface = 1, label = paste("PC3 ", round(10^as.numeric(c(t(as.vector(prcomp.R3.pcsx))))[6],2))) +
  
  #
  scale_x_log10(sec.axis = sec_axis(~.^(1/3)*2, name = expression(D~'['*mu*m*']')),
                limits = c(0.0001, 10000),
                breaks = scales::trans_breaks("log10", function(x) 10^x),
                labels = trans_format("log10", math_format(10^.x))) +
  scale_y_continuous(breaks = c(0,1,2,3,4,5,6,7,9),
                     labels = c("0.05", "0.10", "0.20", "0.24", "0.28", "0.35", "0.40", "0.50", "PC"),
                     sec.axis = sec_axis(~., breaks = c(0,1,2,3,4,5,6,7,9), labels = NULL)) +
  #
  {if(cb == 1)scale_fill_scico_d(palette = "batlow", direction = 1, begin = 0, end = 0.7)} +
  #
  #geom_hline(yintercept = 0, color = "White", size = 1.5) +
  theme_classic() +


  ylab("") +
  xlab(expression(R^3~'['*mu*m^3*']')) +
  #annotation_logticks(sides = "b") +
  guides(color = FALSE, fill = guide_legend(reverse = TRUE, title = expression(Temp~'['*degree*C*']'), 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))
```
-->



```{r}
prcomp.R3.Var = get_pca_ind(prcomp.R3)

prcomp.R3.Contrib = prcomp.R3.Var$contrib

prcomp.R3.Coord = as.data.frame(prcomp.R3.Var$coord)

prcomp.R3.Results <- cbind(select(prcomp.R3.Coord, 1:6), prcomp.R3.fractSum)

#View(prcomp.R3.Results)
```

```{r}
prcomp.R3.Coord <- prcomp.R3.Coord %>%
  select(1:10)
  

prcomp.R3.Coord <- cbind(prcomp.R3.Coord, prcomp.R3.fractSum) %>%
  mutate(perc = if_else(condAve > 0.5,1,0)) %>%
  mutate(condAve = log(condAve)) %>%
  mutate(stresso = stressf*exp((1.05-Th.Density/100)*coef(fracmodel)[2]*-1))
```


<!--
```{r}
plot_ly(x = prcomp.R3.Coord$Dim.1, y = prcomp.R3.Coord$Dim.2, z = prcomp.R3.Coord$Dim.4, 
        color = prcomp.R3.Coord$Ni.Vol.Corrected,
        colors = hue_pal()(5),
        type = 'scatter3d') %>%
  layout(title = 'PCs 1,2,4',
         scene = list(
           xaxis = list(title = "PC1"),
           yaxis = list(title = "PC2"),
           zaxis = list(title = "PC4")
           ))

plot_ly(x = prcomp.R3.Coord$Dim.1, y = prcomp.R3.Coord$Dim.2, z = prcomp.R3.Coord$Dim.4, 
        color = prcomp.R3.Coord$Temp,
        colors = hue_pal()(5),
        type = 'scatter3d') %>%
  layout(title = 'PCs 1,2,4',
         scene = list(
           xaxis = list(title = "PC1"),
           yaxis = list(title = "PC2"),
           zaxis = list(title = "PC4")
           ))

plot_ly(x = prcomp.R3.Coord$Dim.1, y = prcomp.R3.Coord$Dim.2, z = prcomp.R3.Coord$Dim.4, 
        color = prcomp.R3.Coord$perc,
        colors = hue_pal()(2),
        type = 'scatter3d') %>%
  layout(title = 'PCs 1,2,4',
         scene = list(
           xaxis = list(title = "PC1"),
           yaxis = list(title = "PC2"),
           zaxis = list(title = "PC4")
           ))

plot_ly(x = prcomp.R3.Coord$Dim.1, y = prcomp.R3.Coord$Dim.3, z = prcomp.R3.Coord$Dim.4, 
        color = prcomp.R3.Coord$condAve,
        colors = hue_pal()(5),
        type = 'scatter3d') %>%
  layout(title = 'PCs 1,3,4 Conductivity',
         scene = list(
           xaxis = list(title = "PC1"),
           yaxis = list(title = "PC3"),
           zaxis = list(title = "PC4")
           ))

plot_ly(x = prcomp.R3.Coord$Dim.1, y = prcomp.R3.Coord$Dim.3, z = prcomp.R3.Coord$Dim.2, 
        color = prcomp.R3.Coord$stressf,
        colors = hue_pal()(5),
        type = 'scatter3d') %>%
  layout(title = 'PCs 1,3,2 Stress',
         scene = list(
           xaxis = list(title = "PC1"),
           yaxis = list(title = "PC3"),
           zaxis = list(title = "PC4")
           ))
```
-->


```{r}
prcomp.R3.rot %>%
  select(-1) %>%
  max()
prcomp.R3.rot %>%
  select(-1) %>%
  min()

PCfilm <- prcomp.R3.rot %>%
  mutate(r3x = 10^r3x) %>%
  #
  ggplot() +
  geom_tile(aes(x = r3x, y = 1, width = 0.025, height = 0.2, fill = PC1)) +
  geom_tile(aes(x = r3x, y = 2, width = 0.025, height = 0.2, fill = PC2)) +
  geom_tile(aes(x = r3x, y = 3, width = 0.025, height = 0.2, fill = PC3)) +
  geom_tile(aes(x = r3x, y = 4, width = 0.025, height = 0.2, fill = PC4)) +
  #geom_tile(aes(x = r3x, y = 5, width = 0.025, height = 0.2, fill = PC5)) +
  #geom_tile(aes(x = r3x, y = 6, width = 0.025, height = 0.2, fill = PC6)) +
  #
  scale_fill_scico(palette = "roma", limits = c(-0.15,0.15), direction = -1) +
  #scale_fill_gradientn(colors = brewer_pal(palette = "RdBu")(5), limits = c(-0.15,0.15)) +
  scale_x_log10(sec.axis = sec_axis(~.^(1/3)*2, name = expression(D~'['*mu*m*']')),
                limits = c(0.0001, 10000),
                breaks = scales::trans_breaks("log10", function(x) 10^x),
                labels = trans_format("log10", math_format(10^.x))) +
  scale_y_continuous(breaks = c(1,2,3,4,5,6),sec.axis = sec_axis(~., labels = NULL)) +
  ylab("Principal Component") +
  xlab(expression(R^3~'['*mu*m^3*']')) +
  labs(fill = "Loading") +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.title = element_text(colour = "black", size = 12),
        legend.text = element_text(colour="black", size = 12))

print(PCfilm)
{if(save == 1)ggsave(filename = "./PCAexports/PCfilm.png", plot = PCfilm, 
         device = "png", width = 6,height = 4, units = "in")}
rm(PCfilm)

#uncomment below code to generate and save PC loading - R3 Distribution Plots
```



```{r}
nifix <- function(z){
  if_else(z == 0.05, 1, 
        if_else(z == 0.1, 2, 
                if_else(z == 0.2, 3, 
                        if_else(z == 0.24, 4, 
                                if_else(z == 0.28, 5, 
                                        if_else(z == 0.35, 6,
                                                if_else(z == 0.4, 7, 
                                                        if_else(z == 0.5, 8, 0))))))))
}
```


```{r}
for (i in c("PC1"#,"PC2","PC3","PC4","PC5","PC6"
            )) {
  
PCANi <- r3densities %>%
  mutate(Label = substr(Labelfine, 1, 5)) %>%
  left_join(., fractSum, by = "Label") %>%
  #filter(Ni.Vol.Corrected == 0.35) %>%
  #filter(hrs == 5) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Label != "WH21B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  #
  #
  mutate(ni2 = nifix(Ni.Vol.Corrected)) %>%
  filter(Temp == 900) %>%
  filter(hrs == 5) %>%
  #
  mutate(x = round(x, digits = 3)) %>%
  mutate(r3x = x) %>%
  select(-x) %>%
  filter(r3x >= -4) %>%
  filter(r3x <= 4) %>%
  left_join(., prcomp.R3.rot, by = "r3x") %>%
  #
  mutate(r3x = 10^r3x) %>%
  #
  ggplot(aes_string(fill = i)) +
  geom_ridgeline_gradient(size = 1, aes(x = r3x, y = ni2-1, 
                              group = Labelfine, 
                              height = density*5)) +
  #geom_tile(aes(x = r3x, y = 9, width = 0.025, height = 0.25)) +
  scale_fill_scico(palette = "roma", limits = c(-0.15,0.15), direction = -1) +
  #scale_fill_gradientn(colors = brewer_pal(palette = "RdBu")(5), limits = c(-0.15,0.15)) +
  scale_x_log10(sec.axis = sec_axis(~.^(1/3)*2, name = expression(D~'['*mu*m*']')),
                limits = c(0.0001, 10000),
                breaks = scales::trans_breaks("log10", function(x) 10^x),
                labels = trans_format("log10", math_format(10^.x))) +
  scale_y_continuous(breaks = c(0,1,2,3,4,5,6,7#,9
                                ),
                     labels = c("0.05", "0.10", "0.20", "0.24", "0.28", "0.35", "0.40", "0.50"#, "PC"
                                ),
                     sec.axis = sec_axis(~., breaks = c(0,1,2,3,4,5,6,7,9), labels = NULL)) +
  theme_classic() +
  labs(tag = "(a)") +
  ylab("Nickel Volume Fraction") +
  xlab(expression(R^3~'['*mu*m^3*']')) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        plot.tag = element_text(colour = "black", size = 18, face = "bold"),
        legend.text = element_text(colour="black", size = 12))

print(PCANi)
{if(save == 1)ggsave(filename = paste("./PCAexports/plotexport",i,"Ni",".png", sep = ""), plot = PCANi, 
         device = "png", width = 6,height = 4, units = "in")}
rm(PCANi)
}


#rm(nifix)
```



```{r}
timefix <- function(y){
  if_else(y == 150, 150, 
          if_else(y == 50, 100, 
                  if_else(y == 10, 50, 
                          if_else(y == 5, 0, 0))))
}



for (i in c("PC1","PC2","PC3","PC4","PC5","PC6")) {
  
PCAhrs <- r3densities %>%
  mutate(Label = substr(Labelfine, 1, 5)) %>%
  left_join(., fractSum, by = "Label") %>%
  #filter(Ni.Vol.Corrected == 0.35) %>%
  #filter(hrs == 5) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Label != "WH21B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  #
  filter(Temp == 900) %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  mutate(hrs2 = timefix(hrs)) %>%
  #
  mutate(x = round(x, digits = 3)) %>%
  mutate(r3x = x) %>%
  select(-x) %>%
  filter(r3x >= -4) %>%
  filter(r3x <= 4) %>%
  left_join(., prcomp.R3.rot, by = "r3x") %>%
  #
  mutate(r3x = 10^r3x) %>%
  #
  ggplot(aes_string(fill = i)) +
  geom_ridgeline_gradient(size = 1, aes(x = r3x, y = hrs2, 
                              group = Labelfine, 
                              height = density*200)) +
  geom_tile(aes(x = r3x, y = 270, width = 0.025, height = 10)) +
  scale_fill_scico(palette = "roma", limits = c(-0.15,0.15), direction = -1) +
  #scale_fill_gradientn(colors = brewer_pal(palette = "RdBu")(5), limits = c(-0.15,0.15)) +
  scale_x_log10(sec.axis = sec_axis(~.^(1/3)*2, name = expression(D~'['*mu*m*']')),
                limits = c(0.0001, 10000),
                breaks = scales::trans_breaks("log10", function(x) 10^x),
                labels = trans_format("log10", math_format(10^.x))) +
  scale_y_continuous(breaks = c(0,50,100,150),
                     limits = c(0,275),
                     labels = c("5", "10", "50", "150"),
                     sec.axis = sec_axis(~., breaks = c(0,50,100,150), labels = NULL)) +
  theme_classic() +
  ylab("Time [hrs]") +
  xlab(expression(R^3~'['*mu*m^3*']')) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(PCAhrs)
{if(save == 1)ggsave(filename = paste("./PCAexports/plotexport",i,"hrs",".png", sep = ""), plot = PCAhrs, 
         device = "png", width = 6,height = 4, units = "in")}
rm(PCAhrs)
}
```


-->

```{r}
for (i in c("PC1","PC2","PC3","PC4","PC5","PC6")) {
  
  PCATemp <- r3densities %>%
  mutate(Label = substr(Labelfine, 1, 5)) %>%
  left_join(., fractSum, by = "Label") %>%
  #filter(Ni.Vol.Corrected == 0.35) %>%
  #filter(hrs == 5) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Label != "WH21B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  #
  filter(hrs == 5) %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  #
  mutate(x = round(x, digits = 3)) %>%
  mutate(r3x = x) %>%
  select(-x) %>%
  filter(r3x >= -4) %>%
  filter(r3x <= 4) %>%
  left_join(., prcomp.R3.rot, by = "r3x") %>%
  #
  mutate(r3x = 10^r3x) %>%
  #
  ggplot(aes_string(fill = i)) +
  geom_ridgeline_gradient(size = 1, aes(x = r3x, y = Temp, 
                              group = Labelfine, 
                              height = density*500)) +
  geom_tile(aes(x = r3x, y = 1500, width = 0.025, height = 25)) +
  scale_fill_scico(palette = "roma", limits = c(-0.15,0.15), direction = -1) +
  #scale_fill_gradientn(colors = brewer_pal(palette = "RdBu")(5), limits = c(-0.15,0.15)) +
  scale_x_log10(sec.axis = sec_axis(~.^(1/3)*2, name = expression(D~'['*mu*m*']')),
                limits = c(0.0001, 10000),
                breaks = scales::trans_breaks("log10", function(x) 10^x),
                labels = trans_format("log10", math_format(10^.x))) +
  scale_y_continuous(breaks = c(700,800,900,1000,1100),
                     sec.axis = sec_axis(~., breaks = c(700,800,900,1000,1100), labels = NULL)) +
  theme_classic() +
  labs(tag = "(a)") +
  ylab(expression(Temp~'['*degree*C*']')) +
  xlab(expression(R^3~'['*mu*m^3*']')) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        plot.tag = element_text(colour = "black", size = 18, face = "bold"),
        legend.text = element_text(colour="black", size = 12))
  
  print(PCATemp)
  {if(save == 1)ggsave(filename = paste("./PCAexports/plotexport",i,"Temp",".png", sep = ""), plot = PCATemp, 
         device = "png", width = 6,height = 4, units = "in")}
  rm(PCATemp)
}
```

```{r}
brewer_pal(palette = "RdBu")(5)

wes_palette("Zissou1", 20, type = "continuous")
wes_palette("Moonrise3", 20, type = "continuous")
wes_palette("Darjeeling1", 20, type = "continuous")



scico_palette_names() %>%
  scico_palette_show(palettes = .)


paletteer_c(palette = "scico::roma", n = 5)

scico(5, palette = "roma")
```
-->

<!--
```{r}
procspace <- df_particles_fine %>%
  select(Label,Temp,hrs,Ni.Vol.Corrected) %>%
  mutate(Label = substr(Label,1,4)) %>%
  unique()

plot_ly(x = procspace$Temp,
        y = procspace$Ni.Vol.Corrected,
        z = procspace$hrs,
        color = procspace$Temp,
        colors = hue_pal()(5),
        type = 'scatter3d') %>%
  layout(title = 'Processing Space',
         scene = list(
           xaxis = list(title = "Sintering Temperature"),
           yaxis = list(title = "Nickel Fraction"),
           zaxis = list(type = "log", title = "Dwell Time")
           ))

#rm(procspace)
```
-->

<!--
```{r}
for (i in c("PC1","PC2","PC3","PC4","PC5","PC6")) {

PCA_Ni_Temp <- r3densities %>%
  mutate(Label = substr(Labelfine, 1, 5)) %>%
  left_join(., fractSum, by = "Label") %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Label != "WH21B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  #
  #
  mutate(ni2 = nifix(Ni.Vol.Corrected)) %>%
  #filter(Temp == 900) %>%
  filter(hrs == 5) %>%
  #
  mutate(x = round(x, digits = 3)) %>%
  mutate(r3x = x) %>%
  select(-x) %>%
  filter(r3x >= -4) %>%
  filter(r3x <= 4) %>%
  left_join(., prcomp.R3.rot, by = "r3x") %>%
  #
  mutate(r3x = 10^r3x) %>%
  #
  ggplot(aes_string(fill = i)) +
  geom_ridgeline_gradient(size = 1, aes(x = r3x, y = ni2-1, 
                              group = Labelfine,
                              color = as.factor(Temp),
                              #linetype = as.factor(hrs),
                              height = density*5)) +
  geom_tile(aes(x = r3x, y = 9, width = 0.025, height = 0.25)) +
  scale_linetype_manual(values = c("solid","dotted","dashed","dotdash")) +
  scale_fill_scico(palette = "roma", limits = c(-0.15,0.15), direction = -1) +
  #scale_fill_gradientn(colors = brewer_pal(palette = "RdBu")(5), limits = c(-0.15,0.15)) +
  scale_x_log10(sec.axis = sec_axis(~.^(1/3)*2, name = expression(D~'['*mu*m*']')),
                limits = c(0.0001, 10000),
                breaks = scales::trans_breaks("log10", function(x) 10^x),
                labels = trans_format("log10", math_format(10^.x))) +
  scale_y_continuous(breaks = c(0,1,2,3,4,5,6,7,9),
                     labels = c("0.05", "0.10", "0.20", "0.24", "0.28", "0.35", "0.40", "0.50", paste(i)),
                     sec.axis = sec_axis(~., breaks = c(0,1,2,3,4,5,6,7,9), labels = NULL)) +
  theme_classic() +
  labs(tag = "(a)") +
  ylab("Nickel Volume Fraction") +
  xlab(expression(R^3~'['*mu*m^3*']')) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        plot.tag = element_text(colour = "black", size = 18, face = "bold"),
        legend.text = element_text(colour="black", size = 12)) +
  guides(color = guide_legend(reverse = TRUE, title = expression(Temp~'['*degree*C*']'), 
                               override.aes = list(fill = "white"), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12)))

  print(PCA_Ni_Temp)
  {if(save == 1)ggsave(filename = paste("./PCAexports/plotexport",i,"_Ni_Temp",".png", sep = ""), plot = PCA_Ni_Temp, 
         device = "png", width = 6,height = 4, units = "in")}
  rm(PCA_Ni_Temp)

PCA_Temp_Ni <- r3densities %>%
  mutate(Label = substr(Labelfine, 1, 5)) %>%
  left_join(., fractSum, by = "Label") %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Label != "WH21B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  #
  filter(hrs == 5) %>%
  #filter(Ni.Vol.Corrected == 0.35) %>%
  #
  mutate(x = round(x, digits = 3)) %>%
  mutate(r3x = x) %>%
  select(-x) %>%
  filter(r3x >= -4) %>%
  filter(r3x <= 4) %>%
  left_join(., prcomp.R3.rot, by = "r3x") %>%
  #
  mutate(r3x = 10^r3x) %>%
  #
  ggplot(aes_string(fill = i)) +
  geom_ridgeline_gradient(size = 1, aes(x = r3x, y = Temp, 
                              group = Labelfine,
                              color = as.factor(Ni.Vol.Corrected),
                              height = density*500)) +
  geom_tile(aes(x = r3x, y = 1500, width = 0.025, height = 25)) +
  scale_fill_scico(palette = "roma", limits = c(-0.15,0.15), direction = -1) +
  #scale_fill_gradientn(colors = brewer_pal(palette = "RdBu")(5), limits = c(-0.15,0.15)) +
  scale_x_log10(sec.axis = sec_axis(~.^(1/3)*2, name = expression(D~'['*mu*m*']')),
                limits = c(0.0001, 10000),
                breaks = scales::trans_breaks("log10", function(x) 10^x),
                labels = trans_format("log10", math_format(10^.x))) +
  scale_y_continuous(breaks = c(700,800,900,1000,1100,1500),
                     labels = c(700,800,900,1000,1100,paste(i)),
                     sec.axis = sec_axis(~., breaks = c(700,800,900,1000,1100), labels = NULL)) +
  theme_classic() +
  labs(tag = "(a)") +
  ylab(expression(Temp~'['*degree*C*']')) +
  xlab(expression(R^3~'['*mu*m^3*']')) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        plot.tag = element_text(colour = "black", size = 18, face = "bold"),
        legend.text = element_text(colour="black", size = 12)) +
  guides(color = guide_legend(reverse = TRUE, title = "Ni Vol.",
                              override.aes = list(fill = "white"),
                              title.theme = element_text(colour = "black",
                                                         #face = "bold",
                                                         size = 12)))
  
  print(PCA_Temp_Ni)
  {if(save == 1)ggsave(filename = paste("./PCAexports/plotexport",i,"_Temp_Ni",".png", sep = ""), plot = PCA_Temp_Ni, 
         device = "png", width = 6,height = 4, units = "in")}
  rm(PCA_Temp_Ni)
}
```
-->

