---
title: "LTO-Ni-Skeletons"
author: "whh36"
date: "11/21/2020"
output: html_document
---

```{r}
library(spatstat)
```

```{r}
df_particles_fine %>%
  filter(magx == 10) %>%
  nrow()
```

<!--
```{r}
temp1 <- df_particles_fine %>%
  filter(magx == 10) %>%
  filter(Labelfine == "WH01A/1100-5-20Ni-A0008.tiff") #%>%
  #filter(Area > 0.00215)
  #filtered for Area > 0.00215, which gives an R3 of 1x10^-4 from R3 plots
```

```{r}
temp2 <- skeleton.branches.data %>%
  filter(Labelfineshort == "1100-5-20Ni-A0008.tiff") %>%
  group_by(Skeleton.ID) %>%
  summarise(partX.s = mean(V1.y), partY.s = mean(V1.x), partX.s2 = mean(V2.y), partY.s2 = mean(V2.x)) %>%
  mutate(partX.s.ave = (partX.s + partX.s2)/2) %>%
  mutate(partY.s.ave = (partY.s + partY.s2)/2)


skeleton.data %>%
  filter(Labelfineshort == "1100-5-20Ni-A0008.tiff") %>%
  filter(Branches == 0)

#temp1 and temp2 are different lengths because 0 branch data is left out of branch details info
#will need to run an ImageJ macro with a larger filter to get matching data?
#PSD analysis and skeleton analysis need to run with same filters
```

```{r}
ggplot() +
  geom_point(data = temp2, aes(x = partX.s, y = partY.s, color = "red")) +
  geom_point(data = temp1, aes(x = partX, y = partY)) +
  coord_fixed()

ggplot() +
  geom_point(data = temp2, aes(x = partX.s2, y = partY.s2, color = "red")) +
  geom_point(data = temp1, aes(x = partX, y = partY)) +
  coord_fixed()

ggplot() +
  geom_point(data = temp2, aes(x = partX.s.ave, y = partY.s.ave, color = "red")) +
  geom_point(data = temp1, aes(x = partX, y = partY)) +
  coord_fixed()
```

```{r}
#temp1ppp <- ppp(x = temp1$partX, y = temp1$partY, c(0,(8*1024/305)), c(0,(8*1024/305)))
#(8*1024/305) is the scale conversion for one dimension of each image at 10k
#the second two values define the window that contains the points

#temp2ppp <- ppp(x = temp2$partX.s.ave, y = temp2$partY.s.ave, c(0,(8*1024/305)), c(0,(8*1024/305)))

#nncross(temp1ppp, temp2ppp)
```
-->

```{r}
skeleton.data %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #filter(Average.Branch.Length > 0) %>%
  filter(Branches > 0) %>%
  #
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(hrs == 5) %>%
  #
  ggplot() +
  geom_density_ridges(size = 1, aes(x = Average.Branch.Length, y = Temp, group = Labelfine, 
                                    #color = black,
                                    fill = as.factor(Temp))) +
  geom_rect(color = "black", aes(xmin = ave.ave.branches-0.01, 
                ymin = Temp, 
                xmax = ave.ave.branches+0.01, 
                ymax = Temp + 100,
                fill = as.factor(Temp))) +
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(breaks = c(700,800,900,1000,1100),
                     sec.axis = sec_axis(~., labels = NULL)) +
  guides(color = FALSE, fill = guide_legend(reverse = TRUE, title = expression(Temp~'['*degree*C*']'), 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

branches_dist_temp <- skeleton.data %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #filter(Average.Branch.Length > 0) %>%
  filter(Branches > 1) %>%
  #
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(hrs == 5) %>%
  #
  ggplot() +
  geom_density_ridges(size = 1, aes(x = Branches, y = Temp, group = Labelfine, 
                                    #color = black,
                                    fill = as.factor(Temp))) +
  geom_rect(color = "black", aes(xmin = ave.branches-0.01, 
                ymin = Temp, 
                xmax = ave.branches+0.01, 
                ymax = Temp + 100,
                fill = as.factor(Temp))) +
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(breaks = c(700,800,900,1000,1100),
                     sec.axis = sec_axis(~., labels = NULL)) +
  ylab(expression(Temp~'['*degree*C*']')) +
  annotation_logticks(sides = "b") +
  guides(color = FALSE, fill = guide_legend(reverse = TRUE, title = expression(Temp~'['*degree*C*']'), 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(branches_dist_temp)
ggsave(filename = "./skeletonexports/branches_dist_temp.png", plot = branches_dist_temp, 
       device = "png", width = 6,height = 4, units = "in")
rm(branches_dist_temp)


max_branches_temp3d <- skeleton.data %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #filter(Average.Branch.Length > 0) %>%
  filter(Branches > 0) %>%
  #
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(hrs == 5) %>%
  #
  ggplot() +
  geom_density_ridges(size = 1, aes(x = Maximum.Branch.Length, y = Temp, group = Labelfine, 
                                    #color = black,
                                    fill = as.factor(Temp))) +
  ylab(expression(Temp~'['*degree*C*']')) +
  xlab(expression(Maximum~Branch~Length~'['*mu*m*']')) +
  geom_rect(color = "black", aes(xmin = ave.max.branches-0.01, 
                ymin = Temp, 
                xmax = ave.max.branches+0.01, 
                ymax = Temp + 100,
                fill = as.factor(Temp))) +
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(breaks = c(700,800,900,1000,1100),
                     sec.axis = sec_axis(~., labels = NULL)) +
  guides(color = FALSE, fill = guide_legend(reverse = TRUE, title = expression(Temp~'['*degree*C*']'), 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(max_branches_temp3d)
ggsave(filename = "./skeletonexports/max_branches_temp3d.png", plot = max_branches_temp3d, 
       device = "png", width = 6,height = 4, units = "in")
rm(max_branches_temp3d)

skeleton.data %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #filter(Average.Branch.Length > 0) %>%
  filter(Branches > 0) %>%
  #
  #filter(Ni.Vol.Corrected == 0.35) %>%
  filter(hrs == 5) %>%
  #
  ggplot() +
  geom_density_ridges(size = 1, aes(x = Maximum.Branch.Length, y = Temp, group = Labelfine, 
                                    #color = black,
                                    fill = as.factor(Ni.Vol.Corrected))) +
  geom_rect(color = "black", aes(xmin = ave.max.branches-0.01, 
                ymin = Temp, 
                xmax = ave.max.branches+0.01, 
                ymax = Temp + 100,
                fill = as.factor(Ni.Vol.Corrected))) +
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(breaks = c(700,800,900,1000,1100),
                     sec.axis = sec_axis(~., labels = NULL)) +
  guides(colour = FALSE, fill = guide_legend(reverse = TRUE, title = "Ni Vol.", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))
```

```{r}
skeleton.data %>%
  mutate(Ni.Vol.Corrected2 = Ni.Vol.Corrected) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.05,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.05, 1), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.10,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.10, 2), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.20,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.20, 3), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.24,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.24, 4), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.28,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.28, 5), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.35,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.35, 6), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.40,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.40, 7), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.50,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.50, 8), Ni.Vol.Corrected2)) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #filter(Average.Branch.Length > 0) %>%
  filter(Branches > 0) %>%
  #
  filter(Temp == 900) %>%
  filter(hrs == 5) %>%
  #
  ggplot() +
  geom_density_ridges(size = 1, aes(x = Average.Branch.Length, y = Ni.Vol.Corrected2, group = Labelfine, 
                                    #color = black,
                                    fill = as.factor(Ni.Vol.Corrected))) +
  geom_rect(color = "black", aes(xmin = ave.ave.branches-0.01, 
                ymin = Ni.Vol.Corrected2, 
                xmax = ave.ave.branches+0.01, 
                ymax = Ni.Vol.Corrected2 + 1,
                fill = as.factor(Ni.Vol.Corrected))) +
  ylab("Nickel Volume Fraction") +
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(breaks = c(1,2,3,4,5,6,7,8),
                     labels = c("0.05", "0.10", "0.20", "0.24", "0.28", "0.35", "0.40", "0.50"),
                     sec.axis = sec_axis(~., labels = NULL)) +
  guides(colour = FALSE, fill = guide_legend(reverse = TRUE, title = "Ni Vol.", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

branches_dist_ni <- skeleton.data %>%
  mutate(Ni.Vol.Corrected2 = Ni.Vol.Corrected) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.05,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.05, 1), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.10,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.10, 2), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.20,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.20, 3), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.24,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.24, 4), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.28,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.28, 5), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.35,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.35, 6), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.40,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.40, 7), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.50,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.50, 8), Ni.Vol.Corrected2)) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #filter(Average.Branch.Length > 0) %>%
  filter(Branches > 1) %>%
  #
  filter(Temp == 900) %>%
  filter(hrs == 5) %>%
  #
  ggplot() +
  geom_density_ridges(size = 1, aes(x = Branches, y = Ni.Vol.Corrected2, group = Labelfine, 
                                    #color = black,
                                    fill = as.factor(Ni.Vol.Corrected))) +
  geom_rect(color = "black", aes(xmin = ave.branches-0.01, 
                ymin = Ni.Vol.Corrected2, 
                xmax = ave.branches+0.01, 
                ymax = Ni.Vol.Corrected2 + 1,
                fill = as.factor(Ni.Vol.Corrected))) +
  ylab("Nickel Volume Fraction") +
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(breaks = c(1,2,3,4,5,6,7,8),
                     labels = c("0.05", "0.10", "0.20", "0.24", "0.28", "0.35", "0.40", "0.50"),
                     sec.axis = sec_axis(~., labels = NULL)) +
  annotation_logticks(sides = "b") +
  guides(colour = FALSE, fill = guide_legend(reverse = TRUE, title = "Ni Vol.", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(branches_dist_ni)
ggsave(filename = "./skeletonexports/branches_dist_ni.png", plot = branches_dist_ni, 
       device = "png", width = 6,height = 4, units = "in")
rm(branches_dist_ni)

max_branches_ni3d <- skeleton.data %>%
  mutate(Ni.Vol.Corrected2 = Ni.Vol.Corrected) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.05,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.05, 1), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.10,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.10, 2), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.20,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.20, 3), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.24,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.24, 4), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.28,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.28, 5), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.35,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.35, 6), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.40,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.40, 7), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.50,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.50, 8), Ni.Vol.Corrected2)) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #filter(Average.Branch.Length > 0) %>%
  filter(Branches > 0) %>%
  #
  filter(Temp == 900) %>%
  filter(hrs == 5) %>%
  #
  ggplot() +
  geom_density_ridges(size = 1, aes(x = Maximum.Branch.Length, y = Ni.Vol.Corrected2, group = Labelfine, 
                                    #color = black,
                                    fill = as.factor(Ni.Vol.Corrected))) +
  ylab("Nickel Volume Fraction") +
  xlab(expression(Maximum~Branch~Length~'['*mu*m*']')) +
  geom_rect(color = "black", aes(xmin = ave.max.branches-0.01, 
                ymin = Ni.Vol.Corrected2, 
                xmax = ave.max.branches+0.01, 
                ymax = Ni.Vol.Corrected2 + 1,
                fill = as.factor(Ni.Vol.Corrected))) +
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(breaks = c(1,2,3,4,5,6,7,8),
                     labels = c("0.05", "0.10", "0.20", "0.24", "0.28", "0.35", "0.40", "0.50"),
                     sec.axis = sec_axis(~., labels = NULL)) +
  guides(colour = FALSE, fill = guide_legend(reverse = TRUE, title = "Ni Vol.", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(max_branches_ni3d)
ggsave(filename = "./skeletonexports/max_branches_ni3d.png", plot = max_branches_ni3d, 
       device = "png", width = 6,height = 4, units = "in")
rm(max_branches_ni3d)


skeleton.data %>%
  mutate(Ni.Vol.Corrected2 = Ni.Vol.Corrected) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.05,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.05, 1), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.10,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.10, 2), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.20,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.20, 3), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.24,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.24, 4), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.28,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.28, 5), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.35,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.35, 6), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.40,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.40, 7), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.50,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.50, 8), Ni.Vol.Corrected2)) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #filter(Average.Branch.Length > 0) %>%
  filter(Branches > 0) %>%
  #
  #filter(Temp == 900) %>%
  filter(hrs == 5) %>%
  #
  ggplot() +
  geom_density_ridges(size = 1, aes(x = Maximum.Branch.Length, y = Ni.Vol.Corrected2, group = Labelfine, 
                                    #color = black,
                                    fill = as.factor(Temp))) +
  geom_rect(color = "black", aes(xmin = ave.max.branches-0.01, 
                ymin = Ni.Vol.Corrected2, 
                xmax = ave.max.branches+0.01, 
                ymax = Ni.Vol.Corrected2 + 1,
                fill = as.factor(Temp))) +
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(breaks = c(1,2,3,4,5,6,7,8),
                     labels = c("0.05", "0.10", "0.20", "0.24", "0.28", "0.35", "0.40", "0.50"),
                     sec.axis = sec_axis(~., labels = NULL)) +
  guides(color = FALSE, fill = guide_legend(reverse = TRUE, title = expression(Temp~'['*degree*C*']'), 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))
  
```

```{r}
skeleton.data %>%
  mutate(hrs = as.double(hrs)) %>%
  mutate(hrs2 = hrs) %>%
  mutate(hrs2 = if_else(hrs == 5, replace(hrs, hrs == 5, 1), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 10, replace(hrs, hrs == 10, 2), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 50, replace(hrs, hrs == 50, 3), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 150, replace(hrs, hrs == 150, 4), hrs2)) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #
  filter(Temp == 900) %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  #filter(Average.Branch.Length > 0) %>%
  filter(Branches > 0) %>%
  ggplot() +
  geom_density_ridges(size = 1, aes(x = Average.Branch.Length, y = hrs2, group = Labelfine, 
                                    #color = black,
                                    fill = as.factor(hrs))) +
  geom_rect(color = "black", aes(xmin = ave.ave.branches-0.01, 
                ymin = hrs2, 
                xmax = ave.ave.branches+0.01, 
                ymax = hrs2 + 1,
                fill = as.factor(hrs))) +
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(breaks = c(1:4),
                     labels = c("5","10","50","150"),
                     sec.axis = sec_axis(~., breaks = c(1:4), labels = NULL)) +
  guides(color = FALSE, fill = guide_legend(reverse = TRUE, title = "Time [hrs]", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  ylab("Time [hrs]") +
  scale_fill_manual(values=c("#00BF7D", "#BF7D00", "#7C00BF", "#BF0041")) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

branches_dist_hrs <- skeleton.data %>%
  mutate(hrs = as.double(hrs)) %>%
  mutate(hrs2 = hrs) %>%
  mutate(hrs2 = if_else(hrs == 5, replace(hrs, hrs == 5, 1), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 10, replace(hrs, hrs == 10, 2), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 50, replace(hrs, hrs == 50, 3), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 150, replace(hrs, hrs == 150, 4), hrs2)) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #
  filter(Temp == 900) %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  #filter(Average.Branch.Length > 0) %>%
  filter(Branches > 1) %>%
  ggplot() +
  geom_density_ridges(size = 1, aes(x = Branches, y = hrs2, group = Labelfine, 
                                    #color = black,
                                    fill = as.factor(hrs))) +
  geom_rect(color = "black", aes(xmin = ave.branches-0.01, 
                ymin = hrs2, 
                xmax = ave.branches+0.01, 
                ymax = hrs2 + 1,
                fill = as.factor(hrs))) +
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(breaks = c(1:4),
                     labels = c("5","10","50","150"),
                     sec.axis = sec_axis(~., breaks = c(1:4), labels = NULL)) +
  annotation_logticks(sides = "b") +
  guides(color = FALSE, fill = guide_legend(reverse = TRUE, title = "Time [hrs]", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  ylab("Time [hrs]") +
  scale_fill_manual(values=c("#00BF7D", "#BF7D00", "#7C00BF", "#BF0041")) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(branches_dist_hrs)
ggsave(filename = "./skeletonexports/branches_dist_hrs.png", plot = branches_dist_hrs, 
       device = "png", width = 6,height = 4, units = "in")
rm(branches_dist_hrs)

branches_dist_hrs2 <- skeleton.data %>%
  mutate(hrs = as.double(hrs)) %>%
  mutate(hrs2 = hrs) %>%
  mutate(hrs2 = if_else(hrs == 5, replace(hrs, hrs == 5, 1), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 10, replace(hrs, hrs == 10, 2), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 50, replace(hrs, hrs == 50, 3), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 150, replace(hrs, hrs == 150, 4), hrs2)) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #
  filter(Temp == 900) %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  #filter(Average.Branch.Length > 0) %>%
  filter(Branches > 0) %>%
  ggplot() +
  geom_density_ridges(size = 1, aes(x = Branches, y = hrs2, group = Labelfine, 
                                    #color = black,
                                    fill = as.factor(hrs))) +
  geom_rect(color = "black", aes(xmin = ave.branches-0.01, 
                ymin = hrs2, 
                xmax = ave.branches+0.01, 
                ymax = hrs2 + 1,
                fill = as.factor(hrs))) +
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(breaks = c(1:4),
                     labels = c("5","10","50","150"),
                     sec.axis = sec_axis(~., breaks = c(1:4), labels = NULL)) +
  annotation_logticks(sides = "b") +
  guides(color = FALSE, fill = guide_legend(reverse = TRUE, title = "Time [hrs]", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  ylab("Time [hrs]") +
  scale_fill_manual(values=c("#00BF7D", "#BF7D00", "#7C00BF", "#BF0041")) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(branches_dist_hrs2)
ggsave(filename = "./skeletonexports/branches_dist_hrs2.png", plot = branches_dist_hrs2, 
       device = "png", width = 6,height = 4, units = "in")
rm(branches_dist_hrs2)

max_branches_hrs3d <- skeleton.data %>%
  mutate(hrs = as.double(hrs)) %>%
  mutate(hrs2 = hrs) %>%
  mutate(hrs2 = if_else(hrs == 5, replace(hrs, hrs == 5, 1), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 10, replace(hrs, hrs == 10, 2), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 50, replace(hrs, hrs == 50, 3), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 150, replace(hrs, hrs == 150, 4), hrs2)) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #
  filter(Temp == 900) %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  #filter(Average.Branch.Length > 0) %>%
  filter(Branches > 0) %>%
  ggplot() +
  geom_density_ridges(size = 1, aes(x = Maximum.Branch.Length, y = hrs2, group = Labelfine, 
                                    #color = black,
                                    fill = as.factor(hrs))) +
  xlab(expression(Maximum~Branch~Length~'['*mu*m*']')) +
  geom_rect(color = "black", aes(xmin = ave.max.branches-0.01, 
                ymin = hrs2, 
                xmax = ave.max.branches+0.01, 
                ymax = hrs2 + 1,
                fill = as.factor(hrs))) +
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(breaks = c(1:4),
                     labels = c("5","10","50","150"),
                     sec.axis = sec_axis(~., breaks = c(1:4), labels = NULL)) +
  guides(color = FALSE, fill = guide_legend(reverse = TRUE, title = "Time [hrs]", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  ylab("Time [hrs]") +
  scale_fill_manual(values=c("#00BF7D", "#BF7D00", "#7C00BF", "#BF0041")) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(max_branches_hrs3d)
ggsave(filename = "./skeletonexports/max_branches_hrs3d.png", plot = max_branches_hrs3d, 
       device = "png", width = 6,height = 4, units = "in")
rm(max_branches_hrs3d)

skeleton.data %>%
  mutate(hrs = as.double(hrs)) %>%
  mutate(hrs2 = hrs) %>%
  mutate(hrs2 = if_else(hrs == 5, replace(hrs, hrs == 5, 1), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 10, replace(hrs, hrs == 10, 2), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 50, replace(hrs, hrs == 50, 3), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 150, replace(hrs, hrs == 150, 4), hrs2)) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #
  filter(Temp == 900) %>%
  #filter(Ni.Vol.Corrected == 0.35) %>%
  #filter(Average.Branch.Length > 0) %>%
  filter(Branches > 0) %>%
  ggplot() +
  geom_density_ridges(size = 1, aes(x = Maximum.Branch.Length, y = hrs2, group = Labelfine, 
                                    #color = black,
                                    fill = as.factor(Ni.Vol.Corrected))) +
  geom_rect(color = "black", aes(xmin = ave.max.branches-0.01, 
                ymin = hrs2, 
                xmax = ave.max.branches+0.01, 
                ymax = hrs2 + 1,
                fill = as.factor(Ni.Vol.Corrected))) +
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(breaks = c(1:4),
                     labels = c("5","10","50","150"),
                     sec.axis = sec_axis(~., breaks = c(1:4), labels = NULL)) +
  guides(colour = FALSE, fill = guide_legend(reverse = TRUE, title = "Ni Vol.", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  ylab("Time [hrs]") +
  #scale_fill_manual(values=c("#00BF7D", "#BF7D00", "#7C00BF", "#BF0041")) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))
```

```{r}
branches_hrs <- skeleton.data %>%
  mutate(hrs = as.double(hrs)) %>%
  mutate(hrs2 = hrs) %>%
  mutate(hrs2 = if_else(hrs == 5, replace(hrs, hrs == 5, 1), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 10, replace(hrs, hrs == 10, 2), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 50, replace(hrs, hrs == 50, 3), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 150, replace(hrs, hrs == 150, 4), hrs2)) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #
  filter(Temp == 900) %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  #filter(Average.Branch.Length > 0) %>%
  filter(Branches > 1) %>%
  ggplot() +
  geom_boxplot(aes(group = hrs, x = hrs, y = ave.branches)) +
  geom_point(size = 2, aes(y = ave.branches, x = hrs, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 color = as.factor(hrs))) +
  xlab("Time [hrs]") +
  ylab(expression(Average~Number~of~Branches)) +
  scale_y_continuous(limits = c(0,8), 
                     sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_log10(breaks = c(5,10,50,150),sec.axis = sec_axis(~., labels = NULL)) +
  guides(colour = guide_legend(reverse = TRUE, title = "Time [hrs]", 
                               title.theme = element_text(colour="black", 
                                                          #face = "bold", 
                                                          size = 12))) +
  scale_color_manual(values=c("#00BF7D", "#BF7D00", "#7C00BF", "#BF0041")) +
  guides(shape = FALSE) +
  guides(color = FALSE) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(branches_hrs)
ggsave(filename = "./skeletonexports/branches_hrs.png", plot = branches_hrs, 
       device = "png", width = 6,height = 4, units = "in")
rm(branches_hrs)



branches_ni <- skeleton.data %>%
  mutate(Ni.Vol.Corrected2 = Ni.Vol.Corrected) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.05,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.05, 1), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.10,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.10, 2), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.20,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.20, 3), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.24,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.24, 4), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.28,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.28, 5), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.35,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.35, 6), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.40,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.40, 7), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.50,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.50, 8), Ni.Vol.Corrected2)) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #filter(Average.Branch.Length > 0) %>%
  filter(Branches > 1) %>%
  #
  filter(Temp == 900) %>%
  filter(hrs == 5) %>%
  #
  ggplot() +
  geom_boxplot(aes(group = Ni.Vol.Corrected, x = Ni.Vol.Corrected, y = ave.branches)) +
  geom_point(size = 2, aes(y = ave.branches, x = Ni.Vol.Corrected, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 color = as.factor(Ni.Vol.Corrected))) +
  xlab("Nickel Volume Fraction") +
  ylab(expression(Average~Number~of~Branches)) +
  scale_y_continuous(limits = c(0,8), 
                     sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  guides(color = FALSE) +
  guides(shape = FALSE) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(branches_ni)
ggsave(filename = "./skeletonexports/branches_ni.png", plot = branches_ni, 
       device = "png", width = 6,height = 4, units = "in")
rm(branches_ni)


branches_temp <- skeleton.data %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #filter(Average.Branch.Length > 0) %>%
  filter(Branches > 1) %>%
  #
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(hrs == 5) %>%
  #
  ggplot() +
  geom_boxplot(aes(group = Temp, x = Temp, y = ave.branches)) +
  geom_point(size = 2, aes(y = ave.branches, x = Temp, 
                 #size = as.factor(hrs),
                 #shape = as.factor(Temp),
                 color = as.factor(Temp))) +
  xlab(expression(Temp~'['*degree*C*']')) +
  ylab(expression(Average~Number~of~Branches)) +
  scale_y_continuous(limits = c(0,8), sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  guides(color = FALSE) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(branches_temp)
ggsave(filename = "./skeletonexports/branches_temp.png", plot = branches_temp, 
       device = "png", width = 6,height = 4, units = "in")
rm(branches_temp)
```

```{r}
branches_ni_700_900 <- skeleton.data %>%
  mutate(Ni.Vol.Corrected2 = Ni.Vol.Corrected) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.05,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.05, 1), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.10,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.10, 2), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.20,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.20, 3), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.24,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.24, 4), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.28,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.28, 5), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.35,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.35, 6), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.40,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.40, 7), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.50,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.50, 8), Ni.Vol.Corrected2)) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #filter(Average.Branch.Length > 0) %>%
  filter(Branches > 1) %>%
  #
  filter(Temp == 700 | Temp == 900) %>%
  # filter(Temp >= 700) %>%
  # filter(Temp != 800) %>%
  # filter(Temp <= 900) %>%
  filter(hrs == 5) %>%
  #
  ggplot() +
  geom_boxplot(position = "identity", aes(group = substr(Label,1,4), color = as.factor(Temp),
                                          x = Ni.Vol.Corrected, y = ave.branches)) +
  geom_point(size = 2, aes(y = ave.branches, x = Ni.Vol.Corrected, 
                 #size = as.factor(hrs),
                 shape = as.factor(hrs),
                 color = as.factor(Temp))) +
  xlab("Nickel Volume Fraction") +
  ylab(expression(Average~Number~of~Branches)) +
  scale_y_continuous(limits = c(0,8), 
                     sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_color_manual(values=c("#F8766D", "#00BF7D")) +
  guides(color = guide_legend(reverse = TRUE, title = expression(Temp~'['*degree*C*']'), 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  guides(shape = FALSE) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(branches_ni_700_900)
ggsave(filename = "./skeletonexports/branches_ni_700_900.png", plot = branches_ni_700_900, 
       device = "png", width = 6,height = 4, units = "in")
rm(branches_ni_700_900)

branches_temp_24_35 <- skeleton.data %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #filter(Average.Branch.Length > 0) %>%
  filter(Branches > 1) %>%
  #
  filter(Ni.Vol.Corrected == 0.35 | Ni.Vol.Corrected == 0.24) %>%
  # filter(Ni.Vol.Corrected <= 0.35) %>%
  # filter(Ni.Vol.Corrected >= 0.24) %>%
  # filter(Ni.Vol.Corrected != 0.28) %>%
  filter(hrs == 5) %>%
  #
  ggplot() +
  geom_boxplot(position = "identity", aes(group = substr(Label,1,4),color = as.factor(Ni.Vol.Corrected),
                                          x = Temp, y = ave.branches)) +
  geom_point(size = 2, aes(y = ave.branches, x = Temp, 
                 #size = as.factor(hrs),
                 #shape = as.factor(Temp),
                 color = as.factor(Ni.Vol.Corrected))) +
  xlab(expression(Temp~'['*degree*C*']')) +
  ylab(expression(Average~Number~of~Branches)) +
  scale_y_continuous(limits = c(0,8), sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_color_manual(values=c("#00BE67", "#00A9FF")) +
  guides(colour = guide_legend(reverse = TRUE, title = "Ni Vol.", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(branches_temp_24_35)
ggsave(filename = "./skeletonexports/branches_temp_24_35.png", plot = branches_temp_24_35, 
       device = "png", width = 6,height = 4, units = "in")
rm(branches_temp_24_35)
```


<!--
```{r}
skeleton.data %>%
  filter(Branches == 0) %>%
  group_by(Labelfine) %>%
  #group_by(substr(Label,1,4)) %>%
  count() %>%
  rename(zerocount = n) %>%
  left_join(skeleton.data, ., by = "Labelfine") %>%
  ggplot() +
  geom_point(aes(x = Temp, y = zerocount))

skeleton.data %>%
  filter(Branches == 0) %>%
  filter(Temp >= 800) %>%
  group_by(Labelfine) %>%
  #group_by(substr(Label,1,4)) %>%
  count() %>%
  rename(zerocount = n) %>%
  left_join(skeleton.data, ., by = "Labelfine") %>%
  ggplot() +
  geom_point(aes(x = Temp, y = zerocount,
                 shape = as.factor(hrs),
                 color = as.factor(Ni.Vol.Corrected))) +
  scale_shape_manual(values=c(16, 17, 0, 2)) #hrs
```
-->

```{r}
branches_maxbranches <- skeleton.data %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(Branches > 0) %>%
  ggplot() +
  geom_point(aes(x = Branches, y = Maximum.Branch.Length, 
                 shape = as.factor(hrs),
                 color = as.factor(Temp))) +
  scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  guides(shape = guide_legend(title = "Time [hrs]", reverse = TRUE,
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour="black",
                                                          #face = "bold",
                                                          size = 12))) +
  guides(color = guide_legend(reverse = TRUE, title = expression(Temp~'['*degree*C*']'), 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  ylab(expression(Maximum~Branch~Length~'['*mu*m*']')) +
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_log10(limits = c(0.01,10),sec.axis = sec_axis(~., labels = NULL)) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(branches_maxbranches)
ggsave(filename = "./skeletonexports/branches_maxbranches.png", plot = branches_maxbranches, 
       device = "png", width = 6,height = 4, units = "in")
rm(branches_maxbranches)
```


#Subset data analysis (Large Particles Only to ensure data match)

```{r}

area_branches <- skelematch %>%
  ggplot() +
  geom_point(aes(x = Area, y = Branches,
                 shape = as.factor(hrs),
                 color = as.factor(Ni.Vol.Corrected))) +
  # geom_smooth(method = lm, se = FALSE, aes(group = Labelfine, 
  #                              color = as.factor(Ni.Vol.Corrected),
  #                              x = Area, y = Branches)) +
  scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_log10(sec.axis = sec_axis(~., labels = NULL)) +
  xlab(expression(Nickel~Particle~Area~'['*mu*m^2*']')) +
  guides(shape = guide_legend(title = "Time [hrs]", reverse = TRUE,
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour="black",
                                                          #face = "bold",
                                                          size = 12))) +
  guides(colour = guide_legend(reverse = TRUE, title = "Ni Vol.", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  coord_fixed() +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(area_branches)
ggsave(filename = "./skeletonexports/area_branches.png", plot = area_branches, 
       device = "png", width = 6,height = 4, units = "in")
rm(area_branches)
```


```{r}
skelematch %>%
  ggplot() +
  geom_boxplot(aes(group = Ni.Vol.Corrected, x = Ni.Vol.Corrected, y = Branches)) +
  geom_point(aes(x = Ni.Vol.Corrected, y = Branches, color = as.factor(Ni.Vol.Corrected))) +
  #scale_x_log10() +
  scale_y_log10()

skelematch %>%
  ggplot() +
  geom_point(alpha = 0.5,aes(x = totNifrace, y = Branches, 
                             shape = as.factor(hrs),
                             color = as.factor(Ni.Vol.Corrected))) +
  #scale_x_log10() +
  scale_y_log10()
```

```{r}
area_maxbranches <- skelematch %>%
  ggplot() +
  geom_point(#alpha = 0.5, 
             aes(x = Area, y = Maximum.Branch.Length, 
                 shape = as.factor(hrs),
                 color = as.factor(Ni.Vol.Corrected))) +
  # geom_smooth(method = lm, color = "black", se = FALSE, aes(#group = Labelfine, 
  #                              #color = as.factor(Ni.Vol.Corrected),
  #                              x = Area, y = Maximum.Branch.Length)) +
  scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(limits = c(0,7), sec.axis = sec_axis(~., labels = NULL)) +
  ylab(expression(Maximum~Branch~Length~'['*mu*m*']')) +
  xlab(expression(Nickel~Particle~Area~'['*mu*m^2*']')) +
  guides(shape = guide_legend(title = "Time [hrs]", reverse = TRUE,
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour="black",
                                                          #face = "bold",
                                                          size = 12))) +
  guides(colour = guide_legend(reverse = TRUE, title = "Ni Vol.", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(area_maxbranches)
ggsave(filename = "./skeletonexports/area_maxbranches.png", plot = area_maxbranches, 
       device = "png", width = 6,height = 4, units = "in")
rm(area_maxbranches)
```


```{r}
skelematch %>%
  filter(Branches > 1) %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  ggplot() +
  geom_point(#alpha = 0.5, 
             aes(x = Branches, y = Maximum.Branch.Length, 
                 shape = as.factor(hrs),
                 color = as.factor(hrs)
                 )
             ) +
  # geom_smooth(method = lm, se = FALSE, aes(#group = Labelfine,
  #                              #color = as.factor(Ni.Vol.Corrected),
  #                              x = Branches, y = Maximum.Branch.Length)) +
  scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  scale_color_manual(values=c("#00BF7D", "#BF7D00", "#7C00BF", "#BF0041")) +
  guides(shape = guide_legend(title = "Time [hrs]", reverse = TRUE,
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour="black",
                                                          #face = "bold",
                                                          size = 12))) +
  guides(color = guide_legend(title = "Time [hrs]", reverse = TRUE,
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour="black",
                                                          #face = "bold",
                                                          size = 12))) +
  ylab(expression(Maximum~Branch~Length~'['*mu*m*']')) +
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_log10(limits = c(0.1,10),sec.axis = sec_axis(~., labels = NULL)) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))
```

<!--
```{r}
plot_ly(x = skeleton.data$Maximum.Branch.Length, 
        y = skeleton.data$Branches, 
        z = skeleton.data$Ni.Vol.Corrected, 
        color = skeleton.data$Ni.Vol.Corrected,
        colors = hue_pal()(8),
        type = 'scatter3d') %>%
  layout(title = 'Skeletons',
         scene = list(
           xaxis = list(title = "Maximum.Branch.Length"),
           yaxis = list(title = "Branches", type = "log"),
           zaxis = list(title = "Ni.Vol.Corrected")
           ))
```
-->

```{r}
max_branches_hrs <- skeleton.data %>%
  mutate(hrs = as.double(hrs)) %>%
  mutate(hrs2 = hrs) %>%
  mutate(hrs2 = if_else(hrs == 5, replace(hrs, hrs == 5, 1), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 10, replace(hrs, hrs == 10, 2), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 50, replace(hrs, hrs == 50, 3), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 150, replace(hrs, hrs == 150, 4), hrs2)) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #
  filter(Temp == 900) %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  #filter(Average.Branch.Length > 0) %>%
  filter(Branches > 1) %>%
  filter(magx == 10) %>%
  ggplot() +
  geom_boxplot(aes(group = hrs, x = hrs, y = ave.max.branches)) +
  geom_point(size = 2, aes(y = ave.max.branches, x = hrs, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 color = as.factor(hrs))) +
  xlab("Time [hrs]") +
  ylab(expression(Average~Max~Branch~Length)) +
  scale_y_continuous(limits = c(0,1), 
                     sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_log10(breaks = c(5,10,50,150),sec.axis = sec_axis(~., labels = NULL)) +
  guides(colour = guide_legend(reverse = TRUE, title = "Time [hrs]", 
                               title.theme = element_text(colour="black", 
                                                          #face = "bold", 
                                                          size = 12))) +
  scale_color_manual(values=c("#00BF7D", "#BF7D00", "#7C00BF", "#BF0041")) +
  guides(shape = FALSE) +
  guides(color = FALSE) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(max_branches_hrs)
ggsave(filename = "./skeletonexports/max_branches_hrs.png", plot = max_branches_hrs, 
       device = "png", width = 6,height = 4, units = "in")
rm(max_branches_hrs)



max_branches_ni <- skeleton.data %>%
  mutate(Ni.Vol.Corrected2 = Ni.Vol.Corrected) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.05,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.05, 1), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.10,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.10, 2), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.20,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.20, 3), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.24,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.24, 4), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.28,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.28, 5), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.35,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.35, 6), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.40,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.40, 7), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.50,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.50, 8), Ni.Vol.Corrected2)) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #filter(Average.Branch.Length > 0) %>%
  filter(Branches > 1) %>%
  #
  filter(Temp == 900) %>%
  filter(hrs == 5) %>%
  #
  ggplot() +
  geom_boxplot(aes(group = Ni.Vol.Corrected, x = Ni.Vol.Corrected, y = ave.max.branches)) +
  geom_point(size = 2, aes(y = ave.max.branches, x = Ni.Vol.Corrected, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 color = as.factor(Ni.Vol.Corrected))) +
  xlab("Nickel Volume Fraction") +
  ylab(expression(Average~Max~Branch~Length)) +
  scale_y_continuous(limits = c(0,1), 
                     sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  guides(color = FALSE) +
  guides(shape = FALSE) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(max_branches_ni)
ggsave(filename = "./skeletonexports/max_branches_ni.png", plot = max_branches_ni, 
       device = "png", width = 6,height = 4, units = "in")
rm(max_branches_ni)


max_branches_temp <- skeleton.data %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #filter(Average.Branch.Length > 0) %>%
  filter(Branches > 1) %>%
  #
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(hrs == 5) %>%
  #
  ggplot() +
  geom_boxplot(aes(group = Temp, x = Temp, y = ave.max.branches)) +
  geom_point(size = 2, aes(y = ave.max.branches, x = Temp, 
                 #size = as.factor(hrs),
                 #shape = as.factor(Temp),
                 color = as.factor(Temp))) +
  xlab(expression(Temp~'['*degree*C*']')) +
  ylab(expression(Average~Max~Branch~Length)) +
  scale_y_continuous(limits = c(0,1), sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  guides(color = FALSE) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(max_branches_temp)
ggsave(filename = "./skeletonexports/max_branches_temp.png", plot = max_branches_temp, 
       device = "png", width = 6,height = 4, units = "in")
rm(max_branches_temp)
```


```{r}
ave.ave.branches_hrs <- skeleton.data %>%
  mutate(hrs = as.double(hrs)) %>%
  mutate(hrs2 = hrs) %>%
  mutate(hrs2 = if_else(hrs == 5, replace(hrs, hrs == 5, 1), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 10, replace(hrs, hrs == 10, 2), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 50, replace(hrs, hrs == 50, 3), hrs2)) %>%
  mutate(hrs2 = if_else(hrs == 150, replace(hrs, hrs == 150, 4), hrs2)) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #
  filter(Temp == 900) %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  #filter(Average.Branch.Length > 0) %>%
  filter(Branches > 1) %>%
  filter(magx == 10) %>%
  ggplot() +
  geom_boxplot(aes(group = hrs, x = hrs, y = ave.ave.branches)) +
  geom_point(size = 2, aes(y = ave.ave.branches, x = hrs, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 color = as.factor(hrs))) +
  xlab("Time [hrs]") +
  ylab(expression(Average~Ave~Branch~Length)) +
  scale_y_continuous(limits = c(0,1), 
                     sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_log10(breaks = c(5,10,50,150),sec.axis = sec_axis(~., labels = NULL)) +
  guides(colour = guide_legend(reverse = TRUE, title = "Time [hrs]", 
                               title.theme = element_text(colour="black", 
                                                          #face = "bold", 
                                                          size = 12))) +
  scale_color_manual(values=c("#00BF7D", "#BF7D00", "#7C00BF", "#BF0041")) +
  guides(shape = FALSE) +
  guides(color = FALSE) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(ave.ave.branches_hrs)
ggsave(filename = "./skeletonexports/ave_branches_hrs.png", plot = ave.ave.branches_hrs, 
       device = "png", width = 6,height = 4, units = "in")
rm(ave.ave.branches_hrs)



ave.ave.branches_ni <- skeleton.data %>%
  mutate(Ni.Vol.Corrected2 = Ni.Vol.Corrected) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.05,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.05, 1), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.10,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.10, 2), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.20,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.20, 3), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.24,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.24, 4), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.28,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.28, 5), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.35,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.35, 6), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.40,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.40, 7), Ni.Vol.Corrected2)) %>%
  mutate(Ni.Vol.Corrected2 = if_else(Ni.Vol.Corrected == 0.50,
                                    replace(Ni.Vol.Corrected, Ni.Vol.Corrected == 0.50, 8), Ni.Vol.Corrected2)) %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #filter(Average.Branch.Length > 0) %>%
  filter(Branches > 1) %>%
  #
  filter(Temp == 900) %>%
  filter(hrs == 5) %>%
  #
  ggplot() +
  geom_boxplot(aes(group = Ni.Vol.Corrected, x = Ni.Vol.Corrected, y = ave.ave.branches)) +
  geom_point(size = 2, aes(y = ave.ave.branches, x = Ni.Vol.Corrected, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 color = as.factor(Ni.Vol.Corrected))) +
  xlab("Nickel Volume Fraction") +
  ylab(expression(Average~Ave~Branch~Length)) +
  scale_y_continuous(limits = c(0,1), 
                     sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  guides(color = FALSE) +
  guides(shape = FALSE) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(ave.ave.branches_ni)
ggsave(filename = "./skeletonexports/ave_branches_ni.png", plot = ave.ave.branches_ni, 
       device = "png", width = 6,height = 4, units = "in")
rm(ave.ave.branches_ni)


ave.ave.branches_temp <- skeleton.data %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Labelfine != "WH06A/1000-5-35A0006.tiff") %>%
  filter(Labelfine != "WH06C/1000-5-35C0004.tiff") %>%
  filter(Label != "WH19A") %>%
  #filter(Average.Branch.Length > 0) %>%
  filter(Branches > 1) %>%
  #
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(hrs == 5) %>%
  #
  ggplot() +
  geom_boxplot(aes(group = Temp, x = Temp, y = ave.ave.branches)) +
  geom_point(size = 2, aes(y = ave.ave.branches, x = Temp, 
                 #size = as.factor(hrs),
                 #shape = as.factor(Temp),
                 color = as.factor(Temp))) +
  xlab(expression(Temp~'['*degree*C*']')) +
  ylab(expression(Average~Max~Branch~Length)) +
  scale_y_continuous(limits = c(0,1), sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  guides(color = FALSE) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(ave.ave.branches_temp)
ggsave(filename = "./skeletonexports/ave_branches_temp.png", plot = ave.ave.branches_temp, 
       device = "png", width = 6,height = 4, units = "in")
rm(ave.ave.branches_temp)
```

