---
title: "LTO-Ni-PCA-RF"
author: "William Huddleston"
date: '2022-08-15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(scico)
library(caret)
library(randomForest)
library(e1071)
library(ipred)
library(concaveman)
library(randomForestExplainer)
cb <- 1
save <- 0
```

#data prep

<!--


```{r}
PC_compiled.full <- read.csv("./data-files/pc_scores_nnd_vrn_r3d_3skel.csv")

PC_compiled.full <- df_particles_fine %>%
  select(Labelfine, magx) %>%
  unique() %>%
  left_join(PC_compiled.full,., by = "Labelfine") %>%
  #filter(is.na(condAve) == FALSE) %>%
  mutate(condAve = log(condAve)) #%>%
  #filter(magx == 10)

PC_compiled <- PC_compiled.full %>%
  select(-1,-3) %>%
  #select(1:60,condAve) %>%
  #filter(is.na(condAve) == FALSE) %>%
  #
  select(Labelfine,
         nnd_pc1,nnd_pc2,nnd_pc3,nnd_pc4,
         vrn_pc1,vrn_pc2,vrn_pc3,vrn_pc4,
         r3d_pc1,r3d_pc2,r3d_pc3,r3d_pc4,
         skel_avbr_pc1,skel_avbr_pc2,skel_avbr_pc3,skel_avbr_pc4,
         skel_br_pc1,skel_br_pc2,skel_br_pc3,skel_br_pc4,
         skel_mxbr_pc1,skel_mxbr_pc2,skel_mxbr_pc3,skel_mxbr_pc4,
         Ni.Vol.Corrected, Temp, hrs,
         stressf,
         condAve)



#summary(PC_compiled)
```


#data splitting


```{r}
#tempscaled.pc <- as.data.frame(scale(PC_compiled))

#split into testing and training
split.pc <- createDataPartition(PC_compiled$condAve, p = 0.7, times = 4)


trainset.pc <- PC_compiled[as.vector(split.pc[[1]]),]
testset.pc <- PC_compiled[-as.vector(split.pc[[1]]),]



trainset.pc.noscale <- trainset.pc
testset.pc.noscale <- testset.pc
trainset.pc.noscale <- select(trainset.pc.noscale,c(names(select(trainset.pc.noscale, -condAve)), "condAve"))
testset.pc.noscale <- select(testset.pc.noscale,c(names(select(testset.pc.noscale, -condAve)), "condAve"))
write.table(trainset.pc.noscale, file = "./data-files/trainset-pc-save.csv", row.names = FALSE, sep = ",")
write.table(testset.pc.noscale, file = "./data-files/testset-pc-save.csv", row.names = FALSE, sep = ",")
```
-->


```{r}
#same train test split
trainset.pc <- read.csv("./data-files/trainset-pc-save.csv", header = TRUE)
testset.pc <- read.csv("./data-files/testset-pc-save.csv", header = TRUE)

trainset.pc <- select(trainset.pc, -Labelfine)
testset.pc <- select(testset.pc, -Labelfine)

#scale features
trainset.pc <- as.data.frame(scale(trainset.pc))
testset.pc <- as.data.frame(scale(testset.pc))

#move condAve to last column
trainset.pc <- select(trainset.pc,c(names(select(trainset.pc, -condAve)), "condAve"))
testset.pc <- select(testset.pc,c(names(select(testset.pc, -condAve)), "condAve"))


#summary(temp)
#summary(trainset3)
#summary(testset)
#rm(temp)
#rm(split.pc)


```



#models

```{r}
s=Sys.time()
rfmodel.pc <- trainset.pc %>%
  select(-Ni.Vol.Corrected, -Temp, -hrs) %>%
  randomForest(x = ., y = trainset.pc$condAve, ntree = 300)
Sys.time()-s


#remove Ni.Vol.Corrected from RF model

conrferr.pc <- plot(rfmodel.pc, main = paste("Conductivity RF -", 
                        round(sqrt(last(rfmodel.pc$mse)),2),
                        "RMSE"))

conrferrplot.pc <- ggplot() +
  geom_line(size = 1, aes(x = 1:300, y = conrferr.pc)) +
  labs(title = paste("Conductivity RF - ", 
                        round(sqrt(last(rfmodel.pc$mse)),2),
                        " RMSE", sep = "")) +
  xlab("Trees") +
  ylab("Error") +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        plot.title = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))


print(conrferrplot.pc)
{if(save == 1)ggsave(filename = "./MLexportsPC/conrferrplot-pc.png", plot = conrferrplot.pc, device = "png", width = 6,height = 4, units = "in")}
rm(conrferr.pc)
rm(conrferrplot.pc)

#print(rfmodel)
```

```{r}
rfmodimp.pc <- importance(rfmodel.pc) %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(IncNodePurity) %>%
  filter(rowname != "condAve")

importance(rfmodel.pc) %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(desc(IncNodePurity))
```

<!--
```{r}
rfmodimp.verb.pc <- rfmodimp.pc %>%
  mutate(variable = rowname) %>%
  select(-rowname) #%>%
  # mutate(variable = if_else(variable == "ave.ave.branches", "Average Branch Length", variable)) %>%
  # mutate(variable = if_else(variable == "ave.max.branches", "Maximum Branch Length", variable)) %>%
  # mutate(variable = if_else(variable == "ave.branches", "Average Number of Branches", variable)) %>%
  # mutate(variable = if_else(variable == "aveAreafine", "Average Particle Area", variable)) %>%
  # mutate(variable = if_else(variable == "avevoronoix", "Average Edge-to-Edge Spacing", variable)) %>%
  # mutate(variable = if_else(variable == "fineavennd", "Average Center-to-Center Spacing", variable)) %>%
  # mutate(variable = if_else(variable == "finecount", "Counts Per Area", variable)) %>%
  # mutate(variable = if_else(variable == "hrs", "Dwell Time", variable)) %>%
  # mutate(variable = if_else(variable == "Temp", "Sintering Temperature", variable)) %>%
  # mutate(variable = if_else(variable == "Th.Density", "Bulk Density", variable)) %>%
  # mutate(variable = if_else(variable == "totNifrace", "Nickel Area Fraction", variable)) %>%
  # mutate(variable = if_else(variable == "voronoicount", "Edge-to-Edge Complexity", variable)) %>%
  # mutate(variable = if_else(variable == "Dim.1", "Size-PC-1", variable)) %>%
  # mutate(variable = if_else(variable == "Dim.2", "Size-PC-2", variable)) %>%
  # mutate(variable = if_else(variable == "Dim.3", "Size-PC-3", variable)) %>%
  # mutate(variable = if_else(variable == "Dim.4", "Size-PC-4", variable)) %>%
  # mutate(variable = if_else(variable == "Dim.5", "Size-PC-5", variable)) %>%
  # mutate(variable = if_else(variable == "Dim.6", "Size-PC-6", variable))

ggplot() +
  geom_point(data = rfmodimp.verb.pc, aes(x = variable, y = -IncNodePurity*10))



# conrfnode <- dotchart(rfmodimp.verb$IncNodePurity, labels = rfmodimp.verb$variable, main = "Conductivity RF")
# 
# print(conrfnode)
# {if(save == 1)ggsave(filename = "./MLexports/conrfnode.png", plot = conrfnode, 
#          device = "png", width = 6,height = 4, units = "in")}
# rm(conrfnode)

#{if(save == 1)png("./MLexports/conrfnode-pc.png")} #uncomment to save
print(dotchart(rfmodimp.verb.pc$IncNodePurity, labels = rfmodimp.verb.pc$variable, main = "Conductivity RF"))
dev.off()


#somehow combine node purity and depth information?
```
-->

```{r}
rfresults.pc <- predict(rfmodel.pc, testset.pc) %>%
  as.data.frame() %>%
  cbind(as.data.frame(testset.pc$condAve))

colnames(rfresults.pc)[1] <- "prediction"
colnames(rfresults.pc)[2] <- "actual"



rflm.pc <- lm(rfresults.pc$prediction ~ rfresults.pc$actual)

paste(round(summary(rflm.pc)$r.squared,3), "R^2")

paste(round(summary(rflm.pc)$adj.r.squared,3), "Adj. R^2")
```

```{r}
#plot of testing predicted vs measured
tempPAL <- scico(8, palette = "roma", direction = 1)
lim1 <- -1.5
lim2 <-  2.25

VALUETEMP.pc <- paste(round(summary(rflm.pc)$adj.r.squared,3)," ~ Adj. ~ R^2",sep = "")

conrfpredmeas.pc <- cbind(rfresults.pc, testset.pc) %>%
  ggplot() +
  geom_point(aes(y = prediction, x = condAve, color = as.factor(Ni.Vol.Corrected))) +
  geom_abline(slope = 1, intercept = 0) +
  #guides(color = FALSE) +
  scale_color_manual(values = tempPAL, labels = c(0.05,0.10,0.20,0.24,0.28,0.35,0.40,0.50)) +
  theme_classic() +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  coord_fixed(ratio = 1, xlim = c(lim1,lim2), ylim = c(lim1,lim2)) +
  xlab("Scaled Conductivity") +
  ylab("Conductivity Predicted") +
  guides(colour = guide_legend(reverse = TRUE, title = "Ni Vol.", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10))) +
  geom_abline(slope = rflm.pc$coefficients[2], 
              intercept = rflm.pc$coefficients[1],
              color = "red",linetype = "dashed") +
  annotate("text", label = VALUETEMP.pc, parse = T,
           x = 1, 
           y = -1) +
  labs(tag = "(b)") +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        #plot.margin = margin(10,10,10,45),
        plot.tag = element_text(colour = "black", size = 18, face = "bold"),
        legend.text = element_text(colour="black", size = 12))

print(conrfpredmeas.pc)
{if(save == 1)ggsave(filename = "./MLexportsPC/conrfpredmeas.png", plot = conrfpredmeas.pc, device = "png", width = 6,height = 4, units = "in")}
rm(conrfpredmeas.pc)

```

```{r}
#plot of training predicted vs measured

rfresults.training.pc <- predict(rfmodel.pc, trainset.pc) %>%
  as.data.frame() %>%
  cbind(as.data.frame(trainset.pc$condAve))

colnames(rfresults.training.pc)[1] <- "prediction"
colnames(rfresults.training.pc)[2] <- "actual"



rflm.training.pc <- lm(rfresults.training.pc$prediction ~ rfresults.training.pc$actual)

paste(round(summary(rflm.training.pc)$r.squared,3), "R^2")

paste(round(summary(rflm.training.pc)$adj.r.squared,3), "Adj. R^2")

#
#
#

tempPAL <- scico(8, palette = "roma", direction = 1)
lim1 <- -1.5
lim2 <-  2.25

VALUETEMP.pc <- paste(round(summary(rflm.training.pc)$adj.r.squared,3)," ~ Adj. ~ R^2",sep = "")

conrfpredmeas.training.pc <- cbind(rfresults.training.pc, trainset.pc) %>%
  ggplot() +
  geom_point(aes(y = prediction, x = condAve, color = as.factor(Ni.Vol.Corrected))) +
  geom_abline(slope = 1, intercept = 0) +
  #guides(color = FALSE) +
  scale_color_manual(values = tempPAL, labels = c(0.05,0.10,0.20,0.24,0.28,0.35,0.40,0.50)) +
  theme_classic() +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  coord_fixed(ratio = 1, xlim = c(lim1,lim2), ylim = c(lim1,lim2)) +
  xlab("Scaled Conductivity") +
  ylab("Conductivity Predicted") +
  guides(colour = guide_legend(reverse = TRUE, title = "Ni Vol.", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10))) +
  geom_abline(slope = rflm.training.pc$coefficients[2], 
              intercept = rflm.training.pc$coefficients[1],
              color = "red",linetype = "dashed") +
  annotate("text", label = VALUETEMP.pc, parse = T,
           x = 1, 
           y = -1)  +
  labs(tag = "(a)") +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        #plot.margin = margin(10,10,10,45),
        plot.tag = element_text(colour = "black", size = 18, face = "bold"),
        legend.text = element_text(colour="black", size = 12))

print(conrfpredmeas.training.pc)
{if(save == 1)ggsave(filename = "./MLexportsPC/conrfpredmeastrain.png", plot = conrfpredmeas.training.pc, device = "png", width = 6,height = 4, units = "in")}
rm(conrfpredmeas.training.pc)


```



```{r}
rfmodel.min.depth.df.pc <- min_depth_distribution(rfmodel.pc)

rfmodel.min.depth.df.pc <- rfmodel.min.depth.df.pc %>%
  filter(variable != "condAve") #%>%
  # mutate(variable = if_else(variable == "ave.ave.branches", "Average Branch Length", variable)) %>%
  # mutate(variable = if_else(variable == "ave.max.branches", "Maximum Branch Length", variable)) %>%
  # mutate(variable = if_else(variable == "ave.branches", "Average Number of Branches", variable)) %>%
  # mutate(variable = if_else(variable == "aveAreafine", "Average Particle Area", variable)) %>%
  # mutate(variable = if_else(variable == "avevoronoix", "Average Edge-to-Edge Spacing", variable)) %>%
  # mutate(variable = if_else(variable == "fineavennd", "Average Center-to-Center Spacing", variable)) %>%
  # mutate(variable = if_else(variable == "finecount", "Counts Per Area", variable)) %>%
  # mutate(variable = if_else(variable == "hrs", "Dwell Time", variable)) %>%
  # mutate(variable = if_else(variable == "Temp", "Sintering Temperature", variable)) %>%
  # mutate(variable = if_else(variable == "Th.Density", "Bulk Density", variable)) %>%
  # mutate(variable = if_else(variable == "totNifrace", "Nickel Area Fraction", variable)) %>%
  # mutate(variable = if_else(variable == "voronoicount", "Edge-to-Edge Complexity", variable)) %>%
  # mutate(variable = if_else(variable == "Dim.1", "Size-PC-1", variable)) %>%
  # mutate(variable = if_else(variable == "Dim.2", "Size-PC-2", variable)) %>%
  # mutate(variable = if_else(variable == "Dim.3", "Size-PC-3", variable)) %>%
  # mutate(variable = if_else(variable == "Dim.4", "Size-PC-4", variable)) %>%
  # mutate(variable = if_else(variable == "Dim.5", "Size-PC-5", variable)) %>%
  # mutate(variable = if_else(variable == "Dim.6", "Size-PC-6", variable))

conrfmindepth.pc <- plot_min_depth_distribution(rfmodel.min.depth.df.pc, k = 30, #mean_sample = "relevant_trees"
                                                ) +
  xlab("") +
  theme(axis.text.x = element_text(colour = "black", size = 12),
        axis.text.y = element_text(colour = "black", size = 12),
        axis.ticks = element_line(colour = "black", size = 1),
        #axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 12),
        axis.title.y = element_text(colour = "black", size = 12),
        #plot.margin = margin(10,10,10,45),
        plot.tag = element_text(colour = "black", size = 18, face = "bold"),
        legend.text = element_text(colour="black", size = 12)) +
  {if(cb == 1)scale_fill_scico_d(na.translate = FALSE, palette = "nuuk", direction = 1, begin = 0, end = 1)}

print(conrfmindepth.pc)
{if(save == 1)ggsave(filename = "./MLexportsPC/conrfmindepth.png", plot = conrfmindepth.pc, device = "png", width = 7.29,height = 4.5, units = "in")}
rm(conrfmindepth.pc)
```
-->



```{r}

bind2 <- df_particles_fine %>%
  select(Labelfine, magx) %>%
  unique()

scoresdata <- read.csv("./data-files/pc_scores_nnd_vrn_r3d_3skel.csv") %>%
  left_join(., bind2, by = "Labelfine") %>%
  filter(magx == 10) %>%
  filter(Temp >= 800) %>%
  filter(Labelfine != "WH35A/WH35A0010.tiff") %>%
  filter(Label != "WH13A") %>% #weird outlier
  filter(Label != "WH15B") %>%
  filter(Label != "WH10D")
```


```{r}
hull_data <- scoresdata %>%
  #
  group_by(Ni.Vol.Corrected) %>%
  slice(chull(r3d_pc1, vrn_pc1))

r3d_pc1.vrn_pc1 <- scoresdata %>%
  #
  ggplot(aes(x = r3d_pc1, y = vrn_pc1)) +
  geom_point(aes(color = as.factor(Ni.Vol.Corrected),
                 shape = as.factor(Temp)
                 )) +
  geom_polygon(data = hull_data, alpha = 0.3, show.legend = T,
               aes(fill = as.factor(Ni.Vol.Corrected), 
                   color = as.factor(Ni.Vol.Corrected))) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_shape_manual(values=c(17, 16, 0, 2)) + #Temp
  geom_hline(yintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  geom_vline(xintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  #scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  {if(cb == 1)scale_fill_scico_d(palette = "roma", direction = 1)} + #nickel
  {if(cb == 1)scale_color_scico_d(palette = "roma", direction = 1)} + #nickel
  theme_classic() +
  guides(shape = guide_legend(title = expression(Temp~'['*degree*C*']'),  reverse = TRUE,
                               #override.aes = list(size=4),
                              override.aes=list(fill=NA),
                               title.theme = element_text(colour="black",
                                                          #face = "bold",
                                                          size = 10))) +
  guides(fill = guide_legend(reverse = FALSE, title = "Ni Vol.",
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10))) +
  guides(color = guide_legend(reverse = FALSE, title = "Ni Vol.", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10))) +
  labs(tag = "(c)") +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        #plot.margin = margin(10,10,10,45),
        plot.tag = element_text(colour = "black", size = 18, face = "bold"),
        legend.text = element_text(colour="black", size = 12))

print(r3d_pc1.vrn_pc1)
{if(save == 1)ggsave(filename = "./paperexports/r3d_pc1-vrn_pc1.png", plot = r3d_pc1.vrn_pc1, 
         device = "png", width = 6,height = 4, units = "in")}
rm(r3d_pc1.vrn_pc1)
```

```{r}
hull_data <- scoresdata %>%
  #
  group_by(Ni.Vol.Corrected) %>%
  slice(chull(r3d_pc1, skel_br_pc1))

r3d_pc1.skel_br_pc1 <- scoresdata %>%
  #
  ggplot(aes(x = r3d_pc1, y = skel_br_pc1)) +
  geom_point(aes(color = as.factor(Ni.Vol.Corrected),
                 shape = as.factor(Temp)
                 )) +
  geom_polygon(data = hull_data, alpha = 0.3, show.legend = T,
               aes(fill = as.factor(Ni.Vol.Corrected), color = as.factor(Ni.Vol.Corrected))) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_shape_manual(values=c(17, 16, 0, 2)) + #Temp
  geom_hline(yintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  geom_vline(xintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  #scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  {if(cb == 1)scale_fill_scico_d(palette = "roma", direction = 1)} + #nickel
  {if(cb == 1)scale_color_scico_d(palette = "roma", direction = 1)} + #nickel
  theme_classic() +
  guides(shape = guide_legend(title = expression(Temp~'['*degree*C*']'),  reverse = TRUE,
                               #override.aes = list(size=4), 
                              override.aes=list(fill=NA),
                               title.theme = element_text(colour="black",
                                                          #face = "bold",
                                                          size = 10))) +
  guides(fill = guide_legend(reverse = FALSE, title = "Ni Vol.",
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10))) +
  guides(color = guide_legend(reverse = FALSE, title = "Ni Vol.", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10))) +
  labs(tag = "(a)") +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        #plot.margin = margin(10,10,10,45),
        plot.tag = element_text(colour = "black", size = 18, face = "bold"),
        legend.text = element_text(colour="black", size = 12))


print(r3d_pc1.skel_br_pc1)
{if(save == 1)ggsave(filename = "./paperexports/r3d_pc1-skel_br_pc1.png", plot = r3d_pc1.skel_br_pc1, 
         device = "png", width = 6,height = 4, units = "in")}
rm(r3d_pc1.skel_br_pc1)
```

```{r}
hull_data <- scoresdata %>%
  #
  group_by(Ni.Vol.Corrected) %>%
  slice(chull(r3d_pc1, r3d_pc2))

scoresdata %>%
  #
  ggplot(aes(x = r3d_pc1, y = r3d_pc2)) +
  geom_point(aes(color = as.factor(Ni.Vol.Corrected),
                 shape = as.factor(Temp)
                 )) +
  geom_polygon(data = hull_data, alpha = 0.3, show.legend = T,
               aes(fill = as.factor(Ni.Vol.Corrected), 
                   color = as.factor(Ni.Vol.Corrected))) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_shape_manual(values=c(17, 16, 0, 2)) + #Temp
  geom_hline(yintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  geom_vline(xintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  #scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  {if(cb == 1)scale_fill_scico_d(palette = "roma", direction = 1)} + #nickel
  {if(cb == 1)scale_color_scico_d(palette = "roma", direction = 1)} + #nickel
  theme_classic() +
  guides(shape = guide_legend(title = expression(Temp~'['*degree*C*']'),  reverse = TRUE,
                               #override.aes = list(size=4),
                              override.aes=list(fill=NA),
                               title.theme = element_text(colour="black",
                                                          #face = "bold",
                                                          size = 10))) +
  guides(fill = guide_legend(reverse = FALSE, title = "Ni Vol.",
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10))) +
  guides(color = guide_legend(reverse = FALSE, title = "Ni Vol.", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10)))
```



```{r}
hull_data <- scoresdata %>%
  #
  group_by(Ni.Vol.Corrected) %>%
  slice(chull(r3d_pc1, vrn_pc2))

scoresdata %>%
  #
  ggplot(aes(x = r3d_pc1, y = vrn_pc2)) +
  geom_point(aes(color = as.factor(Ni.Vol.Corrected),
                 shape = as.factor(Temp)
                 )) +
  geom_polygon(data = hull_data, alpha = 0.3, show.legend = T,
               aes(fill = as.factor(Ni.Vol.Corrected), 
                   color = as.factor(Ni.Vol.Corrected))) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_shape_manual(values=c(17, 16, 0, 2)) + #Temp
  geom_hline(yintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  geom_vline(xintercept = 0, color = "black", size = 0.5, linetype = "dashed") +
  #scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  {if(cb == 1)scale_fill_scico_d(palette = "roma", direction = 1)} + #nickel
  {if(cb == 1)scale_color_scico_d(palette = "roma", direction = 1)} + #nickel
  theme_classic() +
  guides(shape = guide_legend(title = expression(Temp~'['*degree*C*']'),  reverse = TRUE,
                               #override.aes = list(size=4),
                              override.aes=list(fill=NA),
                               title.theme = element_text(colour="black",
                                                          #face = "bold",
                                                          size = 10))) +
  guides(fill = guide_legend(reverse = FALSE, title = "Ni Vol.",
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10))) +
  guides(color = guide_legend(reverse = FALSE, title = "Ni Vol.", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 10)))
```
