---
title: "LTO-Ni-Import-Skeletons"
author: "whh36"
date: "8/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
skeleton.list <- list.files("./data-files/skeletons10k/", full.names = TRUE)
skeleton.list5k <- list.files("./data-files/skeletons05k/", full.names = TRUE)

skeleton.list <- c(skeleton.list,skeleton.list5k)
rm(skeleton.list5k)

skel.dens.branch <- data.frame()
skel.dens.avebranch <- data.frame()
skel.dens.maxbranch <- data.frame()

skeleton.data <- data.frame()

nR3 <- 512 #number of points in each estimate, defaule is 512


for (i in skeleton.list){
  
  #read in skeleton data
  skeleton.temp <- read.csv(i, header = TRUE) %>%
    rename(skel.num = X) %>%
    rename(Branches = X..Branches) %>%
    rename(Junctions = X..Junctions) %>%
    rename(End.point.voxels = X..End.point.voxels) %>%
    rename(Junction.voxels = X..Junction.voxels) %>%
    rename(Slab.voxels = X..Slab.voxels) %>%
    #
    rename(Triple.points = X..Triple.points) %>%
    rename(Quadruple.points = X..Quadruple.points) %>%
    cbind(., i) %>%
    rename(Labelfine = i) %>%
    mutate(Labelfine = substr(Labelfine,27,nchar(i)-4))
  
  skeleton.data <- rbind(skeleton.data, skeleton.temp)
  
  #create the density curves
  skeleton.dist.branch <- skeleton.temp %>%
  ggplot() +
  geom_density(n = nR3, aes(x = Branches)) +
    scale_x_log10(limits = c(0.01,1000))
  
  skeleton.dist.avebranch <- skeleton.temp %>%
  ggplot() +
  geom_density(n = nR3, aes(x = Average.Branch.Length)) +
    scale_x_log10(limits = c(0.01,10))
  
  skeleton.dist.maxbranch <- skeleton.temp %>%
  ggplot() +
  geom_density(n = nR3, aes(x = Maximum.Branch.Length)) +
    scale_x_log10(limits = c(0.01,10))
  
  #save the density curves to a dataframe
  skel.dens.branch <- ggplot_build(skeleton.dist.branch)$data[[1]] %>%
  dplyr::select(2, 3) %>% #second number is 3 for density or 6 for stat(count)
  cbind(., i) %>%
  rbind(skel.dens.branch, .)
  
  skel.dens.avebranch <- ggplot_build(skeleton.dist.avebranch)$data[[1]] %>%
  dplyr::select(2, 3) %>% #second number is 3 for density or 6 for stat(count)
  cbind(., i) %>%
  rbind(skel.dens.avebranch, .)
  
  skel.dens.maxbranch <- ggplot_build(skeleton.dist.maxbranch)$data[[1]] %>%
  dplyr::select(2, 3) %>% #second number is 3 for density or 6 for stat(count)
  cbind(., i) %>%
  rbind(skel.dens.maxbranch, .)
  
  #calculate means in the for loop
  # skeleton.data <- skeleton.temp %>%
  # summarise(METRIC = mean(METRIC)) %>%
  # cbind(., nrow(skeleton.data), i) %>%
  # rbind(skeleton.data, .)
  
  rm(skeleton.temp)
}

rm(skeleton.list)
rm(i)
rm(nR3)


```

```{r}
#write.table(skeleton.dens, file = "./data-files/skeleton.dens.csv", row.names = FALSE, sep = ",")


write.table(skeleton.data, file = "./data-files/skeleton.data.csv", row.names = FALSE, sep = ",")

write.table(skel.dens.branch, file = "./data-files/skel.dens.branch.csv", row.names = FALSE, sep = ",")
write.table(skel.dens.avebranch, file = "./data-files/skel.dens.avebranch.csv", row.names = FALSE, sep = ",")
write.table(skel.dens.maxbranch, file = "./data-files/skel.dens.maxbranch.csv", row.names = FALSE, sep = ",")

```







```{r}
skeleton.branches.list <- list.files("./data-files/skeleton.branch.info10k/", full.names = TRUE)
skeleton.branches.list5k <- list.files("./data-files/skeleton.branch.info05k/", full.names = TRUE)

skeleton.branches.list <- c(skeleton.branches.list,skeleton.branches.list5k)
rm(skeleton.branches.list5k)

skeleton.branches.data <- data.frame()

#nR3 <- 512 #number of points in each estimate, defaule is 512

for (i in skeleton.branches.list){
  
  #read in skeleton branches data
  branches.temp <- read.csv(i, header = TRUE) %>%
    cbind(., i) %>%
    rename(Labelfine = i) %>%
    mutate(Labelfine = substr(Labelfine,35,nchar(i)-4))
  
  skeleton.branches.data <- rbind(skeleton.branches.data, branches.temp)
  
  rm(branches.temp)
}

rm(skeleton.branches.list)
rm(i)
#rm(nR3)


```

```{r}
write.table(skeleton.branches.data, file = "./data-files/skeleton.branches.data.csv", row.names = FALSE, sep = ",")
```



#Subset of >900C


```{r}
skeleton.list <- list.files("./data-files/skeletons.subset/", full.names = TRUE)

#skeleton.dens <- data.frame()

skeleton.data <- data.frame()

nR3 <- 512 #number of points in each estimate, defaule is 512

for (i in skeleton.list){
  
  #read in skeleton data
  skeleton.temp <- read.csv(i, header = TRUE) %>%
    rename(skel.num = X) %>%
    rename(Branches = X..Branches) %>%
    rename(Junctions = X..Junctions) %>%
    rename(End.point.voxels = X..End.point.voxels) %>%
    rename(Junction.voxels = X..Junction.voxels) %>%
    rename(Slab.voxels = X..Slab.voxels) %>%
    #
    rename(Triple.points = X..Triple.points) %>%
    rename(Quadruple.points = X..Quadruple.points) %>%
    cbind(., i) %>%
    rename(Labelfine = i) %>%
    mutate(Labelfine = substr(Labelfine,31,nchar(i)-4))
  
  skeleton.data <- rbind(skeleton.data, skeleton.temp)
  
  #create the density curves
  # skeleton.dist <- skeleton.data %>%
  # ggplot() +
  # geom_density(n = nR3, aes(x = METRIC)) +
  #   scale_x_continuous(limits = c(LIM1,LIM2))
  
  #save the density curves to a dataframe
  # skeleton.dens <- ggplot_build(skeleton.dist)$data[[1]] %>%
  # dplyr::select(2, COLS) %>% #second number is 3 for density or 6 for stat(count)
  # cbind(., i) %>%
  # rbind(skeleton.dens, .)
  
  #calculate means in the for loop
  # skeleton.data <- skeleton.temp %>%
  # summarise(METRIC = mean(METRIC)) %>%
  # cbind(., nrow(skeleton.data), i) %>%
  # rbind(skeleton.data, .)
  
  rm(skeleton.temp)
}

rm(skeleton.list)
rm(i)
rm(nR3)


```

```{r}
#write.table(skeleton.dens, file = "./data-files/skeleton.dens.csv", row.names = FALSE, sep = ",")

write.table(skeleton.data, file = "./data-files/skeleton.data.subset.csv", row.names = FALSE, sep = ",")
```







```{r}
skeleton.branches.list <- list.files("./data-files/skeleton.branch.info.subset/", full.names = TRUE)

skeleton.branches.data <- data.frame()

#nR3 <- 512 #number of points in each estimate, defaule is 512

for (i in skeleton.branches.list){
  
  #read in skeleton branches data
  branches.temp <- read.csv(i, header = TRUE) %>%
    cbind(., i) %>%
    rename(Labelfine = i) %>%
    mutate(Labelfine = substr(Labelfine,42,nchar(i)-4))
  
  skeleton.branches.data <- rbind(skeleton.branches.data, branches.temp)
  
  rm(branches.temp)
}

rm(skeleton.branches.list)
rm(i)
#rm(nR3)


```

```{r}
write.table(skeleton.branches.data, file = "./data-files/skeleton.branches.data.subset.csv", row.names = FALSE, sep = ",")
```


```{r}
#cleanup
rm(skeleton.data)
rm(skeleton.branches.data)
```

