---
title: "LTO-Ni-Mechanical-Plots"
author: "whh36"
date: "8/16/2020"
output: html_document
---

```{r setup, include=FALSE}
#SETUP OF LIBRARIES
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE) #set echo to FALSE to hide code
```

```{r}
fractSum %>%
  filter(Label != "WH17B") %>%
  filter(is.na(load) == FALSE) %>% #removes non mech data
  #filter(hrs == 5) %>%
  #filter(Ni.Vol.Corrected == 0.35) %>%
  group_by(Temp) %>%
  ggplot() +
  geom_boxplot(aes(group = Temp, x = Temp, y = stressf)) +
  geom_point(aes(x = Temp, y = stressf, shape = as.factor(hrs),
                 color = as.factor(Temp))) +
  guides(color = FALSE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(limits = c(0,250), expand = c(0,0), 
                     sec.axis = sec_axis(~., labels = NULL)) +
  scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  theme_classic() +
  xlab(expression(Temp~'['*degree*C*']')) +
  ylab(expression(sigma[fr]~'['*MPa*']')) +
  guides(shape = guide_legend(title = "Time [hrs]", reverse = TRUE,
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour="black",
                                                          #face = "bold",
                                                          size = 12))) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

mechtempploteb <- fractSum %>%
  filter(Label != "WH17B") %>%
  filter(is.na(load) == FALSE) %>% #removes non mech data
  filter(hrs == 5) %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  group_by(Temp) %>%
  ggplot() +
  geom_boxplot(aes(group = Temp, x = Temp, y = stressf)) +
  geom_point(aes(x = Temp, y = stressf, color = as.factor(Temp))) +
  guides(color = FALSE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(limits = c(0,250), expand = c(0,0), 
                     sec.axis = sec_axis(~., labels = NULL)) +
  theme_classic() +
  xlab(expression(Temp~'['*degree*C*']')) +
  ylab(expression(sigma[fr]~'['*MPa*']')) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(mechtempploteb)
ggsave(filename = "./plotexports/plotexportmechtempeb.png", plot = mechtempploteb, 
       device = "png", width = 6,height = 4, units = "in")
rm(mechtempploteb)
```

```{r}
fractSum %>%
  filter(Label != "WH09D") %>%
  filter(is.na(load) == FALSE) %>% #removes non mech data
  #filter(Temp == 900) %>%
  #filter(hrs == 5) %>%
  ggplot() +
  scale_y_continuous(limits = c(0,250), expand = c(0,0), 
                     sec.axis = sec_axis(~., labels = NULL)) +
  geom_boxplot(aes(group = Ni.Vol.Corrected, x = Ni.Vol.Corrected, y = stressf)) +
  geom_point(aes(x = Ni.Vol.Corrected, y = stressf, 
                 shape = as.factor(hrs), 
                 color = as.factor(Ni.Vol.Corrected))) +
  #geom_point(data = filter(mechdata2, Temp == 900), aes(x = Ni.Vol.Corrected, y = stressf, color = as.factor(Temp))) +
  guides(color = FALSE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  theme_classic() +
  xlab("Nickel Volume Fraction") +
  ylab(expression(sigma[fr]~'['*MPa*']')) +
  scale_color_manual(values=c("#000000", "#F8766D", "#CD9600", "#7CAE00", "#00BE67", "#00BFC4", "#00A9FF", "#C77CFF", "#FF61CC")) +
  scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  guides(shape = guide_legend(title = "Time [hrs]", reverse = TRUE,
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour="black",
                                                          #face = "bold",
                                                          size = 12))) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

mechniploteb <- fractSum %>%
  filter(Label != "WH09D") %>%
  filter(is.na(load) == FALSE) %>% #removes non mech data
  filter(Temp == 900) %>%
  filter(hrs == 5) %>%
  ggplot() +
  scale_y_continuous(limits = c(0,250), expand = c(0,0), 
                     sec.axis = sec_axis(~., labels = NULL)) +
  geom_boxplot(aes(group = Ni.Vol.Corrected, x = Ni.Vol.Corrected, y = stressf)) +
  geom_point(aes(x = Ni.Vol.Corrected, y = stressf, 
                 #shape = as.factor(hrs), 
                 color = as.factor(Ni.Vol.Corrected))) +
  #geom_point(data = filter(mechdata2, Temp == 900), aes(x = Ni.Vol.Corrected, y = stressf, color = as.factor(Temp))) +
  guides(color = FALSE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  theme_classic() +
  xlab("Nickel Volume Fraction") +
  ylab(expression(sigma[fr]~'['*MPa*']')) +
  scale_color_manual(values=c("#000000", "#F8766D", "#CD9600", "#7CAE00", "#00BE67", "#00BFC4", "#00A9FF", "#C77CFF", "#FF61CC")) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))


print(mechniploteb)
ggsave(filename = "./plotexports/plotexportmechnieb.png", plot = mechniploteb, 
       device = "png", width = 6,height = 4, units = "in")
rm(mechniploteb)

```

```{r}
fractSum %>%
  filter(is.na(load) == FALSE) %>% #removes non mech data
  #filter(Ni.Vol.Corrected == 0.35) %>%
  #filter(Temp == 900) %>%
  ggplot() +
  geom_boxplot(aes(group = hrs, x = hrs, y = stressf)) +
  geom_point(aes(x = hrs, y = stressf, shape = as.factor(Temp),
                 color = as.factor(hrs))) +
  scale_x_log10(breaks = c(5,10,50,150),sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(limits = c(0,250), sec.axis = sec_axis(~., labels = NULL)) +
  scale_color_manual(values=c("#00BF7D", "#BF7D00", "#7C00BF", "#BF0041")) +
  ylab(expression(sigma[fr]~'['*MPa*']')) +
  xlab("Time [hrs]") +
  guides(color = FALSE) +
  guides(shape = guide_legend(title = expression(Temp~'['*degree*C*']'), reverse = TRUE,
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour="black",
                                                          #face = "bold",
                                                          size = 12))) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

mechtimeeb <- fractSum %>%
  filter(is.na(load) == FALSE) %>% #removes non mech data
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(Temp == 900) %>%
  ggplot() +
  geom_boxplot(aes(group = hrs, x = hrs, y = stressf)) +
  geom_point(aes(x = hrs, y = stressf, color = as.factor(hrs))) +
  scale_x_log10(breaks = c(5,10,50,150),sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(limits = c(0,250), sec.axis = sec_axis(~., labels = NULL)) +
  scale_color_manual(values=c("#00BF7D", "#BF7D00", "#7C00BF", "#BF0041")) +
  ylab(expression(sigma[fr]~'['*MPa*']')) +
  xlab("Time [hrs]") +
  guides(color = FALSE) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(mechtimeeb)
ggsave(filename = "./plotexports/plotexportmechtimeeb.png", plot = mechtimeeb, 
       device = "png", width = 6,height = 4, units = "in")
rm(mechtimeeb)
```

```{r}
#raw data density vs Temp and hrs

fractSum %>%
  ggplot() +
  geom_point(aes(y = Th.Density, x = Temp,
                 #size = as.factor(hrs),
                 #shape = as.factor(Temp),
                 color = as.factor(hrs))) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(limits = c(0, 105), sec.axis = sec_axis(~., labels = NULL)) +
  #guides(color = FALSE) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

fractSum %>%
  mutate(spcap = 160*3.48*(1-Ni.Vol.Corrected)/(3.48*(1-Ni.Vol.Corrected)+8.91*(Ni.Vol.Corrected))) %>%
  ggplot() +
  geom_point(aes(x = Ni.Vol.Corrected, y = spcap, 
                 color = as.factor(Ni.Vol.Corrected))) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(limits = c(0,200), expand = c(0,0), 
                     sec.axis = sec_axis(~., labels = NULL)) +
  guides(color = FALSE) +
  theme_classic() +
  xlab("Nickel Volume Fraction") +
  ylab(expression(Specific~Capacity~'['*mAh*'/'*g*']')) +
  scale_color_manual(values=c("#000000", "#F8766D", "#CD9600", "#7CAE00", "#00BE67", "#00BFC4", "#00A9FF", "#C77CFF", "#FF61CC")) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))
```

```{r}
#raw data fracture stress vs density and R3

fractSum %>%
  filter(is.na(load) == FALSE) %>% #removes non mech data
  ggplot() +
  geom_point(aes(x = Th.Density, y = stressf, 
                 shape = as.factor(hrs),
                 color = as.factor(Temp))) +
  guides(color = FALSE) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(limits = c(0,250), expand = c(0,0), 
                     sec.axis = sec_axis(~., labels = NULL)) +
  theme_classic() +
  ylab(expression(sigma[fr]~'['*MPa*']')) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))
```

```{r}
fracsize <- fractSum %>%
  filter(is.na(load) == FALSE) %>% #removes non mech data
  #filter(Ni.Vol.Corrected == 0.35) %>%
  mutate(stresso = stressf*exp((1.05-Th.Density/100)*coef(fracmodel)[2]*-1)) %>%
  ggplot() +
  geom_point(size = 2.5, stroke = 2,aes(x = R3, y = log(stresso), 
                 shape = as.factor(hrs),
                 color = as.factor(Temp))) +
  guides(color = FALSE) +
  #scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_log10(sec.axis = sec_axis(~.^(1/3)*2, name = expression(D~'['*mu*m*']')),
                limits = c(0.006, 150),
                #breaks = scales::trans_breaks("log10", function(x) 10^x),
                labels = trans_format("log10", math_format(10^.x))) +
  scale_y_continuous(limits = c(3,7), 
                expand = c(0,0), 
                sec.axis = sec_axis(~., labels = NULL)) +
  scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  ylab(expression('ln'*'('*sigma[o]*')'~'['*MPa*']')) +
  xlab(expression(R^3~'['*mu*m^3*']')) +
  theme_classic() +
  guides(shape = guide_legend(title = "Time [hrs]", reverse = TRUE,
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour="black",
                                                          #face = "bold",
                                                          size = 12))) +
  guides(colour = guide_legend(title = expression(Temp~'['*degree*C*']'), reverse = TRUE,
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour="black",
                                                          #face = "bold",
                                                          size = 12))) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour = "black", size = 12))

print(fracsize)
ggsave(filename = "./plotexports/plotexportfracsize.png", plot = fracsize, 
       device = "png", width = 6,height = 4, units = "in")
rm(fracsize)
```

```{r}
#fracture stress vs porosity showing the model fit

#can this plot be colored relative to size too?
fracmod <- fractSum %>%
  filter(is.na(load) == FALSE) %>% #removes non mech data
  ggplot() +
  geom_point(size = 3, aes(x = 100-Th.Density, y = log(stressf),
                           #color = as.factor(Ni.Vol.Corrected),
                           #color = as.factor(Temp)
                           color = as.factor(Temp))) +
  geom_abline(slope = coef(fracmodel)[2]/100,
              intercept = 5.181) +
  theme_classic() +
  ylab(expression('ln'*'('*sigma[fr]*')'~'['*MPa*']')) +
  scale_y_continuous(sec.axis = sec_axis(~exp(.), name = expression(sigma[o]~'['*MPa*']'))) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(fracmod)
ggsave(filename = "./plotexports/plotexportfracmod.png", plot = fracmod, 
       device = "png", width = 6,height = 4, units = "in")
rm(fracmod)
```

```{r}
#fracture stress normalized by porosity plot

fracporo <- fractSum %>%
  mutate(modx = ((100-Th.Density)/100)) %>%
  mutate(sigmanot = stressf/exp(coef(fracmodel)[2]*modx)) %>%
  ggplot() +
  geom_point(size = 4, aes(x = modx, y = log(sigmanot), color = as.factor(Temp))) +
  theme_classic() +
  ylab(expression('ln'*'('*sigma[o]*')'~'['*MPa*']')) +
  scale_y_continuous(sec.axis = sec_axis(~exp(.), name = expression(sigma[o]~'['*MPa*']'))) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(fracporo)
ggsave(filename = "./plotexports/plotexportfracporo.png", plot = fracporo, 
       device = "png", width = 6,height = 4, units = "in")
rm(fracporo)
```

```{r}
#fracture curve toughening comparison

#This is really only relevant for the fracture curves, which could be useful for ease of plotting:
#do it better (similar to adding the density and sample info to dataframe two . . .
#add density and dimensions and sample info to mechdata from the fractSum info (similar to how I did with size data)

toughen <- mechdata %>%
  group_by(Label) %>%
  filter(Label == c("WH32A","WH13Y")) %>%
  ggplot() +
  geom_line(size = 1.5, aes(x = exten, y = load, color = as.factor(Label))) +
  scale_x_continuous(limits = c(0,0.1), 
                     sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  ylab("Load [N]") +
  xlab("Extension [mm]") +
  #guides(color = FALSE) +
  guides(colour = guide_legend(reverse = TRUE, title = "Time [hrs]", 
                               title.theme = element_text(colour="black", 
                                                          size = 12))) +
  scale_color_manual(values=c("#000000", "#00A9FF"), labels = c("5", "150")) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(toughen)
ggsave(filename = "./plotexports/plotexportmechtoughen.png", plot = toughen, 
       device = "png", width = 6,height = 4, units = "in")
rm(toughen)
```

```{r}
#plastic toughening R3 distro plotting
#these samples showed plastic or toughened failures

df_particles %>%
  group_by(Label) %>%
  #mutate(Label = substr(Label,0,4)) %>%
  filter(Area >= 0.005) %>%
  filter(Label == c("WH33C","WH32A","WH32C","WH35A","WH35B")) %>%
  ggplot() +
  geom_density(size = 1, aes(x = R3, y = ..density.., color = Label)) +
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL),
              #limits = c(0.0001, 100000),
              breaks = scales::trans_breaks("log10", function(x) 10^x),
              labels = trans_format("log10", math_format(10^.x))) +
  theme_classic()

```

```{r}
#plot and list of largest average particle size measures

toughsize <- fractSum %>%
  filter(Label != "WH03A") %>%
  filter(Ni.Vol.Corrected > 0) %>%
  ggplot() +
  geom_point(size = 3, stroke = 2,
             aes(x = Temp, y = R3,
                 shape = as.factor(hrs),
                 color = as.factor(Ni.Vol.Corrected))) +
  xlab(expression(Temp~'['*degree*C*']')) +
  ylab(expression(R^3~'['*mu*m^3*']')) +
  theme_classic() +
  scale_y_log10(limits = c(3,75), sec.axis = sec_axis(~.^(1/3)*2, name = expression(D~'['*mu*m*']'))) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  guides(colour = guide_legend(reverse = TRUE, title = "Ni Vol.", 
                               override.aes = list(size=3), 
                               title.theme = element_text(colour="black", size = 12))) +
  guides(shape = guide_legend(reverse = TRUE, title = "Time [hrs]",
                              override.aes = list(size=3),
                              title.theme = element_text(colour="black", size = 12))) +
  annotation_logticks(sides = "l") +
  #geom_label_repel(data = subset(fractSum, R3 > 10), aes(x = Temp, y = R3, label = Label)) +
  geom_hline(yintercept = 10, color = "#00A9FF",linetype = "dashed", size = 1) +
  scale_shape_manual(values=c(16, 17, 0, 2)) + #hrs
  guides(size = FALSE) +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(toughsize)
ggsave(filename = "./plotexports/plotexportmechtoughsize.png", plot = toughsize, 
       device = "png", width = 6,height = 4.5, units = "in")
rm(toughsize)

fractSum %>%
  select(Label, R3) %>%
  arrange(desc(R3)) %>%
  slice(1:15)
```

```{r}
#appearance of "onset" of toughening in a smaller sample (rank 15th largest)
#WH03C

mechdata %>%
  group_by(Label) %>%
  #filter(mTemp == 900) %>%
  #filter(mtime == 50) %>%
  #filter(mNi == 0.28) %>%
  filter(Label == "WH03C") %>%
  ggplot() +
  geom_line(size = 1.5, aes(x = exten, y = load, color = as.factor(mNi))) +
  scale_x_continuous(limits = c(0.075,0.11), 
                     sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  ylab("Load [N]") +
  xlab("Extension [mm]") +
  #guides(color = FALSE) +
  guides(colour = guide_legend(title = expression(Ni~Vol~'['*'%'*']'), 
                               title.theme = element_text(colour="black", 
                                                          size = 12))) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))
```

```{r}
stressfzz <- fractSum %>%
  ggplot() +
  geom_point(size = 3, aes(y = stressf, x = zz, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 color = as.factor(Ni.Vol.Corrected))) +
  xlab(expression(ln~(T*R^'3'*'/'~t))) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  #guides(color = FALSE) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(stressfzz)
ggsave(filename = "./plotexports/plotexportstressfzz.png", plot = stressfzz, device = "png", width = 8, height = 6, units = "in")
rm(stressfzz)

stressozz <- fractSum %>%
  mutate(stresso = stressf*exp((1.05-Th.Density/100)*coef(fracmodel)[2]*-1)) %>%
  ggplot() +
  geom_point(size = 3, aes(y = stresso, x = zz,
                           #x = zz-coef(regmod,2)[3]*Ni.Vol.Corrected,
                           #x = zzz,
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 color = as.factor(Ni.Vol.Corrected))) +
  xlab(expression(ln~(T*R^'3'*'/'~t))) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(limits = c(0,500), sec.axis = sec_axis(~., labels = NULL)) +
  #scale_y_log10(limits = c(10,750), sec.axis = sec_axis(~., labels = NULL)) +
  #guides(color = FALSE) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(stressozz)
ggsave(filename = "./plotexports/plotexportstressozz.png", plot = stressozz, device = "png", width = 8, height = 6, units = "in")
rm(stressozz)
```

```{r}
#zz and zzz vs R3 and hrs, model normalization comparison

fractSum %>%
  ggplot() +
  geom_point(aes(y = zz, x = log(R3),
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 color = as.factor(hrs))) +
  #scale_x_log10() +
  #guides(color = FALSE) +
  theme_classic()

fractSum %>%
  ggplot() +
  geom_point(aes(y = zzz, x = log(R3), 
                 #size = as.factor(hrs),
                 #shape = as.factor(Temp),
                 color = as.factor(hrs))) +
  #scale_x_log10() +
  #guides(color = FALSE) +
  theme_classic()

fractSum %>%
  ggplot() +
  geom_point(aes(x = zz, y = zzz, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 color = as.factor(hrs))) +
  #scale_x_log10() +
  #guides(color = FALSE) +
  theme_classic()

fractSum %>%
  ggplot() +
  geom_point(aes(y = zz + log(hrs) - log(Temp+273.15), x = log(R3), 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 color = as.factor(hrs))) +
  #scale_x_log10() +
  #guides(color = FALSE) +
  theme_classic()

fractSum %>%
  ggplot() +
  geom_point(aes(y = zzz + log(hrs) - log(Temp+273.15), x = log(R3), 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 color = as.factor(hrs))) +
  #scale_x_log10() +
  #guides(color = FALSE) +
  theme_classic()
```

```{r}
#normalized stress for 900-5 vs Ni

stressnormni <- fractSum %>%
  filter(is.na(stressf) == FALSE) %>%
  filter(Temp == 900) %>%
  filter(hrs == 5) %>%
  mutate(stresso = stressf*exp((1.05-Th.Density/100)*coef(fracmodel)[2]*-1)) %>%
  ggplot() +
  geom_boxplot(aes(group = Ni.Vol.Corrected, x = Ni.Vol.Corrected, y = log(stresso))) +
  geom_point(size = 2, aes(y = log(stresso), x = Ni.Vol.Corrected, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 color = as.factor(Ni.Vol.Corrected))) +
  xlab("Nickel Volume Fraction") +
  ylab(expression(sigma[o]~'['*MPa*']')) +
  scale_y_continuous(limits = c(3,7),
                sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  ylab(expression('ln'*'('*sigma[o]*')'~'['*MPa*']')) +
  scale_color_manual(values=c("#000000", "#F8766D", "#CD9600", "#7CAE00", "#00BE67", "#00BFC4", "#00A9FF", "#C77CFF", "#FF61CC")) +
  guides(color = FALSE) +
  guides(shape = FALSE) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(stressnormni)
ggsave(filename = "./plotexports/plotexportstressnormni.png", plot = stressnormni, device = "png", width = 6, height = 4, units = "in")
rm(stressnormni)
```

```{r}
#all samples
fractSum %>%
  filter(is.na(stressf) == FALSE) %>%
  mutate(stresso = stressf*exp((1.05-Th.Density/100)*coef(fracmodel)[2]*-1)) %>%
  ggplot() +
  geom_boxplot(aes(group = Ni.Vol.Corrected, x = Ni.Vol.Corrected, y = stresso)) +
  geom_point(size = 2, aes(y = stresso, x = Ni.Vol.Corrected, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 color = as.factor(Ni.Vol.Corrected))) +
  #xlab(expression(ln~(T*R^'3'*'/'~t))) +
  scale_y_log10(limits = c(10,750),
                sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_color_manual(values=c("#000000", "#F8766D", "#CD9600", "#7CAE00", "#00BE67", "#00BFC4", "#00A9FF", "#C77CFF", "#FF61CC")) +
  guides(color = FALSE) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))


fractSum %>%
  filter(is.na(stressf) == FALSE) %>%
  mutate(spcap = 160*3.48*(1-Ni.Vol.Corrected)/(3.48*(1-Ni.Vol.Corrected)+8.91*(Ni.Vol.Corrected))) %>%
  filter(Temp == 900) %>%
  filter(hrs == 5) %>%
  mutate(stresso = stressf*exp((1.05-Th.Density/100)*coef(fracmodel)[2]*-1)) %>%
  ggplot() +
  geom_boxplot(aes(group = Ni.Vol.Corrected, x = Ni.Vol.Corrected, y = stresso*spcap/160)) +
  geom_point(size = 2, aes(y = stresso*spcap/160, x = Ni.Vol.Corrected, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 color = as.factor(Ni.Vol.Corrected))) +
  xlab("Nickel Volume Fraction") +
  #ylab(expression(sigma[o]~'['*MPa*']')) +
  scale_y_continuous(limits = c(0,200),
                sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_color_manual(values=c("#000000", "#F8766D", "#CD9600", "#7CAE00", "#00BE67", "#00BFC4", "#00A9FF", "#C77CFF", "#FF61CC")) +
  guides(color = FALSE) +
  guides(shape = FALSE) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))
```

```{r}
#normalized stress for 5-35 vs Temp

stressnormtemp <- fractSum %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(hrs == 5) %>%
  mutate(stresso = stressf*exp((1.05-Th.Density/100)*coef(fracmodel)[2]*-1)) %>%
  ggplot() +
  geom_boxplot(aes(group = Temp, x = Temp, y = log(stresso))) +
  geom_point(size = 2, aes(y = log(stresso), x = Temp, 
                 #size = as.factor(hrs),
                 #shape = as.factor(Temp),
                 color = as.factor(Temp))) +
  xlab(expression(Temp~'['*degree*C*']')) +
  ylab(expression('ln'*'('*sigma[o]*')'~'['*MPa*']')) +
  scale_y_continuous(limits = c(3,7),
                sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  guides(color = FALSE) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(stressnormtemp)
ggsave(filename = "./plotexports/plotexportstressnormtemp.png", plot = stressnormtemp, device = "png", width = 6, height = 4, units = "in")
rm(stressnormtemp)

#all samples
fractSum %>%
  mutate(stresso = stressf*exp((1.05-Th.Density/100)*coef(fracmodel)[2]*-1)) %>%
  ggplot() +
  geom_boxplot(aes(group = Temp, x = Temp, y = stresso)) +
  geom_point(size = 2, aes(y = stresso, x = Temp, 
                 #size = as.factor(hrs),
                 #shape = as.factor(Temp),
                 color = as.factor(Ni.Vol.Corrected))) +
  #xlab(expression(ln~(T*R^'3'*'/'~t))) +
  scale_y_log10(limits = c(10,750),
                sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  #guides(color = FALSE) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))
```

```{r}
#normalized stress for 900-35 vs hrs

stressnormhrs <- fractSum %>%
  filter(Ni.Vol.Corrected == 0.35) %>%
  filter(Temp == 900) %>%
  mutate(stresso = stressf*exp((1.05-Th.Density/100)*coef(fracmodel)[2]*-1)) %>%
  ggplot() +
  geom_boxplot(aes(group = hrs, x = hrs, y = log(stresso))) +
  geom_point(size = 2, aes(y = log(stresso), x = hrs, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 color = as.factor(hrs))) +
  xlab("Time [hrs]") +
  ylab(expression('ln'*'('*sigma[o]*')'~'['*MPa*']')) +
  scale_y_continuous(limits = c(3,7), 
                sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_log10(breaks = c(5,10,50,150),sec.axis = sec_axis(~., labels = NULL)) +
  guides(colour = guide_legend(reverse = TRUE, title = "Time [hrs]", 
                               title.theme = element_text(colour="black", 
                                                          #face = "bold", 
                                                          size = 12))) +
  scale_color_manual(values=c("#00BF7D", "#BF7D00", "#7C00BF", "#BF0041")) +
  guides(shape = FALSE) +
  guides(color = FALSE) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(stressnormhrs)
ggsave(filename = "./plotexports/plotexportstressnormhrs.png", plot = stressnormhrs, 
       device = "png", width = 6, height = 4, units = "in")
rm(stressnormhrs)

#all samples
fractSum %>%
  filter(Temp >= 800) %>%
  mutate(stresso = stressf*exp((1.05-Th.Density/100)*coef(fracmodel)[2]*-1)) %>%
  ggplot() +
  geom_boxplot(aes(group = hrs, x = hrs, y = stresso)) +
  geom_point(size = 2, aes(y = stresso, x = hrs, 
                 #size = as.factor(hrs),
                 shape = as.factor(Temp),
                 color = as.factor(hrs))) +
  #xlab(expression(ln~(T*R^'3'*'/'~t))) +
  scale_y_log10(limits = c(10,750), 
                sec.axis = sec_axis(~., labels = NULL)) +
  scale_x_log10(sec.axis = sec_axis(~., labels = NULL)) +
  guides(colour = guide_legend(reverse = TRUE, title = "Time [hrs]", 
                               title.theme = element_text(colour="black", 
                                                          #face = "bold", 
                                                          size = 12))) +
  scale_color_manual(values=c("#00BF7D", "#BF7D00", "#7C00BF", "#BF0041")) +
  #guides(color = FALSE) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))
```


```{r}
stresscond <- fractSum %>%
  ggplot() +
  geom_point(aes(x = condAve, y = stressf, 
                 size = as.numeric(R3),
                 shape = as.factor(Temp),
                 color = as.factor(Ni.Vol.Corrected))) +
  geom_vline(xintercept = 1, color = "red",linetype = "dashed", size = 1) +
  annotate("text", x = 0.011, y = 108, fontface = 1, size = 4.5, label = expression(sigma[fr-min])) +
  geom_hline(yintercept = 100, color = "red",linetype = "dashed", size = 1) +
  annotate("text", x = 2.5, y = 0, fontface = 1, size = 4.5, label = expression(sigma[e-min])) +
  scale_x_log10(limits = c(0.01, 10000), 
                breaks = scales::trans_breaks("log10", function(x) 10^x),
                labels = trans_format("log10", math_format(10^.x)),
                sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(limits = c(0, 250),
    sec.axis = sec_axis(~., labels = NULL)) +
  #scale_color_gradientn(colours = hue_pal()(8)) +
  #geom_abline(slope = -50, intercept = -14,linetype = "dashed") +
  #geom_abline(slope = -50, intercept = 38,linetype = "dashed") +
  #geom_abline(slope = -50, intercept = 88,linetype = "dashed") +
  #geom_abline(slope = -50, intercept = 138,linetype = "dashed") +
  #geom_abline(slope = -50, intercept = 188,linetype = "dashed") +
  #geom_abline(slope = -50, intercept = 238,linetype = "dashed") +
  #geom_abline(slope = -50, intercept = 288,linetype = "dashed") +
  #geom_abline(slope = -50, intercept = 338,linetype = "dashed") +
  #geom_abline(slope = -50, intercept = 388,linetype = "dashed") +
  #geom_abline(slope = -50, intercept = 438,linetype = "dashed") +
  guides(color = FALSE, 
         shape = guide_legend(title = expression(Temp~'['*degree*C*']'), 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12)),
         size = FALSE) +
  ylab(expression(sigma[fr]*~'['*MPa*']')) +
  xlab(expression(sigma[e]*~'['*S*'/'*cm*']')) +
  annotate("rect", ymin = 100, ymax = Inf, xmin = 1, xmax = Inf, 
           fill="green", alpha = 0.05) +
  #scale_shape_manual(values=c(16, 17, 0, 2), na.translate = FALSE) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

#need to tie into zz-bNi

#Ashby Lines, background shading
#Improvements due to high nickel content, sacrificing energy density
#Gradient?
#higher extreme
#couldn't achieve these conductivities unless going to high nickel content

#Have: Tempk,time,Ni,R3 in zz
#Need: Th.Density incorporation
#Stress and Conductivity vs Microstructure

print(stresscond)
ggsave(filename = "./plotexports/plotexportstresscond.png", plot = stresscond, device = "png", width = 8, height = 6, units = "in")
rm(stresscond)
```

```{r}
normstresscond <- fractSum %>%
  filter(Temp >= 800) %>%
  filter(is.na(stressf) == FALSE) %>%
  mutate(stresso = stressf*exp((1.05-Th.Density/100)*coef(fracmodel)[2]*-1)) %>%
  mutate(ncp = 0.33/(Th.Density/105)) %>%
  mutate(condgamma = (0.5*Ni.Vol.Corrected) + 0.5) %>%
  mutate(K1 = condgamma/((1 - ncp)^2)) %>%
  mutate(sigmaideal = if_else(Ni.Vol.Corrected > ncp, 
                              K1*condNi*(Ni.Vol.Corrected - ncp)^2,
                              ((((2*Ni.Vol.Corrected*(1-ab))/((2*ab)+1))+1) / (1-(((1-ab)*Ni.Vol.Corrected)/(ab+1))))*condLTO)) %>%
  mutate(condnorm = condAve/sigmaideal) %>%
  #
  ggplot() +
  geom_point(aes(x = condAve, y = stresso, 
                 size = as.numeric(R3),
                 shape = as.factor(Temp),
                 color = as.factor(Ni.Vol.Corrected))) +
  #geom_vline(xintercept = 1, color = "red",linetype = "dashed", size = 1) +
  annotate("text", x = 0.011, y = 108, fontface = 1, size = 4.5, label = expression(sigma[fr-min])) +
  #geom_hline(yintercept = 100, color = "red",linetype = "dashed", size = 1) +
  annotate("text", x = 2.5, y = 0, fontface = 1, size = 4.5, label = expression(sigma[e-min])) +
  scale_x_log10(#limits = c(0.01, 10000), 
                breaks = scales::trans_breaks("log10", function(x) 10^x),
                labels = trans_format("log10", math_format(10^.x)),
                sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_continuous(#limits = c(0, 250),
    sec.axis = sec_axis(~., labels = NULL)) +
  #scale_color_gradientn(colours = hue_pal()(8)) +
  #geom_abline(slope = -50, intercept = -14,linetype = "dashed") +
  #geom_abline(slope = -50, intercept = 38,linetype = "dashed") +
  #geom_abline(slope = -50, intercept = 88,linetype = "dashed") +
  #geom_abline(slope = -50, intercept = 138,linetype = "dashed") +
  #geom_abline(slope = -50, intercept = 188,linetype = "dashed") +
  #geom_abline(slope = -50, intercept = 238,linetype = "dashed") +
  #geom_abline(slope = -50, intercept = 288,linetype = "dashed") +
  #geom_abline(slope = -50, intercept = 338,linetype = "dashed") +
  #geom_abline(slope = -50, intercept = 388,linetype = "dashed") +
  #geom_abline(slope = -50, intercept = 438,linetype = "dashed") +
  guides(color = FALSE, 
         shape = guide_legend(reverse = TRUE, title = expression(Temp~'['*degree*C*']'), 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12)),
         size = FALSE) +
  ylab(expression(sigma[o-fr]*~'['*MPa*']')) +
  xlab(expression(sigma[e]*~'['*S*'/'*cm*']')) +
  #annotate("rect", ymin = 100, ymax = Inf, xmin = 1, xmax = Inf, fill="green", alpha = 0.05) +
  #scale_shape_manual(values=c(16, 17, 0, 2), na.translate = FALSE) +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))

print(normstresscond)
ggsave(filename = "./plotexports/plotexportnormstresscond.png", plot = normstresscond, device = "png", width = 8, height = 6, units = "in")
rm(normstresscond)
```

```{r}
read.csv("./data-files/cracklengthdata.csv") %>%
  mutate(Ni.Vol.Corrected = Ni.Vol.Corrected/100) %>%
  ggplot() +
  geom_boxplot(aes(group = Ni.Vol.Corrected, x = Ni.Vol.Corrected, y = Kccurved)) +
  geom_point(size = 3, aes(x = Ni.Vol.Corrected, y = Kccurved, 
                 color = as.factor(Ni.Vol.Corrected))) +
  scale_x_continuous(sec.axis = sec_axis(~., labels = NULL)) +
  scale_y_log10(limits = c(0.005,2),sec.axis = sec_axis(~., labels = NULL)) +
  scale_color_manual(values=c("#000000", #"#F8766D", 
                              "#CD9600", 
                              #"#7CAE00", 
                              "#00BE67", 
                              #"#00BFC4", 
                              "#00A9FF", "#C77CFF", "#FF61CC")) +

  guides(color = guide_legend(reverse = TRUE, title = "Ni Vol.", 
                               #override.aes = list(size=4), 
                               title.theme = element_text(colour = "black",
                                                          #face = "bold",
                                                          size = 12))) +
  ylab(expression(K[c]*~'['*MPa*'*'*m^0.5*']')) +
  xlab("Nickel Volume Fraction") +
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))
```
