---
title: "LTO-Ni-RF"
author: "William Huddleston"
date: "2025-06-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
PC_compiled.full <- read.csv("./data-files/pc_scores_nnd_vrn_r3d_3skel.csv")

PC_compiled.full <- df_particles_fine %>%
  select(Labelfine, magx) %>%
  unique() %>%
  left_join(PC_compiled.full,., by = "Labelfine") %>%
  #filter(is.na(condAve) == FALSE) %>%
  mutate(condAve = log(condAve)) #%>%
  #filter(magx == 10)

PC_compiled <- PC_compiled.full %>%
  select(-1,-3) %>%
  #select(1:60,condAve) %>%
  #filter(is.na(condAve) == FALSE) %>%
  #
  select(Labelfine,
         nnd_pc1,nnd_pc2,nnd_pc3,nnd_pc4,
         vrn_pc1,vrn_pc2,vrn_pc3,vrn_pc4,
         r3d_pc1,r3d_pc2,r3d_pc3,r3d_pc4,
         skel_avbr_pc1,skel_avbr_pc2,skel_avbr_pc3,skel_avbr_pc4,
         skel_br_pc1,skel_br_pc2,skel_br_pc3,skel_br_pc4,
         skel_mxbr_pc1,skel_mxbr_pc2,skel_mxbr_pc3,skel_mxbr_pc4,
         Ni.Vol.Corrected, Temp, hrs,
         stressf,
         condAve)
```


```{r}
test1 <- c(seq(50,300,50))

test2 <- c(seq(0.3,0.7,0.1))

trainmatrix <- expand.grid(test1,test2) %>%
  rename(treecount = Var1) %>%
  rename(trainfrac = Var2)

rm(test1,test2)
```

```{r}

#for loop here to test each combination of treecount and trainfract
#for loop to run entire matrix multiple times
#save results in new dataframe
#do whole matrix for averages and PC datasets

```






#RUN MANY MODELS

```{r}
#model.csv generation
# (0) .modelid
# (1) .ntree (25-100)
# (2) .mtry  24/3 is default (4-12)
# (3) .sampsize obsnum is default
# (4) .nodesize (5 is default (1-9))
# (5) maxnodes
# (6) nPerm default is 1
# (7) importance
# (8) top-10 tree-size

# obsnum <- nrow(trainset.pc)
# 
# model.csv.meta <- data.frame("modelid" = 1:700) %>%
#   mutate(modelid = sprintf("%03i",modelid)) %>%
#   mutate(modelid = paste("PC-RF-",modelid, sep = "")) %>%
#   cbind(., ntree.int = sample(seq(from=10,to=100,by=1), size = 700, replace = T)) %>%
#   cbind(., mtry.int = sample(seq(from=4,to=12,by=1), size = 700, replace = T)) %>%
#   cbind(., sampsize.int = round(sample(seq(from = 0.1*obsnum, to = obsnum, by = 1), size = 700, replace = T))) %>%
#   cbind(., nodesize.int = sample(seq(from=1,to=9,by=1), size = 700, replace = T))
#   #maxnodes is a direct function of nodesize, don't need to control this value
#   
# 
# model.csv.meta %>%
#   mutate(code = paste(ntree.int,mtry.int,sampsize.int,nodesize.int, sep = "-")) %>% select(code) %>% unique(.)
# 
# write.table(model.csv.meta, file = "./MLexportsPC/PC-RF/model.csv", row.names = FALSE, sep = ",")

model.csv.meta <- read.csv("./MLexportsPC/PC-RF/model.csv", header = TRUE)
```


```{r}
#presplit trainset/testset for testing
trainset.pc.labels <- read.csv("./data-files/trainset-pc-save.csv", header = TRUE) %>% select(1)
testset.pc.labels <- read.csv("./data-files/testset-pc-save.csv", header = TRUE) %>% select(1)
```


```{r}
#model runs

model.meta.results <- data.frame()
#i <- 3

for (i in 1:700){


rfmodel.pc <- trainset.pc %>%
  select(-Ni.Vol.Corrected, -Temp, -hrs) %>%
  randomForest(x = ., y = trainset.pc$condAve, 
               ntree = model.csv.meta[i,2],
               mtry = model.csv.meta[i,3],
               sampsize = model.csv.meta[i,4],
               nodesize = model.csv.meta[i,5],
               )

#filename <- paste("./MLexportsPC/PC-RF-",i,".Rdata", sep = "")
#save(rfmodel.pc, file = filename)

rfresults.pc <- predict(rfmodel.pc, testset.pc) %>%
  as.data.frame() %>%
  cbind(as.data.frame(testset.pc$condAve),testset.pc.labels) %>%
  mutate(partition = "test")

colnames(rfresults.pc)[1] <- "prediction"
colnames(rfresults.pc)[2] <- "actual"


rfresults.training.pc <- predict(rfmodel.pc, trainset.pc) %>%
  as.data.frame() %>%
  cbind(as.data.frame(trainset.pc$condAve), trainset.pc.labels) %>%
  mutate(partition = "train")

colnames(rfresults.training.pc)[1] <- "prediction"
colnames(rfresults.training.pc)[2] <- "actual"

rfresults.out <- rbind(rfresults.pc,rfresults.training.pc)

filename <- paste("./MLexportsPC/PC-RF/",model.csv.meta[i,1],".csv", sep = "")

write.table(rfresults.out, file = filename, row.names = FALSE, sep = ",")


temp1 <- treesize(rfmodel.pc) %>%
  sort(decreasing = T) %>%
  .[1:10] %>%
  paste(collapse = " ") %>%
  as.character() %>%
  as.data.frame() %>%
  rename(., treesize10 = .)

temp2 <- importance(rfmodel.pc) %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  filter(rowname != "condAve") %>%
  mutate(IncNodePurity = round(IncNodePurity, 2)) %>%
  pull(IncNodePurity) %>%
  paste(collapse = " ") %>%
  as.data.frame() %>%
  rename(., Importance24 = .)

model.meta.results <- cbind(model.csv.meta[i,1], temp2, temp1) %>%
  rename(modelid = "model.csv.meta[i, 1]") %>%
  rbind(model.meta.results, .)

rm(temp1)
rm(temp2)

}


model.csv.meta %>%
  mutate(maxnodes.int = NA) %>%
  mutate(nPerm.int = NA) %>%
  left_join(., model.meta.results, by = "modelid") %>%
write.table(., file = "./MLexportsPC/PC-RF/modelout.csv", row.names = FALSE, sep = ",")

```





