---
title: "distributions-plot-code"
author: "whh36"
date: "8/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(ggridges)
```

```{r}

yourdataframe %>%
  #
  #filter(variable = XX) %>%
  #
  group_by(samplelabel) %>%
  ggplot() +
  #
  geom_ridgeline(aes(x = particlesize, y = variable, 
                     fill = as.factor(variable),
                     height = count/200, group = Labelfine)) + #height is either density or count
  #
  geom_density_ridges(size = 1, aes(x = R3, y = ni2-1, group = Ni.Vol.Corrected, 
                   fill = as.factor(Ni.Vol.Corrected))) +
  #
  # geom_rect(color = "black", aes(xmin = avevoronoix-0.01, #plots the average
  #               ymin = -Temp, 
  #               xmax = avevoronoix+0.01, 
  #               ymax = -Temp+100,
  #               fill = as.factor(Temp))) +
  #
  #
  theme_classic() +
  theme(axis.text.x = element_text(colour = "black", size = 16),
        axis.text.y = element_text(colour = "black", size = 16),
        axis.ticks = element_line(colour = "black", size = 1),
        axis.line = element_line(colour = 'black', size = 1),
        axis.title.x = element_text(colour = "black", size = 16),
        axis.title.y = element_text(colour = "black", size = 16),
        legend.text = element_text(colour="black", size = 12))
```
